/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { TheHogError } from "./the-hog-error.js";

export type PublicErrorResponseDtoData = {
  statusCode: number;
  error: string;
  message: string;
  path: string;
  requestId?: string | undefined;
  timestamp: string;
  errors?: Array<models.PublicValidationErrorItemDto> | undefined;
};

export class PublicErrorResponseDto extends TheHogError {
  error: string;
  path: string;
  requestId?: string | undefined;
  timestamp: string;
  errors?: Array<models.PublicValidationErrorItemDto> | undefined;

  /** The original data that was passed to this error instance. */
  data$: PublicErrorResponseDtoData;

  constructor(
    err: PublicErrorResponseDtoData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    this.path = err.path;
    if (err.requestId != null) this.requestId = err.requestId;
    this.timestamp = err.timestamp;
    if (err.errors != null) this.errors = err.errors;

    this.name = "PublicErrorResponseDto";
  }
}

/** @internal */
export const PublicErrorResponseDto$inboundSchema: z.ZodMiniType<
  PublicErrorResponseDto,
  unknown
> = z.pipe(
  z.object({
    statusCode: types.number(),
    error: types.string(),
    message: types.string(),
    path: types.string(),
    requestId: types.optional(types.string()),
    timestamp: types.string(),
    errors: types.optional(
      z.array(models.PublicValidationErrorItemDto$inboundSchema),
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PublicErrorResponseDto(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
