/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function batchScrapeWebPages(
  client: ClientSDK,
body: models.PlatformWebScrapeBatchDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.BatchScrapeWebPagesResponse> {
  const input = parseInput(operations.BatchScrapeWebPagesRequest$outboundSchema, { body, idempotencyKey }, "batchScrapeWebPages input");
  return sendJson(client, {
    operationId: "batchScrapeWebPages",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/web/scrape/batch")({  }),
    query: {},
    body: input.body,
    idempotencyKey: input.idempotencyKey,
    responseSchemas: [
    { status: 202, schema: operations.BatchScrapeWebPagesResponse$inboundSchemas[202] },
    ],
  }, options);
}
