/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import { matchStatusCode } from "../lib/http.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { TheHogAPIError } from "../models/errors/the-hog-api-error.js";

type ResponseSchema = { status: number; schema: z.ZodType };

type SendJsonConfig = {
  operationId: string;
  method: string;
  path: string;
  query?: Record<string, unknown> | undefined;
  body?: unknown | undefined;
  idempotencyKey?: string | undefined;
  responseSchemas: ResponseSchema[];
};

export function parseInput<T extends z.ZodType>(schema: T, value: unknown, label: string): z.infer<T> {
  try {
    return schema.parse(value);
  } catch (cause) {
    throw new SDKValidationError(`Failed to validate ${label}`, cause, value);
  }
}

export async function sendJson<T>(client: ClientSDK, config: SendJsonConfig, options?: RequestOptions): Promise<T> {
  const query = encodeQuery(config.query ?? {});
  const headers = new Headers({ Accept: "application/json" });
  let body: string | undefined;
  if (config.body !== undefined) {
    headers.set("Content-Type", "application/json");
    body = JSON.stringify(config.body);
  }
  if (config.idempotencyKey) {
    headers.set("Idempotency-Key", config.idempotencyKey);
  }

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);
  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: config.operationId,
    oAuth2Scopes: null,
    resolvedSecurity: requestSecurity,
    securitySource: client._options.security,
    retryConfig: options?.retries || client._options.retryConfig || {
      strategy: "backoff" as const,
      backoff: { initialInterval: 500, maxInterval: 30000, exponent: 1.5, maxElapsedTime: 120000 },
      retryConnectionErrors: true,
    },
    retryCodes: options?.retryCodes || ["408", "429", "5XX"],
  };

  const requestResult = client._createRequest(context, {
    security: requestSecurity,
    method: config.method,
    baseURL: options?.serverURL,
    path: config.path,
    query,
    headers,
    body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestResult.ok) {
    throw requestResult.error;
  }
  const request = requestResult.value;

  const responseResult = await client._do(request, {
    context,
    isErrorStatusCode: (statusCode: number) => matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!responseResult.ok) {
    throw responseResult.error;
  }

  const response = responseResult.value;
  const text = await response.text();
  const payload = parsePayload(text, response.headers.get("content-type"));
  if (!response.ok) {
    throw new TheHogAPIError(`The Hog API request failed with status ${response.status}`, response.status, response, payload, response.headers.get("x-request-id") ?? undefined);
  }

  const responseSchema = config.responseSchemas.find((entry) => entry.status === response.status)?.schema;
  if (!responseSchema) {
    return payload as T;
  }
  try {
    return responseSchema.parse(payload) as T;
  } catch (cause) {
    throw new ResponseValidationError("Response validation failed", {
      response,
      request,
      body: text,
      cause,
      rawValue: payload,
      rawMessage: "Response validation failed",
    });
  }
}

function encodeQuery(query: Record<string, unknown>): string {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (value == null) continue;
    if (Array.isArray(value)) {
      for (const item of value) params.append(key, String(item));
    } else {
      params.set(key, String(value));
    }
  }
  return params.toString();
}

function parsePayload(text: string, contentType: string | null): unknown {
  if (!text) return undefined;
  if ((contentType ?? "").includes("application/json")) {
    return JSON.parse(text);
  }
  return text;
}
