/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function crawlWebSite(
  client: ClientSDK,
body: models.PlatformWebCrawlDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.CrawlWebSiteResponse> {
  const input = parseInput(operations.CrawlWebSiteRequest$outboundSchema, { body, idempotencyKey }, "crawlWebSite input");
  return sendJson(client, {
    operationId: "crawlWebSite",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/web/crawl")({  }),
    query: {},
    body: input.body,
    idempotencyKey: input.idempotencyKey,
    responseSchemas: [
    { status: 202, schema: operations.CrawlWebSiteResponse$inboundSchemas[202] },
    ],
  }, options);
}
