/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function createMonitor(
  client: ClientSDK,
body: models.CreateMonitorDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.CreateMonitorResponse> {
  const input = parseInput(operations.CreateMonitorRequest$outboundSchema, { body, idempotencyKey }, "createMonitor input");
  return sendJson(client, {
    operationId: "createMonitor",
    method: "POST",
    path: pathToFunc("/api/v1/monitors")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 201, schema: operations.CreateMonitorResponse$inboundSchemas[201] },
    ],
  }, options);
}
