/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function deleteMonitor(
  client: ClientSDK,
id: string,
options?: RequestOptions,

): Promise<operations.DeleteMonitorResponse> {
  const input = parseInput(operations.DeleteMonitorRequest$outboundSchema, { id }, "deleteMonitor input");
  return sendJson(client, {
    operationId: "deleteMonitor",
    method: "DELETE",
    path: pathToFunc("/api/v1/monitors/{id}")({ id: input.id }),
    query: {},
    body: undefined,
    idempotencyKey: undefined,
    responseSchemas: [
    ],
  }, options);
}
