/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function findLinkedInCompanies(
  client: ClientSDK,
body: models.PlatformLinkedInFinderDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.FindLinkedInCompaniesResponse> {
  const input = parseInput(operations.FindLinkedInCompaniesRequest$outboundSchema, { body, idempotencyKey }, "findLinkedInCompanies input");
  return sendJson(client, {
    operationId: "findLinkedInCompanies",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/linkedin/finder")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.FindLinkedInCompaniesResponse$inboundSchemas[200] },
    ],
  }, options);
}
