/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function getOperation(
  client: ClientSDK,
id: string,
options?: RequestOptions,

): Promise<operations.GetOperationResponse> {
  const input = parseInput(operations.GetOperationRequest$outboundSchema, { id }, "getOperation input");
  return sendJson(client, {
    operationId: "getOperation",
    method: "GET",
    path: pathToFunc("/api/operations/{id}")({ id: input.id }),
    query: {},
    body: undefined,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.GetOperationResponse$inboundSchemas[200] },
    ],
  }, options);
}
