/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function getLinkedInProfile(
  client: ClientSDK,
body: models.PlatformLinkedInProfileDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.GetLinkedInProfileResponse> {
  const input = parseInput(operations.GetLinkedInProfileRequest$outboundSchema, { body, idempotencyKey }, "getLinkedInProfile input");
  return sendJson(client, {
    operationId: "getLinkedInProfile",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/linkedin/profile")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.GetLinkedInProfileResponse$inboundSchemas[200] },
    ],
  }, options);
}
