/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function getInstagramProfile(
  client: ClientSDK,
body: models.PlatformInstagramUsernameDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.GetInstagramProfileResponse> {
  const input = parseInput(operations.GetInstagramProfileRequest$outboundSchema, { body, idempotencyKey }, "getInstagramProfile input");
  return sendJson(client, {
    operationId: "getInstagramProfile",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/instagram/profile")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.GetInstagramProfileResponse$inboundSchemas[200] },
    ],
  }, options);
}
