/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function getTikTokProfile(
  client: ClientSDK,
body: models.PlatformTikTokUsernameDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.GetTikTokProfileResponse> {
  const input = parseInput(operations.GetTikTokProfileRequest$outboundSchema, { body, idempotencyKey }, "getTikTokProfile input");
  return sendJson(client, {
    operationId: "getTikTokProfile",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/tiktok/profile")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.GetTikTokProfileResponse$inboundSchemas[200] },
    ],
  }, options);
}
