/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function listMonitors(
  client: ClientSDK,
query: Partial<operations.ListMonitorsRequest> = {},
options?: RequestOptions,

): Promise<operations.ListMonitorsResponse> {
  const input = parseInput(operations.ListMonitorsRequest$outboundSchema, { ...query }, "listMonitors input");
  return sendJson(client, {
    operationId: "listMonitors",
    method: "GET",
    path: pathToFunc("/api/v1/monitors")({  }),
    query: { "status": input.status, "limit": input.limit, "cursor": input.cursor },
    body: undefined,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ListMonitorsResponse$inboundSchemas[200] },
    ],
  }, options);
}
