/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function listSearches(
  client: ClientSDK,
query: Partial<operations.ListSearchesRequest> = {},
options?: RequestOptions,

): Promise<operations.ListSearchesResponse> {
  const input = parseInput(operations.ListSearchesRequest$outboundSchema, { ...query }, "listSearches input");
  return sendJson(client, {
    operationId: "listSearches",
    method: "GET",
    path: pathToFunc("/api/v1/search")({  }),
    query: { "type": input.type, "limit": input.limit, "cursor": input.cursor },
    body: undefined,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ListSearchesResponse$inboundSchemas[200] },
    ],
  }, options);
}
