/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function listLinkedInPostReactions(
  client: ClientSDK,
body: models.PlatformLinkedInPostUrlsDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.ListLinkedInPostReactionsResponse> {
  const input = parseInput(operations.ListLinkedInPostReactionsRequest$outboundSchema, { body, idempotencyKey }, "listLinkedInPostReactions input");
  return sendJson(client, {
    operationId: "listLinkedInPostReactions",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/linkedin/post-reactions")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ListLinkedInPostReactionsResponse$inboundSchemas[200] },
    ],
  }, options);
}
