/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function listInstagramFollowers(
  client: ClientSDK,
body: models.PlatformInstagramFollowersDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.ListInstagramFollowersResponse> {
  const input = parseInput(operations.ListInstagramFollowersRequest$outboundSchema, { body, idempotencyKey }, "listInstagramFollowers input");
  return sendJson(client, {
    operationId: "listInstagramFollowers",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/instagram/followers")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ListInstagramFollowersResponse$inboundSchemas[200] },
    ],
  }, options);
}
