/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function listMonitorEvents(
  client: ClientSDK,
id: string,
query: Partial<operations.ListMonitorEventsRequest> = {},
options?: RequestOptions,

): Promise<operations.ListMonitorEventsResponse> {
  const input = parseInput(operations.ListMonitorEventsRequest$outboundSchema, { id, ...query }, "listMonitorEvents input");
  return sendJson(client, {
    operationId: "listMonitorEvents",
    method: "GET",
    path: pathToFunc("/api/v1/monitors/{id}/events")({ id: input.id }),
    query: { "since": input.since, "limit": input.limit, "cursor": input.cursor },
    body: undefined,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ListMonitorEventsResponse$inboundSchemas[200] },
    ],
  }, options);
}
