/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function listLinkedInPostComments(
  client: ClientSDK,
body: models.PlatformLinkedInPostUrlsDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.ListLinkedInPostCommentsResponse> {
  const input = parseInput(operations.ListLinkedInPostCommentsRequest$outboundSchema, { body, idempotencyKey }, "listLinkedInPostComments input");
  return sendJson(client, {
    operationId: "listLinkedInPostComments",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/linkedin/post-comments")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ListLinkedInPostCommentsResponse$inboundSchemas[200] },
    ],
  }, options);
}
