/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function listLinkedInProfilePosts(
  client: ClientSDK,
body: models.PlatformLinkedInProfilePostsDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.ListLinkedInProfilePostsResponse> {
  const input = parseInput(operations.ListLinkedInProfilePostsRequest$outboundSchema, { body, idempotencyKey }, "listLinkedInProfilePosts input");
  return sendJson(client, {
    operationId: "listLinkedInProfilePosts",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/linkedin/profile-posts")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ListLinkedInProfilePostsResponse$inboundSchemas[200] },
    ],
  }, options);
}
