/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function listLinkedInProfileComments(
  client: ClientSDK,
body: models.PlatformLinkedInProfileActivityDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.ListLinkedInProfileCommentsResponse> {
  const input = parseInput(operations.ListLinkedInProfileCommentsRequest$outboundSchema, { body, idempotencyKey }, "listLinkedInProfileComments input");
  return sendJson(client, {
    operationId: "listLinkedInProfileComments",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/linkedin/profile-comments")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ListLinkedInProfileCommentsResponse$inboundSchemas[200] },
    ],
  }, options);
}
