/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function runMonitorNow(
  client: ClientSDK,
id: string,
body?: models.RunNowBodyDto | undefined,
options?: RequestOptions,

): Promise<operations.RunMonitorNowResponse> {
  const input = parseInput(operations.RunMonitorNowRequest$outboundSchema, { id, body }, "runMonitorNow input");
  return sendJson(client, {
    operationId: "runMonitorNow",
    method: "POST",
    path: pathToFunc("/api/v1/monitors/{id}/run-now")({ id: input.id }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 202, schema: operations.RunMonitorNowResponse$inboundSchemas[202] },
    ],
  }, options);
}
