/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function scrapeWebPage(
  client: ClientSDK,
body: models.PlatformWebScrapeDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.ScrapeWebPageResponse> {
  const input = parseInput(operations.ScrapeWebPageRequest$outboundSchema, { body, idempotencyKey }, "scrapeWebPage input");
  return sendJson(client, {
    operationId: "scrapeWebPage",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/web/scrape")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.ScrapeWebPageResponse$inboundSchemas[200] },
    ],
  }, options);
}
