/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function searchPeople(
  client: ClientSDK,
body: models.PostPeopleSearchDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.SearchPeopleResponse> {
  const input = parseInput(operations.SearchPeopleRequest$outboundSchema, { body, idempotencyKey }, "searchPeople input");
  return sendJson(client, {
    operationId: "searchPeople",
    method: "POST",
    path: pathToFunc("/api/v1/people/search")({  }),
    query: {},
    body: input.body,
    idempotencyKey: input.idempotencyKey,
    responseSchemas: [
    { status: 202, schema: operations.SearchPeopleResponse$inboundSchemas[202] },
    ],
  }, options);
}
