/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function searchLinkedInKeywordPosts(
  client: ClientSDK,
body: models.PlatformLinkedInKeywordPostsDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.SearchLinkedInKeywordPostsResponse> {
  const input = parseInput(operations.SearchLinkedInKeywordPostsRequest$outboundSchema, { body, idempotencyKey }, "searchLinkedInKeywordPosts input");
  return sendJson(client, {
    operationId: "searchLinkedInKeywordPosts",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/linkedin/keyword-posts")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.SearchLinkedInKeywordPostsResponse$inboundSchemas[200] },
    ],
  }, options);
}
