/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function searchWeb(
  client: ClientSDK,
body: models.PlatformWebSearchDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.SearchWebResponse> {
  const input = parseInput(operations.SearchWebRequest$outboundSchema, { body, idempotencyKey }, "searchWeb input");
  return sendJson(client, {
    operationId: "searchWeb",
    method: "POST",
    path: pathToFunc("/api/v1/platform/scrapers/web/search")({  }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.SearchWebResponse$inboundSchemas[200] },
    ],
  }, options);
}
