/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function startDeepResearch(
  client: ClientSDK,
body: models.DeepResearchRequestDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.StartDeepResearchResponse> {
  const input = parseInput(operations.StartDeepResearchRequest$outboundSchema, { body, idempotencyKey }, "startDeepResearch input");
  return sendJson(client, {
    operationId: "startDeepResearch",
    method: "POST",
    path: pathToFunc("/api/deep-research")({  }),
    query: {},
    body: input.body,
    idempotencyKey: input.idempotencyKey,
    responseSchemas: [
    { status: 202, schema: operations.StartDeepResearchResponse$inboundSchemas[202] },
    ],
  }, options);
}
