/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function submitSearch(
  client: ClientSDK,
body: models.PostSearchDto,
sync?: boolean | undefined,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.SubmitSearchResponse> {
  const input = parseInput(operations.SubmitSearchRequest$outboundSchema, { body, sync, idempotencyKey }, "submitSearch input");
  return sendJson(client, {
    operationId: "submitSearch",
    method: "POST",
    path: pathToFunc("/api/v1/search")({  }),
    query: { "sync": input.sync },
    body: input.body,
    idempotencyKey: input.idempotencyKey,
    responseSchemas: [
    { status: 200, schema: operations.SubmitSearchResponse$inboundSchemas[200] },
    { status: 202, schema: operations.SubmitSearchResponse$inboundSchemas[202] },
    ],
  }, options);
}
