/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function submitEnrichment(
  client: ClientSDK,
body: models.PostEnrichmentDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.SubmitEnrichmentResponse> {
  const input = parseInput(operations.SubmitEnrichmentRequest$outboundSchema, { body, idempotencyKey }, "submitEnrichment input");
  return sendJson(client, {
    operationId: "submitEnrichment",
    method: "POST",
    path: pathToFunc("/api/enrichments")({  }),
    query: {},
    body: input.body,
    idempotencyKey: input.idempotencyKey,
    responseSchemas: [
    { status: 200, schema: operations.SubmitEnrichmentResponse$inboundSchemas[200] },
    { status: 202, schema: operations.SubmitEnrichmentResponse$inboundSchemas[202] },
    ],
  }, options);
}
