/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { pathToFunc } from "../lib/url.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { parseInput, sendJson } from "./common.js";
export async function updateMonitor(
  client: ClientSDK,
id: string,
body: models.UpdateMonitorDto,
idempotencyKey?: string | undefined,
options?: RequestOptions,

): Promise<operations.UpdateMonitorResponse> {
  const input = parseInput(operations.UpdateMonitorRequest$outboundSchema, { id, body, idempotencyKey }, "updateMonitor input");
  return sendJson(client, {
    operationId: "updateMonitor",
    method: "PATCH",
    path: pathToFunc("/api/v1/monitors/{id}")({ id: input.id }),
    query: {},
    body: input.body,
    idempotencyKey: undefined,
    responseSchemas: [
    { status: 200, schema: operations.UpdateMonitorResponse$inboundSchemas[200] },
    ],
  }, options);
}
