/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { searchCompanies } from "../funcs/search-companies.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class Companies extends ClientSDK {
  /**
   * Search companies
   */
  async search(body: models.PostCompanySearchDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.SearchCompaniesResponse> {
    return searchCompanies(this, body, idempotencyKey, options);
  }
}
