/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { companiesSearch } from "../funcs/companies-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Companies extends ClientSDK {
  /**
   * Search companies
   *
   * @remarks
   * Async company discovery. Returns operationId; poll GET /api/operations/:id.
   */
  async search(
    body: models.PostCompanySearchDto,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<models.EntitySearchAcceptedPublicDto> {
    return unwrapAsync(companiesSearch(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }
}
