/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { startDeepResearch } from "../funcs/start-deep-research.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class DeepResearch extends ClientSDK {
  /**
   * Start deep research
   */
  async start(body: models.DeepResearchRequestDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.StartDeepResearchResponse> {
    return startDeepResearch(this, body, idempotencyKey, options);
  }
}
