/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deepResearchStart } from "../funcs/deep-research-start.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DeepResearch extends ClientSDK {
  /**
   * Start deep research
   *
   * @remarks
   * Start a deep research job with a prompt and JSON Schema. The response includes an operation ID and poll URL for retrieving the structured result.
   */
  async start(
    body: models.DeepResearchRequestDto,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<models.DeepResearchQueuedResponseDto> {
    return unwrapAsync(deepResearchStart(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }
}
