/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { getEnrichment } from "../funcs/get-enrichment.js";
import { submitEnrichment } from "../funcs/submit-enrichment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class Enrichments extends ClientSDK {
  /**
   * Get enrichment
   */
  async get(id: string, options?: RequestOptions): Promise<operations.GetEnrichmentResponse> {
    return getEnrichment(this, id, options);
  }
  /**
   * Submit enrichment
   */
  async submit(body: models.PostEnrichmentDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.SubmitEnrichmentResponse> {
    return submitEnrichment(this, body, idempotencyKey, options);
  }
}
