/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { enrichmentsGet } from "../funcs/enrichments-get.js";
import { enrichmentsSubmit } from "../funcs/enrichments-submit.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Enrichments extends ClientSDK {
  /**
   * Submit enrichment
   *
   * @remarks
   * Enrich one contact or a batch of contacts with requested fields such as verified email, phone, and signals. Small contact-only requests can complete immediately; larger requests return an operation to poll.
   */
  async submit(
    body: models.PostEnrichmentDto,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.SubmitEnrichmentResponse> {
    return unwrapAsync(enrichmentsSubmit(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Get enrichment
   *
   * @remarks
   * Check the status of an enrichment request and retrieve the result once it completes.
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<models.OperationResponseDto> {
    return unwrapAsync(enrichmentsGet(
      this,
      id,
      options,
    ));
  }
}
