/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scrapersInstagramGetPost } from "../funcs/scrapers-instagram-get-post.js";
import { scrapersInstagramGetProfile } from "../funcs/scrapers-instagram-get-profile.js";
import { scrapersInstagramListFollowers } from "../funcs/scrapers-instagram-list-followers.js";
import { scrapersInstagramListFollowing } from "../funcs/scrapers-instagram-list-following.js";
import { scrapersInstagramListPostComments } from "../funcs/scrapers-instagram-list-post-comments.js";
import { scrapersInstagramListPosts } from "../funcs/scrapers-instagram-list-posts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Instagram extends ClientSDK {
  /**
   * Get Instagram profile
   *
   * @remarks
   * Fetch public profile details for an Instagram username.
   */
  async getProfile(
    request: models.PlatformInstagramUsernameDto,
    options?: RequestOptions,
  ): Promise<operations.GetInstagramProfileResponseBody> {
    return unwrapAsync(scrapersInstagramGetProfile(
      this,
      request,
      options,
    ));
  }

  /**
   * List Instagram posts
   *
   * @remarks
   * Fetch recent posts for an Instagram username.
   */
  async listPosts(
    request: models.PlatformInstagramUsernameDto,
    options?: RequestOptions,
  ): Promise<operations.ListInstagramPostsResponseBody> {
    return unwrapAsync(scrapersInstagramListPosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Instagram post
   *
   * @remarks
   * Fetch details for an Instagram post or reel URL.
   */
  async getPost(
    request: models.PlatformInstagramPostDetailsDto,
    options?: RequestOptions,
  ): Promise<operations.GetInstagramPostResponseBody> {
    return unwrapAsync(scrapersInstagramGetPost(
      this,
      request,
      options,
    ));
  }

  /**
   * List Instagram post comments
   *
   * @remarks
   * Fetch comments for an Instagram post or reel URL.
   */
  async listPostComments(
    request: models.PlatformInstagramPostCommentsDto,
    options?: RequestOptions,
  ): Promise<operations.ListInstagramPostCommentsResponseBody> {
    return unwrapAsync(scrapersInstagramListPostComments(
      this,
      request,
      options,
    ));
  }

  /**
   * List Instagram followers
   *
   * @remarks
   * Fetch followers for an Instagram username.
   */
  async listFollowers(
    request: models.PlatformInstagramFollowersDto,
    options?: RequestOptions,
  ): Promise<operations.ListInstagramFollowersResponseBody> {
    return unwrapAsync(scrapersInstagramListFollowers(
      this,
      request,
      options,
    ));
  }

  /**
   * List Instagram following
   *
   * @remarks
   * Fetch accounts followed by an Instagram username.
   */
  async listFollowing(
    request: models.PlatformInstagramFollowingDto,
    options?: RequestOptions,
  ): Promise<operations.ListInstagramFollowingResponseBody> {
    return unwrapAsync(scrapersInstagramListFollowing(
      this,
      request,
      options,
    ));
  }
}
