/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { getInstagramPost } from "../funcs/get-instagram-post.js";
import { getInstagramProfile } from "../funcs/get-instagram-profile.js";
import { listInstagramFollowers } from "../funcs/list-instagram-followers.js";
import { listInstagramFollowing } from "../funcs/list-instagram-following.js";
import { listInstagramPostComments } from "../funcs/list-instagram-post-comments.js";
import { listInstagramPosts } from "../funcs/list-instagram-posts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class InstagramScrapers extends ClientSDK {
  /**
   * Get Instagram post
   */
  async getPost(body: models.PlatformInstagramPostDetailsDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.GetInstagramPostResponse> {
    return getInstagramPost(this, body, idempotencyKey, options);
  }
  /**
   * Get Instagram profile
   */
  async getProfile(body: models.PlatformInstagramUsernameDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.GetInstagramProfileResponse> {
    return getInstagramProfile(this, body, idempotencyKey, options);
  }
  /**
   * List Instagram followers
   */
  async listFollowers(body: models.PlatformInstagramFollowersDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListInstagramFollowersResponse> {
    return listInstagramFollowers(this, body, idempotencyKey, options);
  }
  /**
   * List Instagram following
   */
  async listFollowing(body: models.PlatformInstagramFollowingDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListInstagramFollowingResponse> {
    return listInstagramFollowing(this, body, idempotencyKey, options);
  }
  /**
   * List Instagram post comments
   */
  async listPostComments(body: models.PlatformInstagramPostCommentsDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListInstagramPostCommentsResponse> {
    return listInstagramPostComments(this, body, idempotencyKey, options);
  }
  /**
   * List Instagram posts
   */
  async listPosts(body: models.PlatformInstagramUsernameDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListInstagramPostsResponse> {
    return listInstagramPosts(this, body, idempotencyKey, options);
  }
}
