/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scrapersLinkedinFindCompanies } from "../funcs/scrapers-linkedin-find-companies.js";
import { scrapersLinkedinGetCompany } from "../funcs/scrapers-linkedin-get-company.js";
import { scrapersLinkedinGetProfile } from "../funcs/scrapers-linkedin-get-profile.js";
import { scrapersLinkedinListCompanyPosts } from "../funcs/scrapers-linkedin-list-company-posts.js";
import { scrapersLinkedinListPostComments } from "../funcs/scrapers-linkedin-list-post-comments.js";
import { scrapersLinkedinListPostReactions } from "../funcs/scrapers-linkedin-list-post-reactions.js";
import { scrapersLinkedinListProfileComments } from "../funcs/scrapers-linkedin-list-profile-comments.js";
import { scrapersLinkedinListProfilePosts } from "../funcs/scrapers-linkedin-list-profile-posts.js";
import { scrapersLinkedinListProfileReactions } from "../funcs/scrapers-linkedin-list-profile-reactions.js";
import { scrapersLinkedinSearchKeywordPosts } from "../funcs/scrapers-linkedin-search-keyword-posts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Linkedin extends ClientSDK {
  /**
   * Find LinkedIn companies
   *
   * @remarks
   * Find LinkedIn company URLs from website domains or URLs.
   */
  async findCompanies(
    request: models.PlatformLinkedInFinderDto,
    options?: RequestOptions,
  ): Promise<operations.FindLinkedInCompaniesResponseBody> {
    return unwrapAsync(scrapersLinkedinFindCompanies(
      this,
      request,
      options,
    ));
  }

  /**
   * Get LinkedIn profile
   *
   * @remarks
   * Fetch public profile details for a LinkedIn username.
   */
  async getProfile(
    request: models.PlatformLinkedInProfileDto,
    options?: RequestOptions,
  ): Promise<operations.GetLinkedInProfileResponseBody> {
    return unwrapAsync(scrapersLinkedinGetProfile(
      this,
      request,
      options,
    ));
  }

  /**
   * Get LinkedIn company
   *
   * @remarks
   * Fetch public company details for a LinkedIn slug or URL.
   */
  async getCompany(
    request: models.PlatformLinkedInCompanyDto,
    options?: RequestOptions,
  ): Promise<operations.GetLinkedInCompanyResponseBody> {
    return unwrapAsync(scrapersLinkedinGetCompany(
      this,
      request,
      options,
    ));
  }

  /**
   * List LinkedIn company posts
   *
   * @remarks
   * Fetch recent posts for a LinkedIn company page.
   */
  async listCompanyPosts(
    request: models.PlatformLinkedInCompanyPostsDto,
    options?: RequestOptions,
  ): Promise<operations.ListLinkedInCompanyPostsResponseBody> {
    return unwrapAsync(scrapersLinkedinListCompanyPosts(
      this,
      request,
      options,
    ));
  }

  /**
   * List LinkedIn profile posts
   *
   * @remarks
   * Fetch recent posts for a LinkedIn profile.
   */
  async listProfilePosts(
    request: models.PlatformLinkedInProfilePostsDto,
    options?: RequestOptions,
  ): Promise<operations.ListLinkedInProfilePostsResponseBody> {
    return unwrapAsync(scrapersLinkedinListProfilePosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Search LinkedIn posts
   *
   * @remarks
   * Search LinkedIn posts by keyword.
   */
  async searchKeywordPosts(
    request: models.PlatformLinkedInKeywordPostsDto,
    options?: RequestOptions,
  ): Promise<operations.SearchLinkedInKeywordPostsResponseBody> {
    return unwrapAsync(scrapersLinkedinSearchKeywordPosts(
      this,
      request,
      options,
    ));
  }

  /**
   * List LinkedIn post reactions
   *
   * @remarks
   * Fetch reactions for one or more LinkedIn post URLs.
   */
  async listPostReactions(
    request: models.PlatformLinkedInPostUrlsDto,
    options?: RequestOptions,
  ): Promise<operations.ListLinkedInPostReactionsResponseBody> {
    return unwrapAsync(scrapersLinkedinListPostReactions(
      this,
      request,
      options,
    ));
  }

  /**
   * List LinkedIn post comments
   *
   * @remarks
   * Fetch comments for one or more LinkedIn post URLs.
   */
  async listPostComments(
    request: models.PlatformLinkedInPostUrlsDto,
    options?: RequestOptions,
  ): Promise<operations.ListLinkedInPostCommentsResponseBody> {
    return unwrapAsync(scrapersLinkedinListPostComments(
      this,
      request,
      options,
    ));
  }

  /**
   * List LinkedIn profile reactions
   *
   * @remarks
   * Fetch recent LinkedIn posts a public profile has reacted to.
   */
  async listProfileReactions(
    request: models.PlatformLinkedInProfileActivityDto,
    options?: RequestOptions,
  ): Promise<operations.ListLinkedInProfileReactionsResponseBody> {
    return unwrapAsync(scrapersLinkedinListProfileReactions(
      this,
      request,
      options,
    ));
  }

  /**
   * List LinkedIn profile comments
   *
   * @remarks
   * Fetch recent LinkedIn posts a public profile has commented on.
   */
  async listProfileComments(
    request: models.PlatformLinkedInProfileActivityDto,
    options?: RequestOptions,
  ): Promise<operations.ListLinkedInProfileCommentsResponseBody> {
    return unwrapAsync(scrapersLinkedinListProfileComments(
      this,
      request,
      options,
    ));
  }
}
