/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { findLinkedInCompanies } from "../funcs/find-linked-in-companies.js";
import { getLinkedInCompany } from "../funcs/get-linked-in-company.js";
import { getLinkedInProfile } from "../funcs/get-linked-in-profile.js";
import { listLinkedInCompanyPosts } from "../funcs/list-linked-in-company-posts.js";
import { listLinkedInPostComments } from "../funcs/list-linked-in-post-comments.js";
import { listLinkedInPostReactions } from "../funcs/list-linked-in-post-reactions.js";
import { listLinkedInProfileComments } from "../funcs/list-linked-in-profile-comments.js";
import { listLinkedInProfilePosts } from "../funcs/list-linked-in-profile-posts.js";
import { listLinkedInProfileReactions } from "../funcs/list-linked-in-profile-reactions.js";
import { searchLinkedInKeywordPosts } from "../funcs/search-linked-in-keyword-posts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class LinkedInScrapers extends ClientSDK {
  /**
   * Find LinkedIn companies
   */
  async findCompanies(body: models.PlatformLinkedInFinderDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.FindLinkedInCompaniesResponse> {
    return findLinkedInCompanies(this, body, idempotencyKey, options);
  }
  /**
   * Get LinkedIn company
   */
  async getCompany(body: models.PlatformLinkedInCompanyDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.GetLinkedInCompanyResponse> {
    return getLinkedInCompany(this, body, idempotencyKey, options);
  }
  /**
   * Get LinkedIn profile
   */
  async getProfile(body: models.PlatformLinkedInProfileDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.GetLinkedInProfileResponse> {
    return getLinkedInProfile(this, body, idempotencyKey, options);
  }
  /**
   * List LinkedIn company posts
   */
  async listCompanyPosts(body: models.PlatformLinkedInCompanyPostsDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListLinkedInCompanyPostsResponse> {
    return listLinkedInCompanyPosts(this, body, idempotencyKey, options);
  }
  /**
   * List LinkedIn post comments
   */
  async listPostComments(body: models.PlatformLinkedInPostUrlsDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListLinkedInPostCommentsResponse> {
    return listLinkedInPostComments(this, body, idempotencyKey, options);
  }
  /**
   * List LinkedIn post reactions
   */
  async listPostReactions(body: models.PlatformLinkedInPostUrlsDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListLinkedInPostReactionsResponse> {
    return listLinkedInPostReactions(this, body, idempotencyKey, options);
  }
  /**
   * List LinkedIn profile comments
   */
  async listProfileComments(body: models.PlatformLinkedInProfileActivityDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListLinkedInProfileCommentsResponse> {
    return listLinkedInProfileComments(this, body, idempotencyKey, options);
  }
  /**
   * List LinkedIn profile posts
   */
  async listProfilePosts(body: models.PlatformLinkedInProfilePostsDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListLinkedInProfilePostsResponse> {
    return listLinkedInProfilePosts(this, body, idempotencyKey, options);
  }
  /**
   * List LinkedIn profile reactions
   */
  async listProfileReactions(body: models.PlatformLinkedInProfileActivityDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ListLinkedInProfileReactionsResponse> {
    return listLinkedInProfileReactions(this, body, idempotencyKey, options);
  }
  /**
   * Search LinkedIn posts
   */
  async searchKeywordPosts(body: models.PlatformLinkedInKeywordPostsDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.SearchLinkedInKeywordPostsResponse> {
    return searchLinkedInKeywordPosts(this, body, idempotencyKey, options);
  }
}
