/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { createMonitor } from "../funcs/create-monitor.js";
import { deleteMonitor } from "../funcs/delete-monitor.js";
import { getMonitor } from "../funcs/get-monitor.js";
import { listMonitorEvents } from "../funcs/list-monitor-events.js";
import { listMonitors } from "../funcs/list-monitors.js";
import { runMonitorNow } from "../funcs/run-monitor-now.js";
import { updateMonitor } from "../funcs/update-monitor.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class Monitors extends ClientSDK {
  /**
   * Create monitor
   */
  async create(body: models.CreateMonitorDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.CreateMonitorResponse> {
    return createMonitor(this, body, idempotencyKey, options);
  }
  /**
   * Delete monitor
   */
  async delete(id: string, options?: RequestOptions): Promise<operations.DeleteMonitorResponse> {
    return deleteMonitor(this, id, options);
  }
  /**
   * Get monitor
   */
  async get(id: string, options?: RequestOptions): Promise<operations.GetMonitorResponse> {
    return getMonitor(this, id, options);
  }
  /**
   * List monitor events
   */
  async listEvents(id: string, query: Partial<operations.ListMonitorEventsRequest> = {}, options?: RequestOptions): Promise<operations.ListMonitorEventsResponse> {
    return listMonitorEvents(this, id, query, options);
  }
  /**
   * List monitors
   */
  async list(query: Partial<operations.ListMonitorsRequest> = {}, options?: RequestOptions): Promise<operations.ListMonitorsResponse> {
    return listMonitors(this, query, options);
  }
  /**
   * Run monitor now
   */
  async runNow(id: string, body?: models.RunNowBodyDto | undefined, options?: RequestOptions): Promise<operations.RunMonitorNowResponse> {
    return runMonitorNow(this, id, body, options);
  }
  /**
   * Update monitor
   */
  async update(id: string, body: models.UpdateMonitorDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.UpdateMonitorResponse> {
    return updateMonitor(this, id, body, idempotencyKey, options);
  }
}
