/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { monitorsCreate } from "../funcs/monitors-create.js";
import { monitorsDelete } from "../funcs/monitors-delete.js";
import { monitorsGet } from "../funcs/monitors-get.js";
import { monitorsListEvents } from "../funcs/monitors-list-events.js";
import { monitorsList } from "../funcs/monitors-list.js";
import { monitorsRunNow } from "../funcs/monitors-run-now.js";
import { monitorsUpdate } from "../funcs/monitors-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Monitors extends ClientSDK {
  /**
   * Create monitor
   *
   * @remarks
   * Create a recurring monitor that runs on a schedule and stores matching events for later review.
   */
  async create(
    request: models.CreateMonitorDto,
    options?: RequestOptions,
  ): Promise<models.MonitorResponseDto> {
    return unwrapAsync(monitorsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List monitors
   *
   * @remarks
   * List monitors for your organization.
   */
  async list(
    status?: any | undefined,
    limit?: number | undefined,
    cursor?: any | undefined,
    options?: RequestOptions,
  ): Promise<models.MonitorListResponseDto> {
    return unwrapAsync(monitorsList(
      this,
      status,
      limit,
      cursor,
      options,
    ));
  }

  /**
   * Update monitor
   *
   * @remarks
   * Update a monitor configuration, schedule, or status.
   */
  async update(
    body: models.UpdateMonitorDto,
    id: string,
    options?: RequestOptions,
  ): Promise<models.MonitorResponseDto> {
    return unwrapAsync(monitorsUpdate(
      this,
      body,
      id,
      options,
    ));
  }

  /**
   * Delete monitor
   *
   * @remarks
   * Delete a monitor by ID.
   */
  async delete(
    id: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(monitorsDelete(
      this,
      id,
      options,
    ));
  }

  /**
   * Get monitor
   *
   * @remarks
   * Retrieve a monitor by ID.
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<models.MonitorResponseDto> {
    return unwrapAsync(monitorsGet(
      this,
      id,
      options,
    ));
  }

  /**
   * Run monitor now
   *
   * @remarks
   * Trigger a monitor run immediately instead of waiting for its next scheduled time.
   */
  async runNow(
    id: string,
    body?: models.RunNowBodyDto | undefined,
    options?: RequestOptions,
  ): Promise<models.MonitorResponseDto> {
    return unwrapAsync(monitorsRunNow(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * List monitor events
   *
   * @remarks
   * List events found by a monitor.
   */
  async listEvents(
    id: string,
    since?: any | undefined,
    limit?: number | undefined,
    cursor?: any | undefined,
    options?: RequestOptions,
  ): Promise<models.MonitorEventListResponseDto> {
    return unwrapAsync(monitorsListEvents(
      this,
      id,
      since,
      limit,
      cursor,
      options,
    ));
  }
}
