/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { operationsGet } from "../funcs/operations-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export type OperationWaitTarget =
  | string
  | {
    id?: string | undefined;
    operationId?: string | undefined;
    pollUrl?: string | undefined;
  };

export type OperationWaitOptions = RequestOptions & {
  intervalMs?: number | undefined;
  timeoutMs?: number | undefined;
};

const DEFAULT_WAIT_INTERVAL_MS = 2000;
const DEFAULT_WAIT_TIMEOUT_MS = 300000;
const SUCCESS_STATUSES = new Set(["succeeded", "partial_success"]);
const FAILURE_STATUSES = new Set(["failed", "cancelled"]);

export class Operations extends ClientSDK {
  /**
   * Get operation
   *
   * @remarks
   * Check the status of a background operation and retrieve its result once it completes.
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<models.OperationResponseDto> {
    return unwrapAsync(operationsGet(
      this,
      id,
      options,
    ));
  }

  /**
   * Wait for an operation to complete.
   */
  async wait(
    operation: OperationWaitTarget,
    options: OperationWaitOptions = {},
  ): Promise<models.OperationResponseDto> {
    const operationId = getOperationId(operation);
    const startedAt = Date.now();
    const intervalMs = options.intervalMs ?? DEFAULT_WAIT_INTERVAL_MS;
    const timeoutMs = options.timeoutMs ?? DEFAULT_WAIT_TIMEOUT_MS;
    const { intervalMs: _intervalMs, timeoutMs: _timeoutMs, ...requestOptions } =
      options;
    void _intervalMs;
    void _timeoutMs;

    for (;;) {
      const result = await this.get(operationId, requestOptions);
      const status = String(result.status);

      if (SUCCESS_STATUSES.has(status)) {
        return result;
      }
      if (FAILURE_STATUSES.has(status)) {
        throw new Error(`Operation ${operationId} ended with status ${status}`);
      }
      if (Date.now() - startedAt >= timeoutMs) {
        throw new Error(`Timed out waiting for operation ${operationId}`);
      }

      await sleep(intervalMs);
    }
  }
}

function getOperationId(operation: OperationWaitTarget): string {
  if (typeof operation === "string") {
    return operation;
  }

  const id = operation.operationId ?? operation.id ?? idFromPollUrl(operation.pollUrl);
  if (!id) {
    throw new Error("Expected an operation id or pollUrl.");
  }

  return id;
}

function idFromPollUrl(pollUrl: string | undefined): string | undefined {
  if (!pollUrl) {
    return undefined;
  }

  const path = pollUrl.startsWith("http")
    ? new URL(pollUrl).pathname
    : pollUrl.split("?")[0] ?? pollUrl;
  const id = path.split("/").filter(Boolean).at(-1);
  return id ? decodeURIComponent(id) : undefined;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
