/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { operationsGet } from "../funcs/operations-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Operations extends ClientSDK {
  /**
   * Get operation
   *
   * @remarks
   * Check the status of a background operation and retrieve its result once it completes.
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<models.OperationResponseDto> {
    return unwrapAsync(operationsGet(
      this,
      id,
      options,
    ));
  }
}
