/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { peopleSearch } from "../funcs/people-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class People extends ClientSDK {
  /**
   * Search people
   *
   * @remarks
   * Async people discovery. Returns operationId; poll GET /api/operations/:id.
   */
  async search(
    body: models.PostPeopleSearchDto,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<models.EntitySearchAcceptedDto> {
    return unwrapAsync(peopleSearch(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }
}
