/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { searchPeople } from "../funcs/search-people.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class People extends ClientSDK {
  /**
   * Search people
   */
  async search(body: models.PostPeopleSearchDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.SearchPeopleResponse> {
    return searchPeople(this, body, idempotencyKey, options);
  }
}
