/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { InstagramScrapers } from "./instagram.js";
import { LinkedInScrapers } from "./linkedin.js";
import { TikTokScrapers } from "./tiktok.js";
import { WebScrapers } from "./web.js";

export class Scrapers extends ClientSDK {
  private _linkedin?: LinkedInScrapers;
  get linkedin(): LinkedInScrapers {
    return (this._linkedin ??= new LinkedInScrapers(this._options));
  }

  private _instagram?: InstagramScrapers;
  get instagram(): InstagramScrapers {
    return (this._instagram ??= new InstagramScrapers(this._options));
  }

  private _tiktok?: TikTokScrapers;
  get tiktok(): TikTokScrapers {
    return (this._tiktok ??= new TikTokScrapers(this._options));
  }

  private _web?: WebScrapers;
  get web(): WebScrapers {
    return (this._web ??= new WebScrapers(this._options));
  }
}
