/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Instagram } from "./instagram.js";
import { Linkedin } from "./linkedin.js";
import { Tiktok } from "./tiktok.js";
import { Web } from "./web.js";

export class Scrapers extends ClientSDK {
  private _linkedin?: Linkedin;
  get linkedin(): Linkedin {
    return (this._linkedin ??= new Linkedin(this._options));
  }

  private _instagram?: Instagram;
  get instagram(): Instagram {
    return (this._instagram ??= new Instagram(this._options));
  }

  private _tiktok?: Tiktok;
  get tiktok(): Tiktok {
    return (this._tiktok ??= new Tiktok(this._options));
  }

  private _web?: Web;
  get web(): Web {
    return (this._web ??= new Web(this._options));
  }
}
