/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { TheHogCore } from "../core.js";
import { Companies } from "./companies.js";
import { People } from "./people.js";
import { DeepResearch } from "./deep-research.js";
import { Enrichments } from "./enrichments.js";
import { Operations } from "./operations.js";
import { Monitors } from "./monitors.js";
import { Search } from "./search.js";
import { Scrapers } from "./scrapers.js";

export class TheHog extends TheHogCore {
  private _companies?: Companies;
  get companies(): Companies {
    return (this._companies ??= new Companies(this._options));
  }

  private _people?: People;
  get people(): People {
    return (this._people ??= new People(this._options));
  }

  private _deepResearch?: DeepResearch;
  get deepResearch(): DeepResearch {
    return (this._deepResearch ??= new DeepResearch(this._options));
  }

  private _enrichments?: Enrichments;
  get enrichments(): Enrichments {
    return (this._enrichments ??= new Enrichments(this._options));
  }

  private _operations?: Operations;
  get operations(): Operations {
    return (this._operations ??= new Operations(this._options));
  }

  private _monitors?: Monitors;
  get monitors(): Monitors {
    return (this._monitors ??= new Monitors(this._options));
  }

  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }

  private _scrapers?: Scrapers;
  get scrapers(): Scrapers {
    return (this._scrapers ??= new Scrapers(this._options));
  }

}