/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { getSearchResult } from "../funcs/get-search-result.js";
import { listSearches } from "../funcs/list-searches.js";
import { submitSearch } from "../funcs/submit-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class Search extends ClientSDK {
  /**
   * Get search result
   */
  async getResult(id: string, options?: RequestOptions): Promise<operations.GetSearchResultResponse> {
    return getSearchResult(this, id, options);
  }
  /**
   * List searches
   */
  async list(query: Partial<operations.ListSearchesRequest> = {}, options?: RequestOptions): Promise<operations.ListSearchesResponse> {
    return listSearches(this, query, options);
  }
  /**
   * Submit search
   */
  async submit(body: models.PostSearchDto, sync?: boolean | undefined, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.SubmitSearchResponse> {
    return submitSearch(this, body, sync, idempotencyKey, options);
  }
}
