/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchGetResult } from "../funcs/search-get-result.js";
import { searchList } from "../funcs/search-list.js";
import { searchSubmit } from "../funcs/search-submit.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Submit search
   *
   * @remarks
   * Run a search across supported web and social sources. The default response returns an operation to poll; add sync=true only when you want to wait briefly for an immediate result.
   */
  async submit(
    body: models.PostSearchDto,
    sync?: boolean | undefined,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.SubmitSearchResponse> {
    return unwrapAsync(searchSubmit(
      this,
      body,
      sync,
      idempotencyKey,
      options,
    ));
  }

  /**
   * List searches
   *
   * @remarks
   * List previous searches for your organization.
   */
  async list(
    type?: any | undefined,
    limit?: number | undefined,
    cursor?: any | undefined,
    options?: RequestOptions,
  ): Promise<models.SearchListResponseDto> {
    return unwrapAsync(searchList(
      this,
      type,
      limit,
      cursor,
      options,
    ));
  }

  /**
   * Get search result
   *
   * @remarks
   * Check the status of a search and retrieve the result once it completes.
   */
  async getResult(
    id: string,
    options?: RequestOptions,
  ): Promise<models.SearchResultDto> {
    return unwrapAsync(searchGetResult(
      this,
      id,
      options,
    ));
  }
}
