/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scrapersTiktokGetProfile } from "../funcs/scrapers-tiktok-get-profile.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tiktok extends ClientSDK {
  /**
   * Get TikTok profile
   *
   * @remarks
   * Fetch public profile details and recent videos for a TikTok username.
   */
  async getProfile(
    request: models.PlatformTikTokUsernameDto,
    options?: RequestOptions,
  ): Promise<operations.GetTikTokProfileResponseBody> {
    return unwrapAsync(scrapersTiktokGetProfile(
      this,
      request,
      options,
    ));
  }
}
