/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { getTikTokProfile } from "../funcs/get-tik-tok-profile.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class TikTokScrapers extends ClientSDK {
  /**
   * Get TikTok profile
   */
  async getProfile(body: models.PlatformTikTokUsernameDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.GetTikTokProfileResponse> {
    return getTikTokProfile(this, body, idempotencyKey, options);
  }
}
