/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import { batchScrapeWebPages } from "../funcs/batch-scrape-web-pages.js";
import { crawlWebSite } from "../funcs/crawl-web-site.js";
import { scrapeWebPage } from "../funcs/scrape-web-page.js";
import { searchWeb } from "../funcs/search-web.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
export class WebScrapers extends ClientSDK {
  /**
   * Batch scrape web pages
   */
  async batchScrape(body: models.PlatformWebScrapeBatchDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.BatchScrapeWebPagesResponse> {
    return batchScrapeWebPages(this, body, idempotencyKey, options);
  }
  /**
   * Crawl website
   */
  async crawl(body: models.PlatformWebCrawlDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.CrawlWebSiteResponse> {
    return crawlWebSite(this, body, idempotencyKey, options);
  }
  /**
   * Scrape web page
   */
  async scrape(body: models.PlatformWebScrapeDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.ScrapeWebPageResponse> {
    return scrapeWebPage(this, body, idempotencyKey, options);
  }
  /**
   * Search web
   */
  async search(body: models.PlatformWebSearchDto, idempotencyKey?: string | undefined, options?: RequestOptions): Promise<operations.SearchWebResponse> {
    return searchWeb(this, body, idempotencyKey, options);
  }
}
