/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scrapersWebCrawl } from "../funcs/scrapers-web-crawl.js";
import { scrapersWebScrape } from "../funcs/scrapers-web-scrape.js";
import { scrapersWebSearch } from "../funcs/scrapers-web-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Web extends ClientSDK {
  /**
   * Search web
   *
   * @remarks
   * Search the web and return normalized results in a stable response shape.
   */
  async search(
    request: models.PlatformWebSearchDto,
    options?: RequestOptions,
  ): Promise<operations.SearchWebResponseBody> {
    return unwrapAsync(scrapersWebSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Crawl website
   *
   * @remarks
   * Crawl a website and return normalized page content in a stable response shape.
   */
  async crawl(
    request: models.PlatformWebCrawlDto,
    options?: RequestOptions,
  ): Promise<operations.CrawlWebSiteResponseBody> {
    return unwrapAsync(scrapersWebCrawl(
      this,
      request,
      options,
    ));
  }

  /**
   * Scrape web page
   *
   * @remarks
   * Fetch a web page and return its readable text content in a stable response shape.
   */
  async scrape(
    request: models.PlatformWebScrapeDto,
    options?: RequestOptions,
  ): Promise<operations.ScrapeWebPageResponseBody> {
    return unwrapAsync(scrapersWebScrape(
      this,
      request,
      options,
    ));
  }
}
