/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type BatchScrapeWebPagesRequest = {
  body: models.PlatformWebScrapeBatchDto;
  idempotencyKey?: string | undefined;
};
export const BatchScrapeWebPagesRequest$outboundSchema = z.object({
  body: models.PlatformWebScrapeBatchDto$outboundSchema,
  idempotencyKey: z.optional(z.string()),
});
export type BatchScrapeWebPagesResponse = models.BatchScrapeWebPagesResponse;
export const BatchScrapeWebPagesResponse$inboundSchemas = {
  202: models.BatchScrapeWebPagesResponse$inboundSchema,
};
