/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type CrawlWebSiteRequest = {
  body: models.PlatformWebCrawlDto;
  idempotencyKey?: string | undefined;
};
export const CrawlWebSiteRequest$outboundSchema = z.object({
  body: models.PlatformWebCrawlDto$outboundSchema,
  idempotencyKey: z.optional(z.string()),
});
export type CrawlWebSiteResponse = models.CrawlWebSiteResponse;
export const CrawlWebSiteResponse$inboundSchemas = {
  202: models.CrawlWebSiteResponse$inboundSchema,
};
