/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Successful response.
 */
export type CrawlWebSiteResponseBody = {
  data: models.WebCrawlResponseDto;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const CrawlWebSiteResponseBody$inboundSchema: z.ZodMiniType<
  CrawlWebSiteResponseBody,
  unknown
> = z.object({
  data: models.WebCrawlResponseDto$inboundSchema,
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function crawlWebSiteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CrawlWebSiteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CrawlWebSiteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CrawlWebSiteResponseBody' from JSON`,
  );
}
