/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type CreateMonitorRequest = {
  body: models.CreateMonitorDto;
};
export const CreateMonitorRequest$outboundSchema = z.object({
  body: models.CreateMonitorDto$outboundSchema,
});
export type CreateMonitorResponse = models.MonitorResponseDto;
export const CreateMonitorResponse$inboundSchemas = {
  201: models.MonitorResponseDto$inboundSchema,
};
