/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
export type DeleteMonitorRequest = {
  id: string;
};
export const DeleteMonitorRequest$outboundSchema = z.object({
  id: z.string(),
});
export type DeleteMonitorResponse = void;
export const DeleteMonitorResponse$inboundSchemas = {
};
