/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteMonitorRequest = {
  /**
   * Monitor ID.
   */
  id: string;
};

/** @internal */
export type DeleteMonitorRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteMonitorRequest$outboundSchema: z.ZodMiniType<
  DeleteMonitorRequest$Outbound,
  DeleteMonitorRequest
> = z.object({
  id: z.string(),
});

export function deleteMonitorRequestToJSON(
  deleteMonitorRequest: DeleteMonitorRequest,
): string {
  return JSON.stringify(
    DeleteMonitorRequest$outboundSchema.parse(deleteMonitorRequest),
  );
}
