/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type FindLinkedInCompaniesRequest = {
  body: models.PlatformLinkedInFinderDto;
};
export const FindLinkedInCompaniesRequest$outboundSchema = z.object({
  body: models.PlatformLinkedInFinderDto$outboundSchema,
});
export type FindLinkedInCompaniesResponse = models.FindLinkedInCompaniesResponse;
export const FindLinkedInCompaniesResponse$inboundSchemas = {
  200: models.FindLinkedInCompaniesResponse$inboundSchema,
};
