/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * LinkedIn company URLs found from domains or URLs.
 */
export type FindLinkedInCompaniesResponseBody = {
  data: Array<models.LinkedInFinderResponseDto>;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const FindLinkedInCompaniesResponseBody$inboundSchema: z.ZodMiniType<
  FindLinkedInCompaniesResponseBody,
  unknown
> = z.object({
  data: z.array(models.LinkedInFinderResponseDto$inboundSchema),
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function findLinkedInCompaniesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInCompaniesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindLinkedInCompaniesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInCompaniesResponseBody' from JSON`,
  );
}
