/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetInstagramPostData = {
  shortcode: string;
  postUrl?: string | null | undefined;
  postType?: string | null | undefined;
  caption?: string | null | undefined;
  hashtags?: Array<string> | null | undefined;
  mentions?: Array<string> | null | undefined;
  likesCount?: number | null | undefined;
  commentsCount?: number | null | undefined;
  videoViewsCount?: number | null | undefined;
  displayUrl?: string | null | undefined;
  dimensionsHeight?: number | null | undefined;
  dimensionsWidth?: number | null | undefined;
  isSponsored?: boolean | null | undefined;
  locationName?: string | null | undefined;
  locationId?: string | null | undefined;
  postedAt?: string | null | undefined;
  authorUsername?: string | null | undefined;
  ownerId?: string | null | undefined;
};

/**
 * Instagram post details.
 */
export type GetInstagramPostResponseBody = {
  data: GetInstagramPostData | null;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const GetInstagramPostData$inboundSchema: z.ZodMiniType<
  GetInstagramPostData,
  unknown
> = z.pipe(
  z.object({
    shortcode: types.string(),
    post_url: z.optional(z.nullable(types.string())),
    post_type: z.optional(z.nullable(types.string())),
    caption: z.optional(z.nullable(types.string())),
    hashtags: z.optional(z.nullable(z.array(types.string()))),
    mentions: z.optional(z.nullable(z.array(types.string()))),
    likes_count: z.optional(z.nullable(types.number())),
    comments_count: z.optional(z.nullable(types.number())),
    video_views_count: z.optional(z.nullable(types.number())),
    display_url: z.optional(z.nullable(types.string())),
    dimensions_height: z.optional(z.nullable(types.number())),
    dimensions_width: z.optional(z.nullable(types.number())),
    is_sponsored: z.optional(z.nullable(types.boolean())),
    location_name: z.optional(z.nullable(types.string())),
    location_id: z.optional(z.nullable(types.string())),
    posted_at: z.optional(z.nullable(types.string())),
    author_username: z.optional(z.nullable(types.string())),
    owner_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "post_url": "postUrl",
      "post_type": "postType",
      "likes_count": "likesCount",
      "comments_count": "commentsCount",
      "video_views_count": "videoViewsCount",
      "display_url": "displayUrl",
      "dimensions_height": "dimensionsHeight",
      "dimensions_width": "dimensionsWidth",
      "is_sponsored": "isSponsored",
      "location_name": "locationName",
      "location_id": "locationId",
      "posted_at": "postedAt",
      "author_username": "authorUsername",
      "owner_id": "ownerId",
    });
  }),
);

export function getInstagramPostDataFromJSON(
  jsonString: string,
): SafeParseResult<GetInstagramPostData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInstagramPostData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInstagramPostData' from JSON`,
  );
}

/** @internal */
export const GetInstagramPostResponseBody$inboundSchema: z.ZodMiniType<
  GetInstagramPostResponseBody,
  unknown
> = z.object({
  data: types.nullable(z.lazy(() => GetInstagramPostData$inboundSchema)),
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function getInstagramPostResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetInstagramPostResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInstagramPostResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInstagramPostResponseBody' from JSON`,
  );
}
