/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type GetLinkedInProfileRequest = {
  body: models.PlatformLinkedInProfileDto;
};
export const GetLinkedInProfileRequest$outboundSchema = z.object({
  body: models.PlatformLinkedInProfileDto$outboundSchema,
});
export type GetLinkedInProfileResponse = models.GetLinkedInProfileResponse;
export const GetLinkedInProfileResponse$inboundSchemas = {
  200: models.GetLinkedInProfileResponse$inboundSchema,
};
