/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type GetInstagramProfileRequest = {
  body: models.PlatformInstagramUsernameDto;
};
export const GetInstagramProfileRequest$outboundSchema = z.object({
  body: models.PlatformInstagramUsernameDto$outboundSchema,
});
export type GetInstagramProfileResponse = models.GetInstagramProfileResponse;
export const GetInstagramProfileResponse$inboundSchemas = {
  200: models.GetInstagramProfileResponse$inboundSchema,
};
