/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type GetTikTokProfileRequest = {
  body: models.PlatformTikTokUsernameDto;
};
export const GetTikTokProfileRequest$outboundSchema = z.object({
  body: models.PlatformTikTokUsernameDto$outboundSchema,
});
export type GetTikTokProfileResponse = models.GetTikTokProfileResponse;
export const GetTikTokProfileResponse$inboundSchemas = {
  200: models.GetTikTokProfileResponse$inboundSchema,
};
