/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetOperationRequest = {
  /**
   * Operation ID.
   */
  id: string;
};

/** @internal */
export type GetOperationRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetOperationRequest$outboundSchema: z.ZodMiniType<
  GetOperationRequest$Outbound,
  GetOperationRequest
> = z.object({
  id: z.string(),
});

export function getOperationRequestToJSON(
  getOperationRequest: GetOperationRequest,
): string {
  return JSON.stringify(
    GetOperationRequest$outboundSchema.parse(getOperationRequest),
  );
}
