/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type GetOperationRequest = {
  id: string;
};
export const GetOperationRequest$outboundSchema = z.object({
  id: z.string(),
});
export type GetOperationResponse = models.OperationResponseDto;
export const GetOperationResponse$inboundSchemas = {
  200: models.OperationResponseDto$inboundSchema,
};
