/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetLinkedInCompanyData = {
  identifier: string;
  name?: string | null | undefined;
  description?: string | null | undefined;
  website?: string | null | undefined;
  industry?: string | null | undefined;
  companySize?: string | null | undefined;
  headquarters?: string | null | undefined;
  founded?: number | null | undefined;
  specialties?: Array<string> | null | undefined;
  logoUrl?: string | null | undefined;
  followerCount?: number | null | undefined;
  employeeCount?: number | null | undefined;
  linkedinUrl?: string | null | undefined;
};

/**
 * LinkedIn company data.
 */
export type GetLinkedInCompanyResponseBody = {
  data: GetLinkedInCompanyData | null;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const GetLinkedInCompanyData$inboundSchema: z.ZodMiniType<
  GetLinkedInCompanyData,
  unknown
> = z.pipe(
  z.object({
    identifier: types.string(),
    name: z.optional(z.nullable(types.string())),
    description: z.optional(z.nullable(types.string())),
    website: z.optional(z.nullable(types.string())),
    industry: z.optional(z.nullable(types.string())),
    company_size: z.optional(z.nullable(types.string())),
    headquarters: z.optional(z.nullable(types.string())),
    founded: z.optional(z.nullable(types.number())),
    specialties: z.optional(z.nullable(z.array(types.string()))),
    logo_url: z.optional(z.nullable(types.string())),
    follower_count: z.optional(z.nullable(types.number())),
    employee_count: z.optional(z.nullable(types.number())),
    linkedin_url: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "company_size": "companySize",
      "logo_url": "logoUrl",
      "follower_count": "followerCount",
      "employee_count": "employeeCount",
      "linkedin_url": "linkedinUrl",
    });
  }),
);

export function getLinkedInCompanyDataFromJSON(
  jsonString: string,
): SafeParseResult<GetLinkedInCompanyData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLinkedInCompanyData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLinkedInCompanyData' from JSON`,
  );
}

/** @internal */
export const GetLinkedInCompanyResponseBody$inboundSchema: z.ZodMiniType<
  GetLinkedInCompanyResponseBody,
  unknown
> = z.object({
  data: types.nullable(z.lazy(() => GetLinkedInCompanyData$inboundSchema)),
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function getLinkedInCompanyResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetLinkedInCompanyResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLinkedInCompanyResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLinkedInCompanyResponseBody' from JSON`,
  );
}
