/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetMonitorRequest = {
  /**
   * Monitor ID.
   */
  id: string;
};

/** @internal */
export type GetMonitorRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetMonitorRequest$outboundSchema: z.ZodMiniType<
  GetMonitorRequest$Outbound,
  GetMonitorRequest
> = z.object({
  id: z.string(),
});

export function getMonitorRequestToJSON(
  getMonitorRequest: GetMonitorRequest,
): string {
  return JSON.stringify(
    GetMonitorRequest$outboundSchema.parse(getMonitorRequest),
  );
}
