/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type Location = {
  country?: string | null | undefined;
  city?: string | null | undefined;
  full?: string | null | undefined;
};

export type Data = {
  username: string;
  fullName?: string | null | undefined;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;
  headline?: string | null | undefined;
  about?: string | null | undefined;
  profilePictureUrl?: string | null | undefined;
  location?: Location | null | undefined;
  followerCount?: number | null | undefined;
  connectionCount?: number | null | undefined;
  currentCompany?: string | null | undefined;
  currentCompanyUrl?: string | null | undefined;
  experience?: { [k: string]: any } | undefined;
  education?: { [k: string]: any } | undefined;
  certifications?: { [k: string]: any } | undefined;
};

/**
 * LinkedIn profile data.
 */
export type GetLinkedInProfileResponseBody = {
  data: Data | null;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const Location$inboundSchema: z.ZodMiniType<Location, unknown> = z
  .object({
    country: z.optional(z.nullable(types.string())),
    city: z.optional(z.nullable(types.string())),
    full: z.optional(z.nullable(types.string())),
  });

export function locationFromJSON(
  jsonString: string,
): SafeParseResult<Location, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Location$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Location' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = z.pipe(
  z.object({
    username: types.string(),
    full_name: z.optional(z.nullable(types.string())),
    first_name: z.optional(z.nullable(types.string())),
    last_name: z.optional(z.nullable(types.string())),
    headline: z.optional(z.nullable(types.string())),
    about: z.optional(z.nullable(types.string())),
    profile_picture_url: z.optional(z.nullable(types.string())),
    location: z.optional(z.nullable(z.lazy(() => Location$inboundSchema))),
    follower_count: z.optional(z.nullable(types.number())),
    connection_count: z.optional(z.nullable(types.number())),
    current_company: z.optional(z.nullable(types.string())),
    current_company_url: z.optional(z.nullable(types.string())),
    experience: types.optional(z.record(z.string(), z.any())),
    education: types.optional(z.record(z.string(), z.any())),
    certifications: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "full_name": "fullName",
      "first_name": "firstName",
      "last_name": "lastName",
      "profile_picture_url": "profilePictureUrl",
      "follower_count": "followerCount",
      "connection_count": "connectionCount",
      "current_company": "currentCompany",
      "current_company_url": "currentCompanyUrl",
    });
  }),
);

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const GetLinkedInProfileResponseBody$inboundSchema: z.ZodMiniType<
  GetLinkedInProfileResponseBody,
  unknown
> = z.object({
  data: types.nullable(z.lazy(() => Data$inboundSchema)),
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function getLinkedInProfileResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetLinkedInProfileResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLinkedInProfileResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLinkedInProfileResponseBody' from JSON`,
  );
}
