/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type GetMonitorRequest = {
  id: string;
};
export const GetMonitorRequest$outboundSchema = z.object({
  id: z.string(),
});
export type GetMonitorResponse = models.MonitorResponseDto;
export const GetMonitorResponse$inboundSchemas = {
  200: models.MonitorResponseDto$inboundSchema,
};
