/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * TikTok profile and video data.
 */
export type GetTikTokProfileResponseBody = {
  data: models.TikTokProfileScrapeResponseDto;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const GetTikTokProfileResponseBody$inboundSchema: z.ZodMiniType<
  GetTikTokProfileResponseBody,
  unknown
> = z.object({
  data: models.TikTokProfileScrapeResponseDto$inboundSchema,
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function getTikTokProfileResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetTikTokProfileResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTikTokProfileResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTikTokProfileResponseBody' from JSON`,
  );
}
