/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type GetInstagramPostRequest = {
  body: models.PlatformInstagramPostDetailsDto;
};
export const GetInstagramPostRequest$outboundSchema = z.object({
  body: models.PlatformInstagramPostDetailsDto$outboundSchema,
});
export type GetInstagramPostResponse = models.GetInstagramPostResponse;
export const GetInstagramPostResponse$inboundSchemas = {
  200: models.GetInstagramPostResponse$inboundSchema,
};
