/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetEnrichmentRequest = {
  /**
   * Enrichment operation ID.
   */
  id: string;
};

/** @internal */
export type GetEnrichmentRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEnrichmentRequest$outboundSchema: z.ZodMiniType<
  GetEnrichmentRequest$Outbound,
  GetEnrichmentRequest
> = z.object({
  id: z.string(),
});

export function getEnrichmentRequestToJSON(
  getEnrichmentRequest: GetEnrichmentRequest,
): string {
  return JSON.stringify(
    GetEnrichmentRequest$outboundSchema.parse(getEnrichmentRequest),
  );
}
