/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type GetLinkedInCompanyRequest = {
  body: models.PlatformLinkedInCompanyDto;
};
export const GetLinkedInCompanyRequest$outboundSchema = z.object({
  body: models.PlatformLinkedInCompanyDto$outboundSchema,
});
export type GetLinkedInCompanyResponse = models.GetLinkedInCompanyResponse;
export const GetLinkedInCompanyResponse$inboundSchemas = {
  200: models.GetLinkedInCompanyResponse$inboundSchema,
};
