/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type GetEnrichmentRequest = {
  id: string;
};
export const GetEnrichmentRequest$outboundSchema = z.object({
  id: z.string(),
});
export type GetEnrichmentResponse = models.OperationResponseDto;
export const GetEnrichmentResponse$inboundSchemas = {
  200: models.OperationResponseDto$inboundSchema,
};
