/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListLinkedInProfilePostsRequest = {
  body: models.PlatformLinkedInProfilePostsDto;
};
export const ListLinkedInProfilePostsRequest$outboundSchema = z.object({
  body: models.PlatformLinkedInProfilePostsDto$outboundSchema,
});
export type ListLinkedInProfilePostsResponse = models.ListLinkedInProfilePostsResponse;
export const ListLinkedInProfilePostsResponse$inboundSchemas = {
  200: models.ListLinkedInProfilePostsResponse$inboundSchema,
};
