/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListInstagramPostCommentsRequest = {
  body: models.PlatformInstagramPostCommentsDto;
};
export const ListInstagramPostCommentsRequest$outboundSchema = z.object({
  body: models.PlatformInstagramPostCommentsDto$outboundSchema,
});
export type ListInstagramPostCommentsResponse = models.ListInstagramPostCommentsResponse;
export const ListInstagramPostCommentsResponse$inboundSchemas = {
  200: models.ListInstagramPostCommentsResponse$inboundSchema,
};
