/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Instagram posts.
 */
export type ListInstagramPostsResponseBody = {
  data: Array<models.InstagramPostResponseDto>;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListInstagramPostsResponseBody$inboundSchema: z.ZodMiniType<
  ListInstagramPostsResponseBody,
  unknown
> = z.object({
  data: z.array(models.InstagramPostResponseDto$inboundSchema),
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function listInstagramPostsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListInstagramPostsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListInstagramPostsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInstagramPostsResponseBody' from JSON`,
  );
}
