/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * LinkedIn profile posts.
 */
export type ListLinkedInProfilePostsResponseBody = {
  data: models.LinkedInProfilePostsResponseDto;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListLinkedInProfilePostsResponseBody$inboundSchema: z.ZodMiniType<
  ListLinkedInProfilePostsResponseBody,
  unknown
> = z.object({
  data: models.LinkedInProfilePostsResponseDto$inboundSchema,
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function listLinkedInProfilePostsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInProfilePostsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInProfilePostsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInProfilePostsResponseBody' from JSON`,
  );
}
