/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListMonitorsRequest = {
  status?: unknown | undefined;
  limit?: number | undefined;
  cursor?: unknown | undefined;
};
export const ListMonitorsRequest$outboundSchema = z.object({
  status: z.optional(z.unknown()),
  limit: z.optional(z.number()),
  cursor: z.optional(z.unknown()),
});
export type ListMonitorsResponse = models.MonitorListResponseDto;
export const ListMonitorsResponse$inboundSchemas = {
  200: models.MonitorListResponseDto$inboundSchema,
};
