/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Instagram following.
 */
export type ListInstagramFollowingResponseBody = {
  data: models.InstagramFollowScrapeResponseDto;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListInstagramFollowingResponseBody$inboundSchema: z.ZodMiniType<
  ListInstagramFollowingResponseBody,
  unknown
> = z.object({
  data: models.InstagramFollowScrapeResponseDto$inboundSchema,
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function listInstagramFollowingResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListInstagramFollowingResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListInstagramFollowingResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInstagramFollowingResponseBody' from JSON`,
  );
}
