/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Instagram post comments.
 */
export type ListInstagramPostCommentsResponseBody = {
  data: Array<models.InstagramCommentResponseDto>;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListInstagramPostCommentsResponseBody$inboundSchema: z.ZodMiniType<
  ListInstagramPostCommentsResponseBody,
  unknown
> = z.object({
  data: z.array(models.InstagramCommentResponseDto$inboundSchema),
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function listInstagramPostCommentsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListInstagramPostCommentsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListInstagramPostCommentsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInstagramPostCommentsResponseBody' from JSON`,
  );
}
