/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListMonitorEventsRequest = {
  id: string;
  since?: unknown | undefined;
  limit?: number | undefined;
  cursor?: unknown | undefined;
};
export const ListMonitorEventsRequest$outboundSchema = z.object({
  id: z.string(),
  since: z.optional(z.unknown()),
  limit: z.optional(z.number()),
  cursor: z.optional(z.unknown()),
});
export type ListMonitorEventsResponse = models.MonitorEventListResponseDto;
export const ListMonitorEventsResponse$inboundSchemas = {
  200: models.MonitorEventListResponseDto$inboundSchema,
};
