/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * LinkedIn profile comments.
 */
export type ListLinkedInProfileCommentsResponseBody = {
  data: Array<models.LinkedInProfileCommentResponseDto>;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListLinkedInProfileCommentsResponseBody$inboundSchema:
  z.ZodMiniType<ListLinkedInProfileCommentsResponseBody, unknown> = z.object({
    data: z.array(models.LinkedInProfileCommentResponseDto$inboundSchema),
    meta: models.PublicResponseMetaDto$inboundSchema,
  });

export function listLinkedInProfileCommentsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ListLinkedInProfileCommentsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInProfileCommentsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListLinkedInProfileCommentsResponseBody' from JSON`,
  );
}
