/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Instagram followers.
 */
export type ListInstagramFollowersResponseBody = {
  data: models.InstagramFollowScrapeResponseDto;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListInstagramFollowersResponseBody$inboundSchema: z.ZodMiniType<
  ListInstagramFollowersResponseBody,
  unknown
> = z.object({
  data: models.InstagramFollowScrapeResponseDto$inboundSchema,
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function listInstagramFollowersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListInstagramFollowersResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListInstagramFollowersResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInstagramFollowersResponseBody' from JSON`,
  );
}
