/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * LinkedIn company posts.
 */
export type ListLinkedInCompanyPostsResponseBody = {
  data: models.LinkedInCompanyPostsResponseDto;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListLinkedInCompanyPostsResponseBody$inboundSchema: z.ZodMiniType<
  ListLinkedInCompanyPostsResponseBody,
  unknown
> = z.object({
  data: models.LinkedInCompanyPostsResponseDto$inboundSchema,
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function listLinkedInCompanyPostsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInCompanyPostsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInCompanyPostsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInCompanyPostsResponseBody' from JSON`,
  );
}
