/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListInstagramFollowingRequest = {
  body: models.PlatformInstagramFollowingDto;
};
export const ListInstagramFollowingRequest$outboundSchema = z.object({
  body: models.PlatformInstagramFollowingDto$outboundSchema,
});
export type ListInstagramFollowingResponse = models.ListInstagramFollowingResponse;
export const ListInstagramFollowingResponse$inboundSchemas = {
  200: models.ListInstagramFollowingResponse$inboundSchema,
};
