/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListSearchesRequest = {
  /**
   * Filter by search type
   */
  type?: any | undefined;
  /**
   * Page size (max 200)
   */
  limit?: number | undefined;
  /**
   * Pagination cursor (created_at ISO)
   */
  cursor?: any | undefined;
};

/** @internal */
export type ListSearchesRequest$Outbound = {
  type?: any | undefined;
  limit?: number | undefined;
  cursor?: any | undefined;
};

/** @internal */
export const ListSearchesRequest$outboundSchema: z.ZodMiniType<
  ListSearchesRequest$Outbound,
  ListSearchesRequest
> = z.object({
  type: z.optional(z.any()),
  limit: z.optional(z.number()),
  cursor: z.optional(z.any()),
});

export function listSearchesRequestToJSON(
  listSearchesRequest: ListSearchesRequest,
): string {
  return JSON.stringify(
    ListSearchesRequest$outboundSchema.parse(listSearchesRequest),
  );
}
