/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListMonitorEventsRequest = {
  /**
   * ISO timestamp — only return events detected after this time
   */
  since?: any | undefined;
  limit?: number | undefined;
  cursor?: any | undefined;
  /**
   * Monitor ID.
   */
  id: string;
};

/** @internal */
export type ListMonitorEventsRequest$Outbound = {
  since?: any | undefined;
  limit?: number | undefined;
  cursor?: any | undefined;
  id: string;
};

/** @internal */
export const ListMonitorEventsRequest$outboundSchema: z.ZodMiniType<
  ListMonitorEventsRequest$Outbound,
  ListMonitorEventsRequest
> = z.object({
  since: z.optional(z.any()),
  limit: z.optional(z.number()),
  cursor: z.optional(z.any()),
  id: z.string(),
});

export function listMonitorEventsRequestToJSON(
  listMonitorEventsRequest: ListMonitorEventsRequest,
): string {
  return JSON.stringify(
    ListMonitorEventsRequest$outboundSchema.parse(listMonitorEventsRequest),
  );
}
