/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * LinkedIn post comments.
 */
export type ListLinkedInPostCommentsResponseBody = {
  data: Array<models.LinkedInPostCommentResponseDto>;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListLinkedInPostCommentsResponseBody$inboundSchema: z.ZodMiniType<
  ListLinkedInPostCommentsResponseBody,
  unknown
> = z.object({
  data: z.array(models.LinkedInPostCommentResponseDto$inboundSchema),
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function listLinkedInPostCommentsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInPostCommentsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInPostCommentsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInPostCommentsResponseBody' from JSON`,
  );
}
