/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListSearchesRequest = {
  type?: unknown | undefined;
  limit?: number | undefined;
  cursor?: unknown | undefined;
};
export const ListSearchesRequest$outboundSchema = z.object({
  type: z.optional(z.unknown()),
  limit: z.optional(z.number()),
  cursor: z.optional(z.unknown()),
});
export type ListSearchesResponse = models.SearchListResponseDto;
export const ListSearchesResponse$inboundSchemas = {
  200: models.SearchListResponseDto$inboundSchema,
};
