/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListLinkedInProfileReactionsRequest = {
  body: models.PlatformLinkedInProfileActivityDto;
};
export const ListLinkedInProfileReactionsRequest$outboundSchema = z.object({
  body: models.PlatformLinkedInProfileActivityDto$outboundSchema,
});
export type ListLinkedInProfileReactionsResponse = models.ListLinkedInProfileReactionsResponse;
export const ListLinkedInProfileReactionsResponse$inboundSchemas = {
  200: models.ListLinkedInProfileReactionsResponse$inboundSchema,
};
