/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * LinkedIn profile reactions.
 */
export type ListLinkedInProfileReactionsResponseBody = {
  data: Array<models.LinkedInProfileReactionResponseDto>;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListLinkedInProfileReactionsResponseBody$inboundSchema:
  z.ZodMiniType<ListLinkedInProfileReactionsResponseBody, unknown> = z.object({
    data: z.array(models.LinkedInProfileReactionResponseDto$inboundSchema),
    meta: models.PublicResponseMetaDto$inboundSchema,
  });

export function listLinkedInProfileReactionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ListLinkedInProfileReactionsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInProfileReactionsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListLinkedInProfileReactionsResponseBody' from JSON`,
  );
}
