/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListLinkedInCompanyPostsRequest = {
  body: models.PlatformLinkedInCompanyPostsDto;
};
export const ListLinkedInCompanyPostsRequest$outboundSchema = z.object({
  body: models.PlatformLinkedInCompanyPostsDto$outboundSchema,
});
export type ListLinkedInCompanyPostsResponse = models.ListLinkedInCompanyPostsResponse;
export const ListLinkedInCompanyPostsResponse$inboundSchemas = {
  200: models.ListLinkedInCompanyPostsResponse$inboundSchema,
};
