/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListLinkedInPostCommentsRequest = {
  body: models.PlatformLinkedInPostUrlsDto;
};
export const ListLinkedInPostCommentsRequest$outboundSchema = z.object({
  body: models.PlatformLinkedInPostUrlsDto$outboundSchema,
});
export type ListLinkedInPostCommentsResponse = models.ListLinkedInPostCommentsResponse;
export const ListLinkedInPostCommentsResponse$inboundSchemas = {
  200: models.ListLinkedInPostCommentsResponse$inboundSchema,
};
