/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListMonitorsRequest = {
  status?: any | undefined;
  limit?: number | undefined;
  cursor?: any | undefined;
};

/** @internal */
export type ListMonitorsRequest$Outbound = {
  status?: any | undefined;
  limit?: number | undefined;
  cursor?: any | undefined;
};

/** @internal */
export const ListMonitorsRequest$outboundSchema: z.ZodMiniType<
  ListMonitorsRequest$Outbound,
  ListMonitorsRequest
> = z.object({
  status: z.optional(z.any()),
  limit: z.optional(z.number()),
  cursor: z.optional(z.any()),
});

export function listMonitorsRequestToJSON(
  listMonitorsRequest: ListMonitorsRequest,
): string {
  return JSON.stringify(
    ListMonitorsRequest$outboundSchema.parse(listMonitorsRequest),
  );
}
