/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListInstagramFollowersRequest = {
  body: models.PlatformInstagramFollowersDto;
};
export const ListInstagramFollowersRequest$outboundSchema = z.object({
  body: models.PlatformInstagramFollowersDto$outboundSchema,
});
export type ListInstagramFollowersResponse = models.ListInstagramFollowersResponse;
export const ListInstagramFollowersResponse$inboundSchemas = {
  200: models.ListInstagramFollowersResponse$inboundSchema,
};
