/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ListInstagramPostsRequest = {
  body: models.PlatformInstagramUsernameDto;
};
export const ListInstagramPostsRequest$outboundSchema = z.object({
  body: models.PlatformInstagramUsernameDto$outboundSchema,
});
export type ListInstagramPostsResponse = models.ListInstagramPostsResponse;
export const ListInstagramPostsResponse$inboundSchemas = {
  200: models.ListInstagramPostsResponse$inboundSchema,
};
