/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * LinkedIn post reactions.
 */
export type ListLinkedInPostReactionsResponseBody = {
  data: Array<models.LinkedInPostReactionResponseDto>;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ListLinkedInPostReactionsResponseBody$inboundSchema: z.ZodMiniType<
  ListLinkedInPostReactionsResponseBody,
  unknown
> = z.object({
  data: z.array(models.LinkedInPostReactionResponseDto$inboundSchema),
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function listLinkedInPostReactionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInPostReactionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInPostReactionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInPostReactionsResponseBody' from JSON`,
  );
}
