/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type RunMonitorNowRequest = {
  /**
   * Monitor ID.
   */
  id: string;
  body?: models.RunNowBodyDto | undefined;
};

/** @internal */
export type RunMonitorNowRequest$Outbound = {
  id: string;
  body?: models.RunNowBodyDto$Outbound | undefined;
};

/** @internal */
export const RunMonitorNowRequest$outboundSchema: z.ZodMiniType<
  RunMonitorNowRequest$Outbound,
  RunMonitorNowRequest
> = z.object({
  id: z.string(),
  body: z.optional(models.RunNowBodyDto$outboundSchema),
});

export function runMonitorNowRequestToJSON(
  runMonitorNowRequest: RunMonitorNowRequest,
): string {
  return JSON.stringify(
    RunMonitorNowRequest$outboundSchema.parse(runMonitorNowRequest),
  );
}
