/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type RunMonitorNowRequest = {
  id: string;
  body?: models.RunNowBodyDto | undefined;
};
export const RunMonitorNowRequest$outboundSchema = z.object({
  id: z.string(),
  body: z.optional(models.RunNowBodyDto$outboundSchema),
});
export type RunMonitorNowResponse = models.MonitorResponseDto;
export const RunMonitorNowResponse$inboundSchemas = {
  202: models.MonitorResponseDto$inboundSchema,
};
