/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Scraped web page content.
 */
export type ScrapeWebPageResponseBody = {
  data: models.WebScrapeResponseDto;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const ScrapeWebPageResponseBody$inboundSchema: z.ZodMiniType<
  ScrapeWebPageResponseBody,
  unknown
> = z.object({
  data: models.WebScrapeResponseDto$inboundSchema,
  meta: models.PublicResponseMetaDto$inboundSchema,
});

export function scrapeWebPageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ScrapeWebPageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScrapeWebPageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScrapeWebPageResponseBody' from JSON`,
  );
}
