/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type ScrapeWebPageRequest = {
  body: models.PlatformWebScrapeDto;
};
export const ScrapeWebPageRequest$outboundSchema = z.object({
  body: models.PlatformWebScrapeDto$outboundSchema,
});
export type ScrapeWebPageResponse = models.ScrapeWebPageResponse;
export const ScrapeWebPageResponse$inboundSchemas = {
  200: models.ScrapeWebPageResponse$inboundSchema,
};
