/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SearchCompaniesRequest = {
  /**
   * Optional. Reusing the same key for the same organization returns the existing queued operation.
   */
  idempotencyKey?: string | undefined;
  body: models.PostCompanySearchDto;
};

/** @internal */
export type SearchCompaniesRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.PostCompanySearchDto$Outbound;
};

/** @internal */
export const SearchCompaniesRequest$outboundSchema: z.ZodMiniType<
  SearchCompaniesRequest$Outbound,
  SearchCompaniesRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.PostCompanySearchDto$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function searchCompaniesRequestToJSON(
  searchCompaniesRequest: SearchCompaniesRequest,
): string {
  return JSON.stringify(
    SearchCompaniesRequest$outboundSchema.parse(searchCompaniesRequest),
  );
}
