/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type SearchLinkedInKeywordPostsRequest = {
  body: models.PlatformLinkedInKeywordPostsDto;
};
export const SearchLinkedInKeywordPostsRequest$outboundSchema = z.object({
  body: models.PlatformLinkedInKeywordPostsDto$outboundSchema,
});
export type SearchLinkedInKeywordPostsResponse = models.SearchLinkedInKeywordPostsResponse;
export const SearchLinkedInKeywordPostsResponse$inboundSchemas = {
  200: models.SearchLinkedInKeywordPostsResponse$inboundSchema,
};
