/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * LinkedIn posts matching a keyword.
 */
export type SearchLinkedInKeywordPostsResponseBody = {
  data: Array<models.LinkedInPostResponseDto>;
  meta: models.PublicResponseMetaDto;
};

/** @internal */
export const SearchLinkedInKeywordPostsResponseBody$inboundSchema:
  z.ZodMiniType<SearchLinkedInKeywordPostsResponseBody, unknown> = z.object({
    data: z.array(models.LinkedInPostResponseDto$inboundSchema),
    meta: models.PublicResponseMetaDto$inboundSchema,
  });

export function searchLinkedInKeywordPostsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInKeywordPostsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInKeywordPostsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInKeywordPostsResponseBody' from JSON`,
  );
}
