/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type SearchWebRequest = {
  body: models.PlatformWebSearchDto;
};
export const SearchWebRequest$outboundSchema = z.object({
  body: models.PlatformWebSearchDto$outboundSchema,
});
export type SearchWebResponse = models.SearchWebResponse;
export const SearchWebResponse$inboundSchemas = {
  200: models.SearchWebResponse$inboundSchema,
};
