/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type SearchPeopleRequest = {
  body: models.PostPeopleSearchDto;
  idempotencyKey?: string | undefined;
};
export const SearchPeopleRequest$outboundSchema = z.object({
  body: models.PostPeopleSearchDto$outboundSchema,
  idempotencyKey: z.optional(z.string()),
});
export type SearchPeopleResponse = models.EntitySearchAcceptedDto;
export const SearchPeopleResponse$inboundSchemas = {
  202: models.EntitySearchAcceptedDto$inboundSchema,
};
