/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type SearchCompaniesRequest = {
  body: models.PostCompanySearchDto;
  idempotencyKey?: string | undefined;
};
export const SearchCompaniesRequest$outboundSchema = z.object({
  body: models.PostCompanySearchDto$outboundSchema,
  idempotencyKey: z.optional(z.string()),
});
export type SearchCompaniesResponse = models.EntitySearchAcceptedPublicDto;
export const SearchCompaniesResponse$inboundSchemas = {
  202: models.EntitySearchAcceptedPublicDto$inboundSchema,
};
