/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SearchPeopleRequest = {
  /**
   * Optional. Reusing the same key for the same organization returns the existing queued operation.
   */
  idempotencyKey?: string | undefined;
  body: models.PostPeopleSearchDto;
};

/** @internal */
export type SearchPeopleRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.PostPeopleSearchDto$Outbound;
};

/** @internal */
export const SearchPeopleRequest$outboundSchema: z.ZodMiniType<
  SearchPeopleRequest$Outbound,
  SearchPeopleRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.PostPeopleSearchDto$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function searchPeopleRequestToJSON(
  searchPeopleRequest: SearchPeopleRequest,
): string {
  return JSON.stringify(
    SearchPeopleRequest$outboundSchema.parse(searchPeopleRequest),
  );
}
