/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type StartDeepResearchRequest = {
  /**
   * Prevents duplicate work if you retry the same request with the same key.
   */
  idempotencyKey?: string | undefined;
  body: models.DeepResearchRequestDto;
};

/** @internal */
export type StartDeepResearchRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.DeepResearchRequestDto$Outbound;
};

/** @internal */
export const StartDeepResearchRequest$outboundSchema: z.ZodMiniType<
  StartDeepResearchRequest$Outbound,
  StartDeepResearchRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.DeepResearchRequestDto$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function startDeepResearchRequestToJSON(
  startDeepResearchRequest: StartDeepResearchRequest,
): string {
  return JSON.stringify(
    StartDeepResearchRequest$outboundSchema.parse(startDeepResearchRequest),
  );
}
