/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type StartDeepResearchRequest = {
  body: models.DeepResearchRequestDto;
  idempotencyKey?: string | undefined;
};
export const StartDeepResearchRequest$outboundSchema = z.object({
  body: models.DeepResearchRequestDto$outboundSchema,
  idempotencyKey: z.optional(z.string()),
});
export type StartDeepResearchResponse = models.DeepResearchQueuedResponseDto;
export const StartDeepResearchResponse$inboundSchemas = {
  202: models.DeepResearchQueuedResponseDto$inboundSchema,
};
