/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SubmitSearchRequest = {
  /**
   * Set to true to wait briefly for a completed result instead of immediately returning an operation to poll.
   */
  sync?: boolean | undefined;
  /**
   * Prevents duplicate work if you retry the same request with the same key.
   */
  idempotencyKey?: string | undefined;
  body: models.PostSearchDto;
};

export type SubmitSearchResponse =
  | models.SearchResultDto
  | models.SearchAcceptedDto;

/** @internal */
export type SubmitSearchRequest$Outbound = {
  sync?: boolean | undefined;
  "Idempotency-Key"?: string | undefined;
  body: models.PostSearchDto$Outbound;
};

/** @internal */
export const SubmitSearchRequest$outboundSchema: z.ZodMiniType<
  SubmitSearchRequest$Outbound,
  SubmitSearchRequest
> = z.pipe(
  z.object({
    sync: z.optional(z.boolean()),
    idempotencyKey: z.optional(z.string()),
    body: models.PostSearchDto$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function submitSearchRequestToJSON(
  submitSearchRequest: SubmitSearchRequest,
): string {
  return JSON.stringify(
    SubmitSearchRequest$outboundSchema.parse(submitSearchRequest),
  );
}

/** @internal */
export const SubmitSearchResponse$inboundSchema: z.ZodMiniType<
  SubmitSearchResponse,
  unknown
> = smartUnion([
  models.SearchResultDto$inboundSchema,
  models.SearchAcceptedDto$inboundSchema,
]);

export function submitSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubmitSearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubmitSearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubmitSearchResponse' from JSON`,
  );
}
