/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type SubmitSearchRequest = {
  sync?: boolean | undefined;
  body: models.PostSearchDto;
  idempotencyKey?: string | undefined;
};
export const SubmitSearchRequest$outboundSchema = z.object({
  sync: z.optional(z.boolean()),
  body: models.PostSearchDto$outboundSchema,
  idempotencyKey: z.optional(z.string()),
});
export type SubmitSearchResponse = models.SearchResultDto | models.SearchAcceptedDto;
export const SubmitSearchResponse$inboundSchemas = {
  200: models.SearchResultDto$inboundSchema,
  202: models.SearchAcceptedDto$inboundSchema,
};
