/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type SubmitEnrichmentRequest = {
  body: models.PostEnrichmentDto;
  idempotencyKey?: string | undefined;
};
export const SubmitEnrichmentRequest$outboundSchema = z.object({
  body: models.PostEnrichmentDto$outboundSchema,
  idempotencyKey: z.optional(z.string()),
});
export type SubmitEnrichmentResponse = models.EnrichmentSyncResponseDto | models.EnrichmentQueuedResponseDto;
export const SubmitEnrichmentResponse$inboundSchemas = {
  200: models.EnrichmentSyncResponseDto$inboundSchema,
  202: models.EnrichmentQueuedResponseDto$inboundSchema,
};
