/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SubmitEnrichmentRequest = {
  /**
   * Prevents duplicate work if you retry the same request with the same key.
   */
  idempotencyKey?: string | undefined;
  body: models.PostEnrichmentDto;
};

export type SubmitEnrichmentResponse =
  | models.EnrichmentQueuedResponseDto
  | models.EnrichmentSyncResponseDto;

/** @internal */
export type SubmitEnrichmentRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.PostEnrichmentDto$Outbound;
};

/** @internal */
export const SubmitEnrichmentRequest$outboundSchema: z.ZodMiniType<
  SubmitEnrichmentRequest$Outbound,
  SubmitEnrichmentRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.PostEnrichmentDto$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function submitEnrichmentRequestToJSON(
  submitEnrichmentRequest: SubmitEnrichmentRequest,
): string {
  return JSON.stringify(
    SubmitEnrichmentRequest$outboundSchema.parse(submitEnrichmentRequest),
  );
}

/** @internal */
export const SubmitEnrichmentResponse$inboundSchema: z.ZodMiniType<
  SubmitEnrichmentResponse,
  unknown
> = smartUnion([
  models.EnrichmentQueuedResponseDto$inboundSchema,
  models.EnrichmentSyncResponseDto$inboundSchema,
]);

export function submitEnrichmentResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubmitEnrichmentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubmitEnrichmentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubmitEnrichmentResponse' from JSON`,
  );
}
