/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateMonitorRequest = {
  /**
   * Monitor ID.
   */
  id: string;
  body: models.UpdateMonitorDto;
};

/** @internal */
export type UpdateMonitorRequest$Outbound = {
  id: string;
  body: models.UpdateMonitorDto$Outbound;
};

/** @internal */
export const UpdateMonitorRequest$outboundSchema: z.ZodMiniType<
  UpdateMonitorRequest$Outbound,
  UpdateMonitorRequest
> = z.object({
  id: z.string(),
  body: models.UpdateMonitorDto$outboundSchema,
});

export function updateMonitorRequestToJSON(
  updateMonitorRequest: UpdateMonitorRequest,
): string {
  return JSON.stringify(
    UpdateMonitorRequest$outboundSchema.parse(updateMonitorRequest),
  );
}
