/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";
export type UpdateMonitorRequest = {
  id: string;
  body: models.UpdateMonitorDto;
};
export const UpdateMonitorRequest$outboundSchema = z.object({
  id: z.string(),
  body: models.UpdateMonitorDto$outboundSchema,
});
export type UpdateMonitorResponse = models.MonitorResponseDto;
export const UpdateMonitorResponse$inboundSchemas = {
  200: models.MonitorResponseDto$inboundSchema,
};
