/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";
import type { WebScrapeBatchAcceptedResponseDto } from "./web-scrape-batch-accepted-response-dto.js";
import { WebScrapeBatchAcceptedResponseDto$inboundSchema, WebScrapeBatchAcceptedResponseDto$outboundSchema } from "./web-scrape-batch-accepted-response-dto.js";

export type BatchScrapeWebPagesResponse = {
  "data": WebScrapeBatchAcceptedResponseDto;
  "meta": PublicResponseMetaDto;
};
export type BatchScrapeWebPagesResponse$Outbound = BatchScrapeWebPagesResponse;

export const BatchScrapeWebPagesResponse$inboundSchema = (z.object({
  "data": z.lazy(() => WebScrapeBatchAcceptedResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<BatchScrapeWebPagesResponse>;
export const BatchScrapeWebPagesResponse$outboundSchema = (z.object({
  "data": z.lazy(() => WebScrapeBatchAcceptedResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<BatchScrapeWebPagesResponse$Outbound>;

export function batchScrapeWebPagesResponseFromJSON(jsonString: string): BatchScrapeWebPagesResponse {
  return BatchScrapeWebPagesResponse$inboundSchema.parse(JSON.parse(jsonString)) as BatchScrapeWebPagesResponse;
}

export function batchScrapeWebPagesResponseToJSON(value: BatchScrapeWebPagesResponse): string {
  return JSON.stringify(BatchScrapeWebPagesResponse$outboundSchema.parse(value));
}
