/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";
import type { WebCrawlAcceptedResponseDto } from "./web-crawl-accepted-response-dto.js";
import { WebCrawlAcceptedResponseDto$inboundSchema, WebCrawlAcceptedResponseDto$outboundSchema } from "./web-crawl-accepted-response-dto.js";

export type CrawlWebSiteResponse = {
  "data": WebCrawlAcceptedResponseDto;
  "meta": PublicResponseMetaDto;
};
export type CrawlWebSiteResponse$Outbound = CrawlWebSiteResponse;

export const CrawlWebSiteResponse$inboundSchema = (z.object({
  "data": z.lazy(() => WebCrawlAcceptedResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<CrawlWebSiteResponse>;
export const CrawlWebSiteResponse$outboundSchema = (z.object({
  "data": z.lazy(() => WebCrawlAcceptedResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<CrawlWebSiteResponse$Outbound>;

export function crawlWebSiteResponseFromJSON(jsonString: string): CrawlWebSiteResponse {
  return CrawlWebSiteResponse$inboundSchema.parse(JSON.parse(jsonString)) as CrawlWebSiteResponse;
}

export function crawlWebSiteResponseToJSON(value: CrawlWebSiteResponse): string {
  return JSON.stringify(CrawlWebSiteResponse$outboundSchema.parse(value));
}
