/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Monitor type
 */
export const Type = {
  LinkedinKeyword: "linkedin_keyword",
  LinkedinProfile: "linkedin_profile",
  LinkedinCompany: "linkedin_company",
  LinkedinPost: "linkedin_post",
  InstagramProfile: "instagram_profile",
  InstagramPost: "instagram_post",
  XProfile: "x_profile",
  XKeyword: "x_keyword",
  RedditKeyword: "reddit_keyword",
  RedditSubreddit: "reddit_subreddit",
  TiktokKeyword: "tiktok_keyword",
  TiktokHashtag: "tiktok_hashtag",
  WebSearch: "web_search",
  SiteSearch: "site_search",
} as const;
/**
 * Monitor type
 */
export type Type = ClosedEnum<typeof Type>;

/**
 * Type-specific configuration (query, filters, etc.)
 */
export type Config = {};

export type CreateMonitorDto = {
  /**
   * Human-readable name
   */
  name: string;
  /**
   * Monitor type
   */
  type: Type;
  /**
   * Type-specific configuration (query, filters, etc.)
   */
  config: Config;
  /**
   * Cadence in minutes (minimum 60 for scraper-based types: LinkedIn, Instagram, X, Reddit, TikTok; minimum 15 for web)
   */
  cadenceMinutes?: number | undefined;
  /**
   * Max results per run (1-100)
   */
  maxResults?: number | undefined;
  /**
   * Force fresh scrape bypassing cache
   */
  forceFresh?: boolean | undefined;
  /**
   * Cache TTL in days for profile/company monitors (1-90)
   */
  cacheTtlDays?: number | undefined;
  /**
   * LinkedIn post URL (required for linkedin_post type)
   */
  postUrl?: string | undefined;
};

/** @internal */
export const Type$outboundSchema: z.ZodMiniEnum<typeof Type> = z.enum(Type);

/** @internal */
export type Config$Outbound = {};

/** @internal */
export const Config$outboundSchema: z.ZodMiniType<Config$Outbound, Config> = z
  .object({});

export function configToJSON(config: Config): string {
  return JSON.stringify(Config$outboundSchema.parse(config));
}

/** @internal */
export type CreateMonitorDto$Outbound = {
  name: string;
  type: string;
  config: Config$Outbound;
  cadence_minutes: number;
  max_results: number;
  force_fresh: boolean;
  cache_ttl_days: number;
  post_url?: string | undefined;
};

/** @internal */
export const CreateMonitorDto$outboundSchema: z.ZodMiniType<
  CreateMonitorDto$Outbound,
  CreateMonitorDto
> = z.pipe(
  z.object({
    name: z.string(),
    type: Type$outboundSchema,
    config: z.lazy(() => Config$outboundSchema),
    cadenceMinutes: z._default(z.number(), 60),
    maxResults: z._default(z.number(), 10),
    forceFresh: z._default(z.boolean(), false),
    cacheTtlDays: z._default(z.number(), 14),
    postUrl: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cadenceMinutes: "cadence_minutes",
      maxResults: "max_results",
      forceFresh: "force_fresh",
      cacheTtlDays: "cache_ttl_days",
      postUrl: "post_url",
    });
  }),
);

export function createMonitorDtoToJSON(
  createMonitorDto: CreateMonitorDto,
): string {
  return JSON.stringify(
    CreateMonitorDto$outboundSchema.parse(createMonitorDto),
  );
}
