/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type CreateMonitorDto = {
  "name": string;
  "type": "linkedin_keyword" | "linkedin_profile" | "linkedin_company" | "linkedin_post" | "instagram_profile" | "instagram_post" | "x_profile" | "x_keyword" | "reddit_keyword" | "reddit_subreddit" | "tiktok_keyword" | "tiktok_hashtag" | "web_search" | "site_search";
  "config": Record<string, unknown>;
  "cadence_minutes"?: number;
  "max_results"?: number;
  "force_fresh"?: boolean;
  "cache_ttl_days"?: number;
  "post_url"?: string;
};
export type CreateMonitorDto$Outbound = CreateMonitorDto;

export const CreateMonitorDto$inboundSchema = (z.object({
  "name": z.string(),
  "type": z.enum(["linkedin_keyword","linkedin_profile","linkedin_company","linkedin_post","instagram_profile","instagram_post","x_profile","x_keyword","reddit_keyword","reddit_subreddit","tiktok_keyword","tiktok_hashtag","web_search","site_search"]),
  "config": z.object({

}),
  "cadence_minutes": z.optional(z.number()),
  "max_results": z.optional(z.number()),
  "force_fresh": z.optional(z.boolean()),
  "cache_ttl_days": z.optional(z.number()),
  "post_url": z.optional(z.string()),
})) as z.ZodType<CreateMonitorDto>;
export const CreateMonitorDto$outboundSchema = (z.object({
  "name": z.string(),
  "type": z.enum(["linkedin_keyword","linkedin_profile","linkedin_company","linkedin_post","instagram_profile","instagram_post","x_profile","x_keyword","reddit_keyword","reddit_subreddit","tiktok_keyword","tiktok_hashtag","web_search","site_search"]),
  "config": z.object({

}),
  "cadence_minutes": z.optional(z.number()),
  "max_results": z.optional(z.number()),
  "force_fresh": z.optional(z.boolean()),
  "cache_ttl_days": z.optional(z.number()),
  "post_url": z.optional(z.string()),
})) as z.ZodType<CreateMonitorDto$Outbound>;

export function createMonitorDtoFromJSON(jsonString: string): CreateMonitorDto {
  return CreateMonitorDto$inboundSchema.parse(JSON.parse(jsonString)) as CreateMonitorDto;
}

export function createMonitorDtoToJSON(value: CreateMonitorDto): string {
  return JSON.stringify(CreateMonitorDto$outboundSchema.parse(value));
}
