/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeepResearchAcceptedMetaDto,
  DeepResearchAcceptedMetaDto$inboundSchema,
} from "./deep-research-accepted-meta-dto.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const DeepResearchQueuedResponseDtoStatus = {
  Queued: "queued",
} as const;
export type DeepResearchQueuedResponseDtoStatus = ClosedEnum<
  typeof DeepResearchQueuedResponseDtoStatus
>;

export type DeepResearchQueuedResponseDto = {
  id: string;
  operationId: string;
  status: DeepResearchQueuedResponseDtoStatus;
  pollUrl: string;
  meta?: DeepResearchAcceptedMetaDto | undefined;
};

/** @internal */
export const DeepResearchQueuedResponseDtoStatus$inboundSchema: z.ZodMiniEnum<
  typeof DeepResearchQueuedResponseDtoStatus
> = z.enum(DeepResearchQueuedResponseDtoStatus);

/** @internal */
export const DeepResearchQueuedResponseDto$inboundSchema: z.ZodMiniType<
  DeepResearchQueuedResponseDto,
  unknown
> = z.object({
  id: types.string(),
  operationId: types.string(),
  status: DeepResearchQueuedResponseDtoStatus$inboundSchema,
  pollUrl: types.string(),
  meta: types.optional(DeepResearchAcceptedMetaDto$inboundSchema),
});

export function deepResearchQueuedResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<DeepResearchQueuedResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeepResearchQueuedResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeepResearchQueuedResponseDto' from JSON`,
  );
}
