/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type DeepResearchAcceptedMetaDto = {
  "schemaContract"?: {
  [key: string]: unknown;
};
};
export type DeepResearchAcceptedMetaDto$Outbound = DeepResearchAcceptedMetaDto;

export const DeepResearchAcceptedMetaDto$inboundSchema = (z.object({
  "schemaContract": z.optional(z.record(z.string(), z.unknown())),
})) as z.ZodType<DeepResearchAcceptedMetaDto>;
export const DeepResearchAcceptedMetaDto$outboundSchema = (z.object({
  "schemaContract": z.optional(z.record(z.string(), z.unknown())),
})) as z.ZodType<DeepResearchAcceptedMetaDto$Outbound>;

export function deepResearchAcceptedMetaDtoFromJSON(jsonString: string): DeepResearchAcceptedMetaDto {
  return DeepResearchAcceptedMetaDto$inboundSchema.parse(JSON.parse(jsonString)) as DeepResearchAcceptedMetaDto;
}

export function deepResearchAcceptedMetaDtoToJSON(value: DeepResearchAcceptedMetaDto): string {
  return JSON.stringify(DeepResearchAcceptedMetaDto$outboundSchema.parse(value));
}
