/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { smartUnion } from "../types/smart-union.js";
import {
  DeepResearchBudgetRequestDto,
  DeepResearchBudgetRequestDto$Outbound,
  DeepResearchBudgetRequestDto$outboundSchema,
} from "./deep-research-budget-request-dto.js";

/**
 * Optional caller-owned anchor metadata overlaid into matching schema paths. Arrays preserve the previously documented contract; objects support keyed anchors used by the runtime.
 */
export type InputAnchors = Array<{ [k: string]: any }> | { [k: string]: any };

export type DeepResearchRequestDto = {
  /**
   * Research instructions.
   */
  prompt: string;
  /**
   * JSON Schema that defines the dynamic shape of result.data returned after the operation completes.
   */
  schema: { [k: string]: any };
  /**
   * Optional model override.
   */
  model?: string | undefined;
  /**
   * Optional seed URLs to prioritize during research.
   */
  urls?: Array<string> | undefined;
  /**
   * Optional caller-owned anchor metadata overlaid into matching schema paths. Arrays preserve the previously documented contract; objects support keyed anchors used by the runtime.
   */
  inputAnchors?: Array<{ [k: string]: any }> | { [k: string]: any } | undefined;
  /**
   * Maximum credits to spend. Must match budget.maxCredits when both are provided.
   */
  maxCredits?: number | undefined;
  budget?: DeepResearchBudgetRequestDto | undefined;
  /**
   * Project context handle.
   */
  projectId?: string | undefined;
};

/** @internal */
export type InputAnchors$Outbound = Array<{ [k: string]: any }> | {
  [k: string]: any;
};

/** @internal */
export const InputAnchors$outboundSchema: z.ZodMiniType<
  InputAnchors$Outbound,
  InputAnchors
> = smartUnion([
  z.array(z.record(z.string(), z.any())),
  z.record(z.string(), z.any()),
]);

export function inputAnchorsToJSON(inputAnchors: InputAnchors): string {
  return JSON.stringify(InputAnchors$outboundSchema.parse(inputAnchors));
}

/** @internal */
export type DeepResearchRequestDto$Outbound = {
  prompt: string;
  schema: { [k: string]: any };
  model?: string | undefined;
  urls?: Array<string> | undefined;
  inputAnchors?: Array<{ [k: string]: any }> | { [k: string]: any } | undefined;
  maxCredits?: number | undefined;
  budget?: DeepResearchBudgetRequestDto$Outbound | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const DeepResearchRequestDto$outboundSchema: z.ZodMiniType<
  DeepResearchRequestDto$Outbound,
  DeepResearchRequestDto
> = z.object({
  prompt: z.string(),
  schema: z.record(z.string(), z.any()),
  model: z.optional(z.string()),
  urls: z.optional(z.array(z.string())),
  inputAnchors: z.optional(
    smartUnion([
      z.array(z.record(z.string(), z.any())),
      z.record(z.string(), z.any()),
    ]),
  ),
  maxCredits: z.optional(z.int()),
  budget: z.optional(DeepResearchBudgetRequestDto$outboundSchema),
  projectId: z.optional(z.string()),
});

export function deepResearchRequestDtoToJSON(
  deepResearchRequestDto: DeepResearchRequestDto,
): string {
  return JSON.stringify(
    DeepResearchRequestDto$outboundSchema.parse(deepResearchRequestDto),
  );
}
