/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeepResearchBudgetRequestDto = {
  /**
   * Maximum credits to spend on this research run.
   */
  maxCredits?: number | undefined;
};

/** @internal */
export type DeepResearchBudgetRequestDto$Outbound = {
  maxCredits?: number | undefined;
};

/** @internal */
export const DeepResearchBudgetRequestDto$outboundSchema: z.ZodMiniType<
  DeepResearchBudgetRequestDto$Outbound,
  DeepResearchBudgetRequestDto
> = z.object({
  maxCredits: z.optional(z.int()),
});

export function deepResearchBudgetRequestDtoToJSON(
  deepResearchBudgetRequestDto: DeepResearchBudgetRequestDto,
): string {
  return JSON.stringify(
    DeepResearchBudgetRequestDto$outboundSchema.parse(
      deepResearchBudgetRequestDto,
    ),
  );
}
