/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type DeepResearchBudgetRequestDto = {
  "maxCredits"?: number;
};
export type DeepResearchBudgetRequestDto$Outbound = DeepResearchBudgetRequestDto;

export const DeepResearchBudgetRequestDto$inboundSchema = (z.object({
  "maxCredits": z.optional(z.number().int()),
})) as z.ZodType<DeepResearchBudgetRequestDto>;
export const DeepResearchBudgetRequestDto$outboundSchema = (z.object({
  "maxCredits": z.optional(z.number().int()),
})) as z.ZodType<DeepResearchBudgetRequestDto$Outbound>;

export function deepResearchBudgetRequestDtoFromJSON(jsonString: string): DeepResearchBudgetRequestDto {
  return DeepResearchBudgetRequestDto$inboundSchema.parse(JSON.parse(jsonString)) as DeepResearchBudgetRequestDto;
}

export function deepResearchBudgetRequestDtoToJSON(value: DeepResearchBudgetRequestDto): string {
  return JSON.stringify(DeepResearchBudgetRequestDto$outboundSchema.parse(value));
}
