/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { DeepResearchBudgetRequestDto } from "./deep-research-budget-request-dto.js";
import { DeepResearchBudgetRequestDto$inboundSchema, DeepResearchBudgetRequestDto$outboundSchema } from "./deep-research-budget-request-dto.js";

export type DeepResearchRequestDto = {
  "prompt": string;
  "schema": {
  [key: string]: unknown;
};
  "model"?: string;
  "urls"?: string[];
  "inputAnchors"?: {
  [key: string]: unknown;
}[] | {
  [key: string]: unknown;
};
  "maxCredits"?: number;
  "budget"?: DeepResearchBudgetRequestDto;
};
export type DeepResearchRequestDto$Outbound = DeepResearchRequestDto;

export const DeepResearchRequestDto$inboundSchema = (z.object({
  "prompt": z.string(),
  "schema": z.record(z.string(), z.unknown()),
  "model": z.optional(z.string()),
  "urls": z.optional(z.array(z.string())),
  "inputAnchors": z.optional(z.union([z.array(z.record(z.string(), z.unknown())), z.record(z.string(), z.unknown())])),
  "maxCredits": z.optional(z.number().int()),
  "budget": z.optional(z.lazy(() => DeepResearchBudgetRequestDto$inboundSchema)),
})) as z.ZodType<DeepResearchRequestDto>;
export const DeepResearchRequestDto$outboundSchema = (z.object({
  "prompt": z.string(),
  "schema": z.record(z.string(), z.unknown()),
  "model": z.optional(z.string()),
  "urls": z.optional(z.array(z.string())),
  "inputAnchors": z.optional(z.union([z.array(z.record(z.string(), z.unknown())), z.record(z.string(), z.unknown())])),
  "maxCredits": z.optional(z.number().int()),
  "budget": z.optional(z.lazy(() => DeepResearchBudgetRequestDto$outboundSchema)),
})) as z.ZodType<DeepResearchRequestDto$Outbound>;

export function deepResearchRequestDtoFromJSON(jsonString: string): DeepResearchRequestDto {
  return DeepResearchRequestDto$inboundSchema.parse(JSON.parse(jsonString)) as DeepResearchRequestDto;
}

export function deepResearchRequestDtoToJSON(value: DeepResearchRequestDto): string {
  return JSON.stringify(DeepResearchRequestDto$outboundSchema.parse(value));
}
