/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { DeepResearchAcceptedMetaDto } from "./deep-research-accepted-meta-dto.js";
import { DeepResearchAcceptedMetaDto$inboundSchema, DeepResearchAcceptedMetaDto$outboundSchema } from "./deep-research-accepted-meta-dto.js";

export type DeepResearchQueuedResponseDto = {
  "id": string;
  "operationId": string;
  "status": "queued";
  "pollUrl": string;
  "meta"?: DeepResearchAcceptedMetaDto;
};
export type DeepResearchQueuedResponseDto$Outbound = DeepResearchQueuedResponseDto;

export const DeepResearchQueuedResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
  "meta": z.optional(z.lazy(() => DeepResearchAcceptedMetaDto$inboundSchema)),
})) as z.ZodType<DeepResearchQueuedResponseDto>;
export const DeepResearchQueuedResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
  "meta": z.optional(z.lazy(() => DeepResearchAcceptedMetaDto$outboundSchema)),
})) as z.ZodType<DeepResearchQueuedResponseDto$Outbound>;

export function deepResearchQueuedResponseDtoFromJSON(jsonString: string): DeepResearchQueuedResponseDto {
  return DeepResearchQueuedResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as DeepResearchQueuedResponseDto;
}

export function deepResearchQueuedResponseDtoToJSON(value: DeepResearchQueuedResponseDto): string {
  return JSON.stringify(DeepResearchQueuedResponseDto$outboundSchema.parse(value));
}
