/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type EnrichmentQueuedResponseDto = {
  "id": string;
  "operationId": string;
  "status": "queued";
  "pollUrl": string;
  "meta": PublicResponseMetaDto;
};
export type EnrichmentQueuedResponseDto$Outbound = EnrichmentQueuedResponseDto;

export const EnrichmentQueuedResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<EnrichmentQueuedResponseDto>;
export const EnrichmentQueuedResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<EnrichmentQueuedResponseDto$Outbound>;

export function enrichmentQueuedResponseDtoFromJSON(jsonString: string): EnrichmentQueuedResponseDto {
  return EnrichmentQueuedResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as EnrichmentQueuedResponseDto;
}

export function enrichmentQueuedResponseDtoToJSON(value: EnrichmentQueuedResponseDto): string {
  return JSON.stringify(EnrichmentQueuedResponseDto$outboundSchema.parse(value));
}
