/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PublicResponseMetaDto,
  PublicResponseMetaDto$inboundSchema,
} from "./public-response-meta-dto.js";

export type EnrichmentSyncResponseDto = {
  data: { [k: string]: any };
  meta: PublicResponseMetaDto;
};

/** @internal */
export const EnrichmentSyncResponseDto$inboundSchema: z.ZodMiniType<
  EnrichmentSyncResponseDto,
  unknown
> = z.object({
  data: z.record(z.string(), z.any()),
  meta: PublicResponseMetaDto$inboundSchema,
});

export function enrichmentSyncResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<EnrichmentSyncResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnrichmentSyncResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnrichmentSyncResponseDto' from JSON`,
  );
}
