/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type EnrichmentSyncResponseDto = {
  "data": {
  [key: string]: unknown;
};
  "meta": PublicResponseMetaDto;
};
export type EnrichmentSyncResponseDto$Outbound = EnrichmentSyncResponseDto;

export const EnrichmentSyncResponseDto$inboundSchema = (z.object({
  "data": z.record(z.string(), z.unknown()),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<EnrichmentSyncResponseDto>;
export const EnrichmentSyncResponseDto$outboundSchema = (z.object({
  "data": z.record(z.string(), z.unknown()),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<EnrichmentSyncResponseDto$Outbound>;

export function enrichmentSyncResponseDtoFromJSON(jsonString: string): EnrichmentSyncResponseDto {
  return EnrichmentSyncResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as EnrichmentSyncResponseDto;
}

export function enrichmentSyncResponseDtoToJSON(value: EnrichmentSyncResponseDto): string {
  return JSON.stringify(EnrichmentSyncResponseDto$outboundSchema.parse(value));
}
