/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PublicResponseMetaDto,
  PublicResponseMetaDto$inboundSchema,
} from "./public-response-meta-dto.js";

export const EnrichmentQueuedResponseDtoStatus = {
  Queued: "queued",
} as const;
export type EnrichmentQueuedResponseDtoStatus = ClosedEnum<
  typeof EnrichmentQueuedResponseDtoStatus
>;

export type EnrichmentQueuedResponseDto = {
  id: string;
  operationId: string;
  status: EnrichmentQueuedResponseDtoStatus;
  pollUrl: string;
  meta: PublicResponseMetaDto;
};

/** @internal */
export const EnrichmentQueuedResponseDtoStatus$inboundSchema: z.ZodMiniEnum<
  typeof EnrichmentQueuedResponseDtoStatus
> = z.enum(EnrichmentQueuedResponseDtoStatus);

/** @internal */
export const EnrichmentQueuedResponseDto$inboundSchema: z.ZodMiniType<
  EnrichmentQueuedResponseDto,
  unknown
> = z.object({
  id: types.string(),
  operationId: types.string(),
  status: EnrichmentQueuedResponseDtoStatus$inboundSchema,
  pollUrl: types.string(),
  meta: PublicResponseMetaDto$inboundSchema,
});

export function enrichmentQueuedResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<EnrichmentQueuedResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnrichmentQueuedResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnrichmentQueuedResponseDto' from JSON`,
  );
}
