/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { EntityEmployeeCountFilterDto } from "./entity-employee-count-filter-dto.js";
import { EntityEmployeeCountFilterDto$inboundSchema, EntityEmployeeCountFilterDto$outboundSchema } from "./entity-employee-count-filter-dto.js";

export type EntityCompanyNestedFilterDto = {
  "names"?: string[];
  "domains"?: string[];
  "linkedinUrls"?: string[];
  "industries"?: string[];
  "employeeCount"?: EntityEmployeeCountFilterDto;
  "signals"?: string[];
};
export type EntityCompanyNestedFilterDto$Outbound = EntityCompanyNestedFilterDto;

export const EntityCompanyNestedFilterDto$inboundSchema = (z.object({
  "names": z.optional(z.array(z.string())),
  "domains": z.optional(z.array(z.string())),
  "linkedinUrls": z.optional(z.array(z.string())),
  "industries": z.optional(z.array(z.string())),
  "employeeCount": z.optional(z.lazy(() => EntityEmployeeCountFilterDto$inboundSchema)),
  "signals": z.optional(z.array(z.string())),
})) as z.ZodType<EntityCompanyNestedFilterDto>;
export const EntityCompanyNestedFilterDto$outboundSchema = (z.object({
  "names": z.optional(z.array(z.string())),
  "domains": z.optional(z.array(z.string())),
  "linkedinUrls": z.optional(z.array(z.string())),
  "industries": z.optional(z.array(z.string())),
  "employeeCount": z.optional(z.lazy(() => EntityEmployeeCountFilterDto$outboundSchema)),
  "signals": z.optional(z.array(z.string())),
})) as z.ZodType<EntityCompanyNestedFilterDto$Outbound>;

export function entityCompanyNestedFilterDtoFromJSON(jsonString: string): EntityCompanyNestedFilterDto {
  return EntityCompanyNestedFilterDto$inboundSchema.parse(JSON.parse(jsonString)) as EntityCompanyNestedFilterDto;
}

export function entityCompanyNestedFilterDtoToJSON(value: EntityCompanyNestedFilterDto): string {
  return JSON.stringify(EntityCompanyNestedFilterDto$outboundSchema.parse(value));
}
