/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type EntitySearchAcceptedDto = {
  "id": string;
  "operationId": string;
  "status": "queued";
  "pollUrl": string;
  "meta": Record<string, unknown>;
};
export type EntitySearchAcceptedDto$Outbound = EntitySearchAcceptedDto;

export const EntitySearchAcceptedDto$inboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
  "meta": z.object({

}),
})) as z.ZodType<EntitySearchAcceptedDto>;
export const EntitySearchAcceptedDto$outboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
  "meta": z.object({

}),
})) as z.ZodType<EntitySearchAcceptedDto$Outbound>;

export function entitySearchAcceptedDtoFromJSON(jsonString: string): EntitySearchAcceptedDto {
  return EntitySearchAcceptedDto$inboundSchema.parse(JSON.parse(jsonString)) as EntitySearchAcceptedDto;
}

export function entitySearchAcceptedDtoToJSON(value: EntitySearchAcceptedDto): string {
  return JSON.stringify(EntitySearchAcceptedDto$outboundSchema.parse(value));
}
