/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type EntityEmployeeCountFilterDto = {
  "min"?: number;
  "max"?: number;
};
export type EntityEmployeeCountFilterDto$Outbound = EntityEmployeeCountFilterDto;

export const EntityEmployeeCountFilterDto$inboundSchema = (z.object({
  "min": z.optional(z.number()),
  "max": z.optional(z.number()),
})) as z.ZodType<EntityEmployeeCountFilterDto>;
export const EntityEmployeeCountFilterDto$outboundSchema = (z.object({
  "min": z.optional(z.number()),
  "max": z.optional(z.number()),
})) as z.ZodType<EntityEmployeeCountFilterDto$Outbound>;

export function entityEmployeeCountFilterDtoFromJSON(jsonString: string): EntityEmployeeCountFilterDto {
  return EntityEmployeeCountFilterDto$inboundSchema.parse(JSON.parse(jsonString)) as EntityEmployeeCountFilterDto;
}

export function entityEmployeeCountFilterDtoToJSON(value: EntityEmployeeCountFilterDto): string {
  return JSON.stringify(EntityEmployeeCountFilterDto$outboundSchema.parse(value));
}
