/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  EntityEmployeeCountFilterDto,
  EntityEmployeeCountFilterDto$Outbound,
  EntityEmployeeCountFilterDto$outboundSchema,
} from "./entity-employee-count-filter-dto.js";

export type EntityCompanyNestedFilterDto = {
  names?: Array<string> | undefined;
  domains?: Array<string> | undefined;
  linkedinUrls?: Array<string> | undefined;
  industries?: Array<string> | undefined;
  employeeCount?: EntityEmployeeCountFilterDto | undefined;
  signals?: Array<string> | undefined;
};

/** @internal */
export type EntityCompanyNestedFilterDto$Outbound = {
  names?: Array<string> | undefined;
  domains?: Array<string> | undefined;
  linkedinUrls?: Array<string> | undefined;
  industries?: Array<string> | undefined;
  employeeCount?: EntityEmployeeCountFilterDto$Outbound | undefined;
  signals?: Array<string> | undefined;
};

/** @internal */
export const EntityCompanyNestedFilterDto$outboundSchema: z.ZodMiniType<
  EntityCompanyNestedFilterDto$Outbound,
  EntityCompanyNestedFilterDto
> = z.object({
  names: z.optional(z.array(z.string())),
  domains: z.optional(z.array(z.string())),
  linkedinUrls: z.optional(z.array(z.string())),
  industries: z.optional(z.array(z.string())),
  employeeCount: z.optional(EntityEmployeeCountFilterDto$outboundSchema),
  signals: z.optional(z.array(z.string())),
});

export function entityCompanyNestedFilterDtoToJSON(
  entityCompanyNestedFilterDto: EntityCompanyNestedFilterDto,
): string {
  return JSON.stringify(
    EntityCompanyNestedFilterDto$outboundSchema.parse(
      entityCompanyNestedFilterDto,
    ),
  );
}
