/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type EntitySearchAcceptedPublicDto = {
  "id": string;
  "operationId": string;
  "status": "queued";
  "pollUrl": string;
};
export type EntitySearchAcceptedPublicDto$Outbound = EntitySearchAcceptedPublicDto;

export const EntitySearchAcceptedPublicDto$inboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
})) as z.ZodType<EntitySearchAcceptedPublicDto>;
export const EntitySearchAcceptedPublicDto$outboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
})) as z.ZodType<EntitySearchAcceptedPublicDto$Outbound>;

export function entitySearchAcceptedPublicDtoFromJSON(jsonString: string): EntitySearchAcceptedPublicDto {
  return EntitySearchAcceptedPublicDto$inboundSchema.parse(JSON.parse(jsonString)) as EntitySearchAcceptedPublicDto;
}

export function entitySearchAcceptedPublicDtoToJSON(value: EntitySearchAcceptedPublicDto): string {
  return JSON.stringify(EntitySearchAcceptedPublicDto$outboundSchema.parse(value));
}
