/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Status = {
  Queued: "queued",
} as const;
export type Status = ClosedEnum<typeof Status>;

export type EntitySearchAcceptedPublicDto = {
  id: string;
  operationId: string;
  status: Status;
  pollUrl: string;
};

/** @internal */
export const Status$inboundSchema: z.ZodMiniEnum<typeof Status> = z.enum(
  Status,
);

/** @internal */
export const EntitySearchAcceptedPublicDto$inboundSchema: z.ZodMiniType<
  EntitySearchAcceptedPublicDto,
  unknown
> = z.object({
  id: types.string(),
  operationId: types.string(),
  status: Status$inboundSchema,
  pollUrl: types.string(),
});

export function entitySearchAcceptedPublicDtoFromJSON(
  jsonString: string,
): SafeParseResult<EntitySearchAcceptedPublicDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EntitySearchAcceptedPublicDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntitySearchAcceptedPublicDto' from JSON`,
  );
}
