/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  EntityCompanyNestedFilterDto,
  EntityCompanyNestedFilterDto$Outbound,
  EntityCompanyNestedFilterDto$outboundSchema,
} from "./entity-company-nested-filter-dto.js";
import {
  EntityEmployeeCountFilterDto,
  EntityEmployeeCountFilterDto$Outbound,
  EntityEmployeeCountFilterDto$outboundSchema,
} from "./entity-employee-count-filter-dto.js";

export const TitleMatch = {
  Exact: "exact",
  Similar: "similar",
} as const;
export type TitleMatch = ClosedEnum<typeof TitleMatch>;

export type EntitySearchFiltersDto = {
  titles?: Array<string> | undefined;
  titleMatch?: TitleMatch | undefined;
  locations?: Array<string> | undefined;
  industries?: Array<string> | undefined;
  employeeCount?: EntityEmployeeCountFilterDto | undefined;
  signals?: Array<string> | undefined;
  company?: EntityCompanyNestedFilterDto | undefined;
};

/** @internal */
export const TitleMatch$outboundSchema: z.ZodMiniEnum<typeof TitleMatch> = z
  .enum(TitleMatch);

/** @internal */
export type EntitySearchFiltersDto$Outbound = {
  titles?: Array<string> | undefined;
  titleMatch?: string | undefined;
  locations?: Array<string> | undefined;
  industries?: Array<string> | undefined;
  employeeCount?: EntityEmployeeCountFilterDto$Outbound | undefined;
  signals?: Array<string> | undefined;
  company?: EntityCompanyNestedFilterDto$Outbound | undefined;
};

/** @internal */
export const EntitySearchFiltersDto$outboundSchema: z.ZodMiniType<
  EntitySearchFiltersDto$Outbound,
  EntitySearchFiltersDto
> = z.object({
  titles: z.optional(z.array(z.string())),
  titleMatch: z.optional(TitleMatch$outboundSchema),
  locations: z.optional(z.array(z.string())),
  industries: z.optional(z.array(z.string())),
  employeeCount: z.optional(EntityEmployeeCountFilterDto$outboundSchema),
  signals: z.optional(z.array(z.string())),
  company: z.optional(EntityCompanyNestedFilterDto$outboundSchema),
});

export function entitySearchFiltersDtoToJSON(
  entitySearchFiltersDto: EntitySearchFiltersDto,
): string {
  return JSON.stringify(
    EntitySearchFiltersDto$outboundSchema.parse(entitySearchFiltersDto),
  );
}
