/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type EntityEmployeeCountFilterDto = {
  min?: number | undefined;
  max?: number | undefined;
};

/** @internal */
export type EntityEmployeeCountFilterDto$Outbound = {
  min?: number | undefined;
  max?: number | undefined;
};

/** @internal */
export const EntityEmployeeCountFilterDto$outboundSchema: z.ZodMiniType<
  EntityEmployeeCountFilterDto$Outbound,
  EntityEmployeeCountFilterDto
> = z.object({
  min: z.optional(z.number()),
  max: z.optional(z.number()),
});

export function entityEmployeeCountFilterDtoToJSON(
  entityEmployeeCountFilterDto: EntityEmployeeCountFilterDto,
): string {
  return JSON.stringify(
    EntityEmployeeCountFilterDto$outboundSchema.parse(
      entityEmployeeCountFilterDto,
    ),
  );
}
