/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const EntitySearchAcceptedDtoStatus = {
  Queued: "queued",
} as const;
export type EntitySearchAcceptedDtoStatus = ClosedEnum<
  typeof EntitySearchAcceptedDtoStatus
>;

export type Meta = {};

export type EntitySearchAcceptedDto = {
  id: string;
  operationId: string;
  status: EntitySearchAcceptedDtoStatus;
  pollUrl: string;
  meta: Meta;
};

/** @internal */
export const EntitySearchAcceptedDtoStatus$inboundSchema: z.ZodMiniEnum<
  typeof EntitySearchAcceptedDtoStatus
> = z.enum(EntitySearchAcceptedDtoStatus);

/** @internal */
export const Meta$inboundSchema: z.ZodMiniType<Meta, unknown> = z.object({});

export function metaFromJSON(
  jsonString: string,
): SafeParseResult<Meta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Meta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Meta' from JSON`,
  );
}

/** @internal */
export const EntitySearchAcceptedDto$inboundSchema: z.ZodMiniType<
  EntitySearchAcceptedDto,
  unknown
> = z.object({
  id: types.string(),
  operationId: types.string(),
  status: EntitySearchAcceptedDtoStatus$inboundSchema,
  pollUrl: types.string(),
  meta: z.lazy(() => Meta$inboundSchema),
});

export function entitySearchAcceptedDtoFromJSON(
  jsonString: string,
): SafeParseResult<EntitySearchAcceptedDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EntitySearchAcceptedDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntitySearchAcceptedDto' from JSON`,
  );
}
