/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInFinderResponseDto } from "./linked-in-finder-response-dto.js";
import { LinkedInFinderResponseDto$inboundSchema, LinkedInFinderResponseDto$outboundSchema } from "./linked-in-finder-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type FindLinkedInCompaniesResponse = {
  "data": LinkedInFinderResponseDto[];
  "meta": PublicResponseMetaDto;
};
export type FindLinkedInCompaniesResponse$Outbound = FindLinkedInCompaniesResponse;

export const FindLinkedInCompaniesResponse$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInFinderResponseDto$inboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<FindLinkedInCompaniesResponse>;
export const FindLinkedInCompaniesResponse$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInFinderResponseDto$outboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<FindLinkedInCompaniesResponse$Outbound>;

export function findLinkedInCompaniesResponseFromJSON(jsonString: string): FindLinkedInCompaniesResponse {
  return FindLinkedInCompaniesResponse$inboundSchema.parse(JSON.parse(jsonString)) as FindLinkedInCompaniesResponse;
}

export function findLinkedInCompaniesResponseToJSON(value: FindLinkedInCompaniesResponse): string {
  return JSON.stringify(FindLinkedInCompaniesResponse$outboundSchema.parse(value));
}
