/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInProfileResponseDto } from "./linked-in-profile-response-dto.js";
import { LinkedInProfileResponseDto$inboundSchema, LinkedInProfileResponseDto$outboundSchema } from "./linked-in-profile-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type GetLinkedInProfileResponse = {
  "data": (LinkedInProfileResponseDto);
  "meta": PublicResponseMetaDto;
};
export type GetLinkedInProfileResponse$Outbound = GetLinkedInProfileResponse;

export const GetLinkedInProfileResponse$inboundSchema = (z.object({
  "data": z.lazy(() => LinkedInProfileResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<GetLinkedInProfileResponse>;
export const GetLinkedInProfileResponse$outboundSchema = (z.object({
  "data": z.lazy(() => LinkedInProfileResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<GetLinkedInProfileResponse$Outbound>;

export function getLinkedInProfileResponseFromJSON(jsonString: string): GetLinkedInProfileResponse {
  return GetLinkedInProfileResponse$inboundSchema.parse(JSON.parse(jsonString)) as GetLinkedInProfileResponse;
}

export function getLinkedInProfileResponseToJSON(value: GetLinkedInProfileResponse): string {
  return JSON.stringify(GetLinkedInProfileResponse$outboundSchema.parse(value));
}
