/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";
import type { TikTokProfileScrapeResponseDto } from "./tik-tok-profile-scrape-response-dto.js";
import { TikTokProfileScrapeResponseDto$inboundSchema, TikTokProfileScrapeResponseDto$outboundSchema } from "./tik-tok-profile-scrape-response-dto.js";

export type GetTikTokProfileResponse = {
  "data": TikTokProfileScrapeResponseDto;
  "meta": PublicResponseMetaDto;
};
export type GetTikTokProfileResponse$Outbound = GetTikTokProfileResponse;

export const GetTikTokProfileResponse$inboundSchema = (z.object({
  "data": z.lazy(() => TikTokProfileScrapeResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<GetTikTokProfileResponse>;
export const GetTikTokProfileResponse$outboundSchema = (z.object({
  "data": z.lazy(() => TikTokProfileScrapeResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<GetTikTokProfileResponse$Outbound>;

export function getTikTokProfileResponseFromJSON(jsonString: string): GetTikTokProfileResponse {
  return GetTikTokProfileResponse$inboundSchema.parse(JSON.parse(jsonString)) as GetTikTokProfileResponse;
}

export function getTikTokProfileResponseToJSON(value: GetTikTokProfileResponse): string {
  return JSON.stringify(GetTikTokProfileResponse$outboundSchema.parse(value));
}
