/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInCompanyResponseDto } from "./linked-in-company-response-dto.js";
import { LinkedInCompanyResponseDto$inboundSchema, LinkedInCompanyResponseDto$outboundSchema } from "./linked-in-company-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type GetLinkedInCompanyResponse = {
  "data": (LinkedInCompanyResponseDto);
  "meta": PublicResponseMetaDto;
};
export type GetLinkedInCompanyResponse$Outbound = GetLinkedInCompanyResponse;

export const GetLinkedInCompanyResponse$inboundSchema = (z.object({
  "data": z.lazy(() => LinkedInCompanyResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<GetLinkedInCompanyResponse>;
export const GetLinkedInCompanyResponse$outboundSchema = (z.object({
  "data": z.lazy(() => LinkedInCompanyResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<GetLinkedInCompanyResponse$Outbound>;

export function getLinkedInCompanyResponseFromJSON(jsonString: string): GetLinkedInCompanyResponse {
  return GetLinkedInCompanyResponse$inboundSchema.parse(JSON.parse(jsonString)) as GetLinkedInCompanyResponse;
}

export function getLinkedInCompanyResponseToJSON(value: GetLinkedInCompanyResponse): string {
  return JSON.stringify(GetLinkedInCompanyResponse$outboundSchema.parse(value));
}
