/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { InstagramPostResponseDto } from "./instagram-post-response-dto.js";
import { InstagramPostResponseDto$inboundSchema, InstagramPostResponseDto$outboundSchema } from "./instagram-post-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type GetInstagramPostResponse = {
  "data": (InstagramPostResponseDto);
  "meta": PublicResponseMetaDto;
};
export type GetInstagramPostResponse$Outbound = GetInstagramPostResponse;

export const GetInstagramPostResponse$inboundSchema = (z.object({
  "data": z.lazy(() => InstagramPostResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<GetInstagramPostResponse>;
export const GetInstagramPostResponse$outboundSchema = (z.object({
  "data": z.lazy(() => InstagramPostResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<GetInstagramPostResponse$Outbound>;

export function getInstagramPostResponseFromJSON(jsonString: string): GetInstagramPostResponse {
  return GetInstagramPostResponse$inboundSchema.parse(JSON.parse(jsonString)) as GetInstagramPostResponse;
}

export function getInstagramPostResponseToJSON(value: GetInstagramPostResponse): string {
  return JSON.stringify(GetInstagramPostResponse$outboundSchema.parse(value));
}
