/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { InstagramProfileResponseDto } from "./instagram-profile-response-dto.js";
import { InstagramProfileResponseDto$inboundSchema, InstagramProfileResponseDto$outboundSchema } from "./instagram-profile-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type GetInstagramProfileResponse = {
  "data": (InstagramProfileResponseDto);
  "meta": PublicResponseMetaDto;
};
export type GetInstagramProfileResponse$Outbound = GetInstagramProfileResponse;

export const GetInstagramProfileResponse$inboundSchema = (z.object({
  "data": z.lazy(() => InstagramProfileResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<GetInstagramProfileResponse>;
export const GetInstagramProfileResponse$outboundSchema = (z.object({
  "data": z.lazy(() => InstagramProfileResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<GetInstagramProfileResponse$Outbound>;

export function getInstagramProfileResponseFromJSON(jsonString: string): GetInstagramProfileResponse {
  return GetInstagramProfileResponse$inboundSchema.parse(JSON.parse(jsonString)) as GetInstagramProfileResponse;
}

export function getInstagramProfileResponseToJSON(value: GetInstagramProfileResponse): string {
  return JSON.stringify(GetInstagramProfileResponse$outboundSchema.parse(value));
}
