/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type InstagramCommentResponseDto = {
  id?: string | null | undefined;
  text: string;
  ownerUsername?: string | null | undefined;
  ownerId?: string | null | undefined;
  timestamp?: string | null | undefined;
  likesCount?: number | null | undefined;
  repliesCount?: number | null | undefined;
  replies?: Array<InstagramCommentResponseDto> | null | undefined;
};

/** @internal */
export const InstagramCommentResponseDto$inboundSchema: z.ZodMiniType<
  InstagramCommentResponseDto,
  unknown
> = z.pipe(
  z.object({
    id: z.optional(z.nullable(types.string())),
    text: types.string(),
    owner_username: z.optional(z.nullable(types.string())),
    owner_id: z.optional(z.nullable(types.string())),
    timestamp: z.optional(z.nullable(types.string())),
    likes_count: z.optional(z.nullable(types.number())),
    replies_count: z.optional(z.nullable(types.number())),
    replies: z.optional(z.nullable(z.array(z.lazy(() =>
      InstagramCommentResponseDto$inboundSchema
    )))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "owner_username": "ownerUsername",
      "owner_id": "ownerId",
      "likes_count": "likesCount",
      "replies_count": "repliesCount",
    });
  }),
);

export function instagramCommentResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<InstagramCommentResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstagramCommentResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstagramCommentResponseDto' from JSON`,
  );
}
