/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type InstagramFollowProfileResponseDto = {
  instagramUserId?: string | null | undefined;
  username: string;
  displayName?: string | null | undefined;
  profileUrl?: string | null | undefined;
  profilePictureUrl?: string | null | undefined;
  isPrivate?: boolean | null | undefined;
  isVerified?: boolean | null | undefined;
};

/** @internal */
export const InstagramFollowProfileResponseDto$inboundSchema: z.ZodMiniType<
  InstagramFollowProfileResponseDto,
  unknown
> = z.pipe(
  z.object({
    instagram_user_id: z.optional(z.nullable(types.string())),
    username: types.string(),
    display_name: z.optional(z.nullable(types.string())),
    profile_url: z.optional(z.nullable(types.string())),
    profile_picture_url: z.optional(z.nullable(types.string())),
    is_private: z.optional(z.nullable(types.boolean())),
    is_verified: z.optional(z.nullable(types.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "instagram_user_id": "instagramUserId",
      "display_name": "displayName",
      "profile_url": "profileUrl",
      "profile_picture_url": "profilePictureUrl",
      "is_private": "isPrivate",
      "is_verified": "isVerified",
    });
  }),
);

export function instagramFollowProfileResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<InstagramFollowProfileResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstagramFollowProfileResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstagramFollowProfileResponseDto' from JSON`,
  );
}
