/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  InstagramFollowEdgeResponseDto,
  InstagramFollowEdgeResponseDto$inboundSchema,
} from "./instagram-follow-edge-response-dto.js";

export const RelationType = {
  Followers: "followers",
  Following: "following",
} as const;
export type RelationType = OpenEnum<typeof RelationType>;

export type InstagramFollowScrapeResponseDto = {
  username: string;
  relationType: RelationType;
  edges: Array<InstagramFollowEdgeResponseDto>;
  requestedLimit?: number | null | undefined;
  returnedCount: number;
};

/** @internal */
export const RelationType$inboundSchema: z.ZodMiniType<RelationType, unknown> =
  openEnums.inboundSchema(RelationType);

/** @internal */
export const InstagramFollowScrapeResponseDto$inboundSchema: z.ZodMiniType<
  InstagramFollowScrapeResponseDto,
  unknown
> = z.pipe(
  z.object({
    username: types.string(),
    relation_type: RelationType$inboundSchema,
    edges: z.array(InstagramFollowEdgeResponseDto$inboundSchema),
    requested_limit: z.optional(z.nullable(types.number())),
    returned_count: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "relation_type": "relationType",
      "requested_limit": "requestedLimit",
      "returned_count": "returnedCount",
    });
  }),
);

export function instagramFollowScrapeResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<InstagramFollowScrapeResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstagramFollowScrapeResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstagramFollowScrapeResponseDto' from JSON`,
  );
}
