/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  InstagramFollowProfileResponseDto,
  InstagramFollowProfileResponseDto$inboundSchema,
} from "./instagram-follow-profile-response-dto.js";

export const InstagramFollowEdgeResponseDtoRelationType = {
  Followers: "followers",
  Following: "following",
} as const;
export type InstagramFollowEdgeResponseDtoRelationType = OpenEnum<
  typeof InstagramFollowEdgeResponseDtoRelationType
>;

export type InstagramFollowEdgeResponseDto = {
  relationType: InstagramFollowEdgeResponseDtoRelationType;
  seedUsername: string;
  follower: InstagramFollowProfileResponseDto;
  following: InstagramFollowProfileResponseDto;
};

/** @internal */
export const InstagramFollowEdgeResponseDtoRelationType$inboundSchema:
  z.ZodMiniType<InstagramFollowEdgeResponseDtoRelationType, unknown> = openEnums
    .inboundSchema(InstagramFollowEdgeResponseDtoRelationType);

/** @internal */
export const InstagramFollowEdgeResponseDto$inboundSchema: z.ZodMiniType<
  InstagramFollowEdgeResponseDto,
  unknown
> = z.pipe(
  z.object({
    relation_type: InstagramFollowEdgeResponseDtoRelationType$inboundSchema,
    seed_username: types.string(),
    follower: InstagramFollowProfileResponseDto$inboundSchema,
    following: InstagramFollowProfileResponseDto$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "relation_type": "relationType",
      "seed_username": "seedUsername",
    });
  }),
);

export function instagramFollowEdgeResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<InstagramFollowEdgeResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstagramFollowEdgeResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstagramFollowEdgeResponseDto' from JSON`,
  );
}
