/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type InstagramProfileResponseDto = {
  "instagram_user_id"?: string | null;
  "username": string;
  "display_name"?: string | null;
  "bio"?: string | null;
  "profile_url"?: string | null;
  "profile_picture_url"?: string | null;
  "website_url"?: string | null;
  "followers_count"?: number | null;
  "following_count"?: number | null;
  "posts_count"?: number | null;
  "is_verified"?: boolean | null;
  "is_business_account"?: boolean | null;
  "is_private"?: boolean | null;
};
export type InstagramProfileResponseDto$Outbound = InstagramProfileResponseDto;

export const InstagramProfileResponseDto$inboundSchema = (z.object({
  "instagram_user_id": z.optional(z.nullable(z.string())),
  "username": z.string(),
  "display_name": z.optional(z.nullable(z.string())),
  "bio": z.optional(z.nullable(z.string())),
  "profile_url": z.optional(z.nullable(z.string())),
  "profile_picture_url": z.optional(z.nullable(z.string())),
  "website_url": z.optional(z.nullable(z.string())),
  "followers_count": z.optional(z.nullable(z.number())),
  "following_count": z.optional(z.nullable(z.number())),
  "posts_count": z.optional(z.nullable(z.number())),
  "is_verified": z.optional(z.nullable(z.boolean())),
  "is_business_account": z.optional(z.nullable(z.boolean())),
  "is_private": z.optional(z.nullable(z.boolean())),
})) as z.ZodType<InstagramProfileResponseDto>;
export const InstagramProfileResponseDto$outboundSchema = (z.object({
  "instagram_user_id": z.optional(z.nullable(z.string())),
  "username": z.string(),
  "display_name": z.optional(z.nullable(z.string())),
  "bio": z.optional(z.nullable(z.string())),
  "profile_url": z.optional(z.nullable(z.string())),
  "profile_picture_url": z.optional(z.nullable(z.string())),
  "website_url": z.optional(z.nullable(z.string())),
  "followers_count": z.optional(z.nullable(z.number())),
  "following_count": z.optional(z.nullable(z.number())),
  "posts_count": z.optional(z.nullable(z.number())),
  "is_verified": z.optional(z.nullable(z.boolean())),
  "is_business_account": z.optional(z.nullable(z.boolean())),
  "is_private": z.optional(z.nullable(z.boolean())),
})) as z.ZodType<InstagramProfileResponseDto$Outbound>;

export function instagramProfileResponseDtoFromJSON(jsonString: string): InstagramProfileResponseDto {
  return InstagramProfileResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as InstagramProfileResponseDto;
}

export function instagramProfileResponseDtoToJSON(value: InstagramProfileResponseDto): string {
  return JSON.stringify(InstagramProfileResponseDto$outboundSchema.parse(value));
}
