/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { InstagramFollowEdgeResponseDto } from "./instagram-follow-edge-response-dto.js";
import { InstagramFollowEdgeResponseDto$inboundSchema, InstagramFollowEdgeResponseDto$outboundSchema } from "./instagram-follow-edge-response-dto.js";

export type InstagramFollowScrapeResponseDto = {
  "username": string;
  "relation_type": "followers" | "following";
  "edges": InstagramFollowEdgeResponseDto[];
  "requested_limit"?: number | null;
  "returned_count": number;
};
export type InstagramFollowScrapeResponseDto$Outbound = InstagramFollowScrapeResponseDto;

export const InstagramFollowScrapeResponseDto$inboundSchema = (z.object({
  "username": z.string(),
  "relation_type": z.enum(["followers","following"]),
  "edges": z.array(z.lazy(() => InstagramFollowEdgeResponseDto$inboundSchema)),
  "requested_limit": z.optional(z.nullable(z.number())),
  "returned_count": z.number(),
})) as z.ZodType<InstagramFollowScrapeResponseDto>;
export const InstagramFollowScrapeResponseDto$outboundSchema = (z.object({
  "username": z.string(),
  "relation_type": z.enum(["followers","following"]),
  "edges": z.array(z.lazy(() => InstagramFollowEdgeResponseDto$outboundSchema)),
  "requested_limit": z.optional(z.nullable(z.number())),
  "returned_count": z.number(),
})) as z.ZodType<InstagramFollowScrapeResponseDto$Outbound>;

export function instagramFollowScrapeResponseDtoFromJSON(jsonString: string): InstagramFollowScrapeResponseDto {
  return InstagramFollowScrapeResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as InstagramFollowScrapeResponseDto;
}

export function instagramFollowScrapeResponseDtoToJSON(value: InstagramFollowScrapeResponseDto): string {
  return JSON.stringify(InstagramFollowScrapeResponseDto$outboundSchema.parse(value));
}
