/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { InstagramFollowProfileResponseDto } from "./instagram-follow-profile-response-dto.js";
import { InstagramFollowProfileResponseDto$inboundSchema, InstagramFollowProfileResponseDto$outboundSchema } from "./instagram-follow-profile-response-dto.js";

export type InstagramFollowEdgeResponseDto = {
  "relation_type": "followers" | "following";
  "seed_username": string;
  "follower": InstagramFollowProfileResponseDto;
  "following": InstagramFollowProfileResponseDto;
};
export type InstagramFollowEdgeResponseDto$Outbound = InstagramFollowEdgeResponseDto;

export const InstagramFollowEdgeResponseDto$inboundSchema = (z.object({
  "relation_type": z.enum(["followers","following"]),
  "seed_username": z.string(),
  "follower": z.lazy(() => InstagramFollowProfileResponseDto$inboundSchema),
  "following": z.lazy(() => InstagramFollowProfileResponseDto$inboundSchema),
})) as z.ZodType<InstagramFollowEdgeResponseDto>;
export const InstagramFollowEdgeResponseDto$outboundSchema = (z.object({
  "relation_type": z.enum(["followers","following"]),
  "seed_username": z.string(),
  "follower": z.lazy(() => InstagramFollowProfileResponseDto$outboundSchema),
  "following": z.lazy(() => InstagramFollowProfileResponseDto$outboundSchema),
})) as z.ZodType<InstagramFollowEdgeResponseDto$Outbound>;

export function instagramFollowEdgeResponseDtoFromJSON(jsonString: string): InstagramFollowEdgeResponseDto {
  return InstagramFollowEdgeResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as InstagramFollowEdgeResponseDto;
}

export function instagramFollowEdgeResponseDtoToJSON(value: InstagramFollowEdgeResponseDto): string {
  return JSON.stringify(InstagramFollowEdgeResponseDto$outboundSchema.parse(value));
}
