/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type InstagramCommentResponseDto = {
  "id"?: string | null;
  "text": string;
  "owner_username"?: string | null;
  "owner_id"?: string | null;
  "timestamp"?: string | null;
  "likes_count"?: number | null;
  "replies_count"?: number | null;
  "replies"?: InstagramCommentResponseDto[] | null;
};
export type InstagramCommentResponseDto$Outbound = InstagramCommentResponseDto;

export const InstagramCommentResponseDto$inboundSchema = (z.object({
  "id": z.optional(z.nullable(z.string())),
  "text": z.string(),
  "owner_username": z.optional(z.nullable(z.string())),
  "owner_id": z.optional(z.nullable(z.string())),
  "timestamp": z.optional(z.nullable(z.string())),
  "likes_count": z.optional(z.nullable(z.number())),
  "replies_count": z.optional(z.nullable(z.number())),
  "replies": z.optional(z.nullable(z.array(z.lazy(() => InstagramCommentResponseDto$inboundSchema)))),
})) as z.ZodType<InstagramCommentResponseDto>;
export const InstagramCommentResponseDto$outboundSchema = (z.object({
  "id": z.optional(z.nullable(z.string())),
  "text": z.string(),
  "owner_username": z.optional(z.nullable(z.string())),
  "owner_id": z.optional(z.nullable(z.string())),
  "timestamp": z.optional(z.nullable(z.string())),
  "likes_count": z.optional(z.nullable(z.number())),
  "replies_count": z.optional(z.nullable(z.number())),
  "replies": z.optional(z.nullable(z.array(z.lazy(() => InstagramCommentResponseDto$outboundSchema)))),
})) as z.ZodType<InstagramCommentResponseDto$Outbound>;

export function instagramCommentResponseDtoFromJSON(jsonString: string): InstagramCommentResponseDto {
  return InstagramCommentResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as InstagramCommentResponseDto;
}

export function instagramCommentResponseDtoToJSON(value: InstagramCommentResponseDto): string {
  return JSON.stringify(InstagramCommentResponseDto$outboundSchema.parse(value));
}
