/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type InstagramPostResponseDto = {
  "shortcode": string;
  "post_url"?: string | null;
  "post_type"?: string | null;
  "caption"?: string | null;
  "hashtags"?: string[] | null;
  "mentions"?: string[] | null;
  "likes_count"?: number | null;
  "comments_count"?: number | null;
  "video_views_count"?: number | null;
  "display_url"?: string | null;
  "dimensions_height"?: number | null;
  "dimensions_width"?: number | null;
  "is_sponsored"?: boolean | null;
  "location_name"?: string | null;
  "location_id"?: string | null;
  "posted_at"?: string | null;
  "author_username"?: string | null;
  "owner_id"?: string | null;
};
export type InstagramPostResponseDto$Outbound = InstagramPostResponseDto;

export const InstagramPostResponseDto$inboundSchema = (z.object({
  "shortcode": z.string(),
  "post_url": z.optional(z.nullable(z.string())),
  "post_type": z.optional(z.nullable(z.string())),
  "caption": z.optional(z.nullable(z.string())),
  "hashtags": z.optional(z.nullable(z.array(z.string()))),
  "mentions": z.optional(z.nullable(z.array(z.string()))),
  "likes_count": z.optional(z.nullable(z.number())),
  "comments_count": z.optional(z.nullable(z.number())),
  "video_views_count": z.optional(z.nullable(z.number())),
  "display_url": z.optional(z.nullable(z.string())),
  "dimensions_height": z.optional(z.nullable(z.number())),
  "dimensions_width": z.optional(z.nullable(z.number())),
  "is_sponsored": z.optional(z.nullable(z.boolean())),
  "location_name": z.optional(z.nullable(z.string())),
  "location_id": z.optional(z.nullable(z.string())),
  "posted_at": z.optional(z.nullable(z.string())),
  "author_username": z.optional(z.nullable(z.string())),
  "owner_id": z.optional(z.nullable(z.string())),
})) as z.ZodType<InstagramPostResponseDto>;
export const InstagramPostResponseDto$outboundSchema = (z.object({
  "shortcode": z.string(),
  "post_url": z.optional(z.nullable(z.string())),
  "post_type": z.optional(z.nullable(z.string())),
  "caption": z.optional(z.nullable(z.string())),
  "hashtags": z.optional(z.nullable(z.array(z.string()))),
  "mentions": z.optional(z.nullable(z.array(z.string()))),
  "likes_count": z.optional(z.nullable(z.number())),
  "comments_count": z.optional(z.nullable(z.number())),
  "video_views_count": z.optional(z.nullable(z.number())),
  "display_url": z.optional(z.nullable(z.string())),
  "dimensions_height": z.optional(z.nullable(z.number())),
  "dimensions_width": z.optional(z.nullable(z.number())),
  "is_sponsored": z.optional(z.nullable(z.boolean())),
  "location_name": z.optional(z.nullable(z.string())),
  "location_id": z.optional(z.nullable(z.string())),
  "posted_at": z.optional(z.nullable(z.string())),
  "author_username": z.optional(z.nullable(z.string())),
  "owner_id": z.optional(z.nullable(z.string())),
})) as z.ZodType<InstagramPostResponseDto$Outbound>;

export function instagramPostResponseDtoFromJSON(jsonString: string): InstagramPostResponseDto {
  return InstagramPostResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as InstagramPostResponseDto;
}

export function instagramPostResponseDtoToJSON(value: InstagramPostResponseDto): string {
  return JSON.stringify(InstagramPostResponseDto$outboundSchema.parse(value));
}
