/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type InstagramFollowProfileResponseDto = {
  "instagram_user_id"?: string | null;
  "username": string;
  "display_name"?: string | null;
  "profile_url"?: string | null;
  "profile_picture_url"?: string | null;
  "is_private"?: boolean | null;
  "is_verified"?: boolean | null;
};
export type InstagramFollowProfileResponseDto$Outbound = InstagramFollowProfileResponseDto;

export const InstagramFollowProfileResponseDto$inboundSchema = (z.object({
  "instagram_user_id": z.optional(z.nullable(z.string())),
  "username": z.string(),
  "display_name": z.optional(z.nullable(z.string())),
  "profile_url": z.optional(z.nullable(z.string())),
  "profile_picture_url": z.optional(z.nullable(z.string())),
  "is_private": z.optional(z.nullable(z.boolean())),
  "is_verified": z.optional(z.nullable(z.boolean())),
})) as z.ZodType<InstagramFollowProfileResponseDto>;
export const InstagramFollowProfileResponseDto$outboundSchema = (z.object({
  "instagram_user_id": z.optional(z.nullable(z.string())),
  "username": z.string(),
  "display_name": z.optional(z.nullable(z.string())),
  "profile_url": z.optional(z.nullable(z.string())),
  "profile_picture_url": z.optional(z.nullable(z.string())),
  "is_private": z.optional(z.nullable(z.boolean())),
  "is_verified": z.optional(z.nullable(z.boolean())),
})) as z.ZodType<InstagramFollowProfileResponseDto$Outbound>;

export function instagramFollowProfileResponseDtoFromJSON(jsonString: string): InstagramFollowProfileResponseDto {
  return InstagramFollowProfileResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as InstagramFollowProfileResponseDto;
}

export function instagramFollowProfileResponseDtoToJSON(value: InstagramFollowProfileResponseDto): string {
  return JSON.stringify(InstagramFollowProfileResponseDto$outboundSchema.parse(value));
}
