/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  LinkedInPostResponseDto,
  LinkedInPostResponseDto$inboundSchema,
} from "./linked-in-post-response-dto.js";

export type LinkedInCompanyPostsResponseDto = {
  companySlug: string;
  posts: Array<LinkedInPostResponseDto>;
  description?: string | null | undefined;
};

/** @internal */
export const LinkedInCompanyPostsResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInCompanyPostsResponseDto,
  unknown
> = z.object({
  companySlug: types.string(),
  posts: z.array(LinkedInPostResponseDto$inboundSchema),
  description: z.optional(z.nullable(types.string())),
});

export function linkedInCompanyPostsResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInCompanyPostsResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInCompanyPostsResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInCompanyPostsResponseDto' from JSON`,
  );
}
