/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInProfileActivityActorResponseDto } from "./linked-in-profile-activity-actor-response-dto.js";
import { LinkedInProfileActivityActorResponseDto$inboundSchema, LinkedInProfileActivityActorResponseDto$outboundSchema } from "./linked-in-profile-activity-actor-response-dto.js";
import type { LinkedInProfileActivityPostResponseDto } from "./linked-in-profile-activity-post-response-dto.js";
import { LinkedInProfileActivityPostResponseDto$inboundSchema, LinkedInProfileActivityPostResponseDto$outboundSchema } from "./linked-in-profile-activity-post-response-dto.js";

export type LinkedInProfileReactionResponseDto = {
  "id"?: string | null;
  "profileUrl": string;
  "profileUsername": string;
  "reactionType": string;
  "reactedAt"?: string | null;
  "sourceUrl"?: string | null;
  "post": LinkedInProfileActivityPostResponseDto;
  "actor"?: (LinkedInProfileActivityActorResponseDto);
};
export type LinkedInProfileReactionResponseDto$Outbound = LinkedInProfileReactionResponseDto;

export const LinkedInProfileReactionResponseDto$inboundSchema = (z.object({
  "id": z.optional(z.nullable(z.string())),
  "profileUrl": z.string(),
  "profileUsername": z.string(),
  "reactionType": z.string(),
  "reactedAt": z.optional(z.nullable(z.string())),
  "sourceUrl": z.optional(z.nullable(z.string())),
  "post": z.lazy(() => LinkedInProfileActivityPostResponseDto$inboundSchema),
  "actor": z.optional(z.lazy(() => LinkedInProfileActivityActorResponseDto$inboundSchema)),
})) as z.ZodType<LinkedInProfileReactionResponseDto>;
export const LinkedInProfileReactionResponseDto$outboundSchema = (z.object({
  "id": z.optional(z.nullable(z.string())),
  "profileUrl": z.string(),
  "profileUsername": z.string(),
  "reactionType": z.string(),
  "reactedAt": z.optional(z.nullable(z.string())),
  "sourceUrl": z.optional(z.nullable(z.string())),
  "post": z.lazy(() => LinkedInProfileActivityPostResponseDto$outboundSchema),
  "actor": z.optional(z.lazy(() => LinkedInProfileActivityActorResponseDto$outboundSchema)),
})) as z.ZodType<LinkedInProfileReactionResponseDto$Outbound>;

export function linkedInProfileReactionResponseDtoFromJSON(jsonString: string): LinkedInProfileReactionResponseDto {
  return LinkedInProfileReactionResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInProfileReactionResponseDto;
}

export function linkedInProfileReactionResponseDtoToJSON(value: LinkedInProfileReactionResponseDto): string {
  return JSON.stringify(LinkedInProfileReactionResponseDto$outboundSchema.parse(value));
}
