/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  LinkedInReactionActorResponseDto,
  LinkedInReactionActorResponseDto$inboundSchema,
} from "./linked-in-reaction-actor-response-dto.js";

export type LinkedInPostReactionResponseDto = {
  id: string;
  reactionType: string;
  postId: string;
  actor: LinkedInReactionActorResponseDto;
};

/** @internal */
export const LinkedInPostReactionResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInPostReactionResponseDto,
  unknown
> = z.object({
  id: types.string(),
  reactionType: types.string(),
  postId: types.string(),
  actor: LinkedInReactionActorResponseDto$inboundSchema,
});

export function linkedInPostReactionResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInPostReactionResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInPostReactionResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInPostReactionResponseDto' from JSON`,
  );
}
