/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInFinderResponseDto = {
  "linkedin_url"?: string | null;
  "domain"?: string | null;
  "company_name"?: string | null;
};
export type LinkedInFinderResponseDto$Outbound = LinkedInFinderResponseDto;

export const LinkedInFinderResponseDto$inboundSchema = (z.object({
  "linkedin_url": z.optional(z.nullable(z.string())),
  "domain": z.optional(z.nullable(z.string())),
  "company_name": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInFinderResponseDto>;
export const LinkedInFinderResponseDto$outboundSchema = (z.object({
  "linkedin_url": z.optional(z.nullable(z.string())),
  "domain": z.optional(z.nullable(z.string())),
  "company_name": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInFinderResponseDto$Outbound>;

export function linkedInFinderResponseDtoFromJSON(jsonString: string): LinkedInFinderResponseDto {
  return LinkedInFinderResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInFinderResponseDto;
}

export function linkedInFinderResponseDtoToJSON(value: LinkedInFinderResponseDto): string {
  return JSON.stringify(LinkedInFinderResponseDto$outboundSchema.parse(value));
}
