/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInRepostedByResponseDto } from "./linked-in-reposted-by-response-dto.js";
import { LinkedInRepostedByResponseDto$inboundSchema, LinkedInRepostedByResponseDto$outboundSchema } from "./linked-in-reposted-by-response-dto.js";

export type LinkedInPostResponseDto = {
  "activityId": string;
  "postUrl"?: string | null;
  "text": string;
  "postedAt"?: string | null;
  "authorName"?: string | null;
  "authorHeadline"?: string | null;
  "authorProfileUrl"?: string | null;
  "authorProfileUsername"?: string | null;
  "totalReactions"?: number | null;
  "commentsCount"?: number | null;
  "repostsCount"?: number | null;
  "isReshare"?: boolean | null;
  "repostedBy"?: (LinkedInRepostedByResponseDto);
  "contentType"?: string | null;
  "contentData"?: {
  [key: string]: unknown;
};
  "hashtags"?: string[] | null;
};
export type LinkedInPostResponseDto$Outbound = LinkedInPostResponseDto;

export const LinkedInPostResponseDto$inboundSchema = (z.object({
  "activityId": z.string(),
  "postUrl": z.optional(z.nullable(z.string())),
  "text": z.string(),
  "postedAt": z.optional(z.nullable(z.string())),
  "authorName": z.optional(z.nullable(z.string())),
  "authorHeadline": z.optional(z.nullable(z.string())),
  "authorProfileUrl": z.optional(z.nullable(z.string())),
  "authorProfileUsername": z.optional(z.nullable(z.string())),
  "totalReactions": z.optional(z.nullable(z.number())),
  "commentsCount": z.optional(z.nullable(z.number())),
  "repostsCount": z.optional(z.nullable(z.number())),
  "isReshare": z.optional(z.nullable(z.boolean())),
  "repostedBy": z.optional(z.lazy(() => LinkedInRepostedByResponseDto$inboundSchema)),
  "contentType": z.optional(z.nullable(z.string())),
  "contentData": z.optional(z.record(z.string(), z.unknown())),
  "hashtags": z.optional(z.nullable(z.array(z.string()))),
})) as z.ZodType<LinkedInPostResponseDto>;
export const LinkedInPostResponseDto$outboundSchema = (z.object({
  "activityId": z.string(),
  "postUrl": z.optional(z.nullable(z.string())),
  "text": z.string(),
  "postedAt": z.optional(z.nullable(z.string())),
  "authorName": z.optional(z.nullable(z.string())),
  "authorHeadline": z.optional(z.nullable(z.string())),
  "authorProfileUrl": z.optional(z.nullable(z.string())),
  "authorProfileUsername": z.optional(z.nullable(z.string())),
  "totalReactions": z.optional(z.nullable(z.number())),
  "commentsCount": z.optional(z.nullable(z.number())),
  "repostsCount": z.optional(z.nullable(z.number())),
  "isReshare": z.optional(z.nullable(z.boolean())),
  "repostedBy": z.optional(z.lazy(() => LinkedInRepostedByResponseDto$outboundSchema)),
  "contentType": z.optional(z.nullable(z.string())),
  "contentData": z.optional(z.record(z.string(), z.unknown())),
  "hashtags": z.optional(z.nullable(z.array(z.string()))),
})) as z.ZodType<LinkedInPostResponseDto$Outbound>;

export function linkedInPostResponseDtoFromJSON(jsonString: string): LinkedInPostResponseDto {
  return LinkedInPostResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInPostResponseDto;
}

export function linkedInPostResponseDtoToJSON(value: LinkedInPostResponseDto): string {
  return JSON.stringify(LinkedInPostResponseDto$outboundSchema.parse(value));
}
