/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInLocationResponseDto } from "./linked-in-location-response-dto.js";
import { LinkedInLocationResponseDto$inboundSchema, LinkedInLocationResponseDto$outboundSchema } from "./linked-in-location-response-dto.js";

export type LinkedInProfileResponseDto = {
  "username": string;
  "full_name"?: string | null;
  "first_name"?: string | null;
  "last_name"?: string | null;
  "headline"?: string | null;
  "about"?: string | null;
  "profile_picture_url"?: string | null;
  "location"?: (LinkedInLocationResponseDto);
  "follower_count"?: number | null;
  "connection_count"?: number | null;
  "current_company"?: string | null;
  "current_company_url"?: string | null;
  "experience"?: {
  [key: string]: unknown;
};
  "education"?: {
  [key: string]: unknown;
};
  "certifications"?: {
  [key: string]: unknown;
};
};
export type LinkedInProfileResponseDto$Outbound = LinkedInProfileResponseDto;

export const LinkedInProfileResponseDto$inboundSchema = (z.object({
  "username": z.string(),
  "full_name": z.optional(z.nullable(z.string())),
  "first_name": z.optional(z.nullable(z.string())),
  "last_name": z.optional(z.nullable(z.string())),
  "headline": z.optional(z.nullable(z.string())),
  "about": z.optional(z.nullable(z.string())),
  "profile_picture_url": z.optional(z.nullable(z.string())),
  "location": z.optional(z.lazy(() => LinkedInLocationResponseDto$inboundSchema)),
  "follower_count": z.optional(z.nullable(z.number())),
  "connection_count": z.optional(z.nullable(z.number())),
  "current_company": z.optional(z.nullable(z.string())),
  "current_company_url": z.optional(z.nullable(z.string())),
  "experience": z.optional(z.record(z.string(), z.unknown())),
  "education": z.optional(z.record(z.string(), z.unknown())),
  "certifications": z.optional(z.record(z.string(), z.unknown())),
})) as z.ZodType<LinkedInProfileResponseDto>;
export const LinkedInProfileResponseDto$outboundSchema = (z.object({
  "username": z.string(),
  "full_name": z.optional(z.nullable(z.string())),
  "first_name": z.optional(z.nullable(z.string())),
  "last_name": z.optional(z.nullable(z.string())),
  "headline": z.optional(z.nullable(z.string())),
  "about": z.optional(z.nullable(z.string())),
  "profile_picture_url": z.optional(z.nullable(z.string())),
  "location": z.optional(z.lazy(() => LinkedInLocationResponseDto$outboundSchema)),
  "follower_count": z.optional(z.nullable(z.number())),
  "connection_count": z.optional(z.nullable(z.number())),
  "current_company": z.optional(z.nullable(z.string())),
  "current_company_url": z.optional(z.nullable(z.string())),
  "experience": z.optional(z.record(z.string(), z.unknown())),
  "education": z.optional(z.record(z.string(), z.unknown())),
  "certifications": z.optional(z.record(z.string(), z.unknown())),
})) as z.ZodType<LinkedInProfileResponseDto$Outbound>;

export function linkedInProfileResponseDtoFromJSON(jsonString: string): LinkedInProfileResponseDto {
  return LinkedInProfileResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInProfileResponseDto;
}

export function linkedInProfileResponseDtoToJSON(value: LinkedInProfileResponseDto): string {
  return JSON.stringify(LinkedInProfileResponseDto$outboundSchema.parse(value));
}
