/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInReactionActorResponseDto } from "./linked-in-reaction-actor-response-dto.js";
import { LinkedInReactionActorResponseDto$inboundSchema, LinkedInReactionActorResponseDto$outboundSchema } from "./linked-in-reaction-actor-response-dto.js";

export type LinkedInPostReactionResponseDto = {
  "id": string;
  "reactionType": string;
  "postId": string;
  "actor": LinkedInReactionActorResponseDto;
};
export type LinkedInPostReactionResponseDto$Outbound = LinkedInPostReactionResponseDto;

export const LinkedInPostReactionResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "reactionType": z.string(),
  "postId": z.string(),
  "actor": z.lazy(() => LinkedInReactionActorResponseDto$inboundSchema),
})) as z.ZodType<LinkedInPostReactionResponseDto>;
export const LinkedInPostReactionResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "reactionType": z.string(),
  "postId": z.string(),
  "actor": z.lazy(() => LinkedInReactionActorResponseDto$outboundSchema),
})) as z.ZodType<LinkedInPostReactionResponseDto$Outbound>;

export function linkedInPostReactionResponseDtoFromJSON(jsonString: string): LinkedInPostReactionResponseDto {
  return LinkedInPostReactionResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInPostReactionResponseDto;
}

export function linkedInPostReactionResponseDtoToJSON(value: LinkedInPostReactionResponseDto): string {
  return JSON.stringify(LinkedInPostReactionResponseDto$outboundSchema.parse(value));
}
