/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInLocationResponseDto = {
  "country"?: string | null;
  "city"?: string | null;
  "full"?: string | null;
};
export type LinkedInLocationResponseDto$Outbound = LinkedInLocationResponseDto;

export const LinkedInLocationResponseDto$inboundSchema = (z.object({
  "country": z.optional(z.nullable(z.string())),
  "city": z.optional(z.nullable(z.string())),
  "full": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInLocationResponseDto>;
export const LinkedInLocationResponseDto$outboundSchema = (z.object({
  "country": z.optional(z.nullable(z.string())),
  "city": z.optional(z.nullable(z.string())),
  "full": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInLocationResponseDto$Outbound>;

export function linkedInLocationResponseDtoFromJSON(jsonString: string): LinkedInLocationResponseDto {
  return LinkedInLocationResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInLocationResponseDto;
}

export function linkedInLocationResponseDtoToJSON(value: LinkedInLocationResponseDto): string {
  return JSON.stringify(LinkedInLocationResponseDto$outboundSchema.parse(value));
}
