/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInProfileActivityPostResponseDto = {
  "postId"?: string | null;
  "postUrl"?: string | null;
  "text"?: string | null;
  "authorName"?: string | null;
  "authorProfileUrl"?: string | null;
  "authorCompanyUrl"?: string | null;
  "postedAt"?: string | null;
  "reactionCount"?: number | null;
  "commentCount"?: number | null;
  "repostCount"?: number | null;
};
export type LinkedInProfileActivityPostResponseDto$Outbound = LinkedInProfileActivityPostResponseDto;

export const LinkedInProfileActivityPostResponseDto$inboundSchema = (z.object({
  "postId": z.optional(z.nullable(z.string())),
  "postUrl": z.optional(z.nullable(z.string())),
  "text": z.optional(z.nullable(z.string())),
  "authorName": z.optional(z.nullable(z.string())),
  "authorProfileUrl": z.optional(z.nullable(z.string())),
  "authorCompanyUrl": z.optional(z.nullable(z.string())),
  "postedAt": z.optional(z.nullable(z.string())),
  "reactionCount": z.optional(z.nullable(z.number())),
  "commentCount": z.optional(z.nullable(z.number())),
  "repostCount": z.optional(z.nullable(z.number())),
})) as z.ZodType<LinkedInProfileActivityPostResponseDto>;
export const LinkedInProfileActivityPostResponseDto$outboundSchema = (z.object({
  "postId": z.optional(z.nullable(z.string())),
  "postUrl": z.optional(z.nullable(z.string())),
  "text": z.optional(z.nullable(z.string())),
  "authorName": z.optional(z.nullable(z.string())),
  "authorProfileUrl": z.optional(z.nullable(z.string())),
  "authorCompanyUrl": z.optional(z.nullable(z.string())),
  "postedAt": z.optional(z.nullable(z.string())),
  "reactionCount": z.optional(z.nullable(z.number())),
  "commentCount": z.optional(z.nullable(z.number())),
  "repostCount": z.optional(z.nullable(z.number())),
})) as z.ZodType<LinkedInProfileActivityPostResponseDto$Outbound>;

export function linkedInProfileActivityPostResponseDtoFromJSON(jsonString: string): LinkedInProfileActivityPostResponseDto {
  return LinkedInProfileActivityPostResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInProfileActivityPostResponseDto;
}

export function linkedInProfileActivityPostResponseDtoToJSON(value: LinkedInProfileActivityPostResponseDto): string {
  return JSON.stringify(LinkedInProfileActivityPostResponseDto$outboundSchema.parse(value));
}
