/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  LinkedInPostResponseDto,
  LinkedInPostResponseDto$inboundSchema,
} from "./linked-in-post-response-dto.js";

export type Author = {
  name?: string | null | undefined;
  headline?: string | null | undefined;
  linkedinUrl?: string | null | undefined;
  avatar?: string | null | undefined;
  publicIdentifier?: string | null | undefined;
};

export type LinkedInProfilePostsResponseDto = {
  username: string;
  posts: Array<LinkedInPostResponseDto>;
  bio?: string | null | undefined;
  author?: Author | null | undefined;
};

/** @internal */
export const Author$inboundSchema: z.ZodMiniType<Author, unknown> = z.object({
  name: z.optional(z.nullable(types.string())),
  headline: z.optional(z.nullable(types.string())),
  linkedinUrl: z.optional(z.nullable(types.string())),
  avatar: z.optional(z.nullable(types.string())),
  publicIdentifier: z.optional(z.nullable(types.string())),
});

export function authorFromJSON(
  jsonString: string,
): SafeParseResult<Author, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Author$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Author' from JSON`,
  );
}

/** @internal */
export const LinkedInProfilePostsResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInProfilePostsResponseDto,
  unknown
> = z.object({
  username: types.string(),
  posts: z.array(LinkedInPostResponseDto$inboundSchema),
  bio: z.optional(z.nullable(types.string())),
  author: z.optional(z.nullable(z.lazy(() => Author$inboundSchema))),
});

export function linkedInProfilePostsResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInProfilePostsResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInProfilePostsResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInProfilePostsResponseDto' from JSON`,
  );
}
