/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  LinkedInProfileActivityPostResponseDto,
  LinkedInProfileActivityPostResponseDto$inboundSchema,
} from "./linked-in-profile-activity-post-response-dto.js";

export const LinkedInProfileReactionResponseDtoType = {
  Profile: "profile",
  Company: "company",
} as const;
export type LinkedInProfileReactionResponseDtoType = OpenEnum<
  typeof LinkedInProfileReactionResponseDtoType
>;

export type Actor = {
  id?: string | null | undefined;
  type?: LinkedInProfileReactionResponseDtoType | null | undefined;
  name?: string | null | undefined;
  linkedinUrl?: string | null | undefined;
  position?: string | null | undefined;
  universalName?: string | null | undefined;
  pictureUrl?: string | null | undefined;
};

export type LinkedInProfileReactionResponseDto = {
  id?: string | null | undefined;
  profileUrl: string;
  profileUsername: string;
  reactionType: string;
  reactedAt?: string | null | undefined;
  sourceUrl?: string | null | undefined;
  post: LinkedInProfileActivityPostResponseDto;
  actor?: Actor | null | undefined;
};

/** @internal */
export const LinkedInProfileReactionResponseDtoType$inboundSchema:
  z.ZodMiniType<LinkedInProfileReactionResponseDtoType, unknown> = openEnums
    .inboundSchema(LinkedInProfileReactionResponseDtoType);

/** @internal */
export const Actor$inboundSchema: z.ZodMiniType<Actor, unknown> = z.object({
  id: z.optional(z.nullable(types.string())),
  type: z.optional(
    z.nullable(LinkedInProfileReactionResponseDtoType$inboundSchema),
  ),
  name: z.optional(z.nullable(types.string())),
  linkedinUrl: z.optional(z.nullable(types.string())),
  position: z.optional(z.nullable(types.string())),
  universalName: z.optional(z.nullable(types.string())),
  pictureUrl: z.optional(z.nullable(types.string())),
});

export function actorFromJSON(
  jsonString: string,
): SafeParseResult<Actor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Actor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Actor' from JSON`,
  );
}

/** @internal */
export const LinkedInProfileReactionResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInProfileReactionResponseDto,
  unknown
> = z.object({
  id: z.optional(z.nullable(types.string())),
  profileUrl: types.string(),
  profileUsername: types.string(),
  reactionType: types.string(),
  reactedAt: z.optional(z.nullable(types.string())),
  sourceUrl: z.optional(z.nullable(types.string())),
  post: LinkedInProfileActivityPostResponseDto$inboundSchema,
  actor: z.optional(z.nullable(z.lazy(() => Actor$inboundSchema))),
});

export function linkedInProfileReactionResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInProfileReactionResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LinkedInProfileReactionResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInProfileReactionResponseDto' from JSON`,
  );
}
