/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInRepostedByResponseDto = {
  "name": string;
  "publicIdentifier": string;
};
export type LinkedInRepostedByResponseDto$Outbound = LinkedInRepostedByResponseDto;

export const LinkedInRepostedByResponseDto$inboundSchema = (z.object({
  "name": z.string(),
  "publicIdentifier": z.string(),
})) as z.ZodType<LinkedInRepostedByResponseDto>;
export const LinkedInRepostedByResponseDto$outboundSchema = (z.object({
  "name": z.string(),
  "publicIdentifier": z.string(),
})) as z.ZodType<LinkedInRepostedByResponseDto$Outbound>;

export function linkedInRepostedByResponseDtoFromJSON(jsonString: string): LinkedInRepostedByResponseDto {
  return LinkedInRepostedByResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInRepostedByResponseDto;
}

export function linkedInRepostedByResponseDtoToJSON(value: LinkedInRepostedByResponseDto): string {
  return JSON.stringify(LinkedInRepostedByResponseDto$outboundSchema.parse(value));
}
