/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type LinkedInFinderResponseDto = {
  linkedinUrl?: string | null | undefined;
  domain?: string | null | undefined;
  companyName?: string | null | undefined;
};

/** @internal */
export const LinkedInFinderResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInFinderResponseDto,
  unknown
> = z.pipe(
  z.object({
    linkedin_url: z.optional(z.nullable(types.string())),
    domain: z.optional(z.nullable(types.string())),
    company_name: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "linkedin_url": "linkedinUrl",
      "company_name": "companyName",
    });
  }),
);

export function linkedInFinderResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInFinderResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInFinderResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInFinderResponseDto' from JSON`,
  );
}
