/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const LinkedInKeywordPostsConfigBodyDtoSortBy = {
  Relevance: "relevance",
  Recent: "recent",
} as const;
export type LinkedInKeywordPostsConfigBodyDtoSortBy = ClosedEnum<
  typeof LinkedInKeywordPostsConfigBodyDtoSortBy
>;

export const DateFilter = {
  Past24h: "past-24h",
  PastWeek: "past-week",
  PastMonth: "past-month",
} as const;
export type DateFilter = ClosedEnum<typeof DateFilter>;

/**
 * Use exact to search the keyword as a quoted phrase, or broad to let LinkedIn match related terms.
 */
export const LinkedInKeywordPostsConfigBodyDtoMatchMode = {
  Exact: "exact",
  Broad: "broad",
} as const;
/**
 * Use exact to search the keyword as a quoted phrase, or broad to let LinkedIn match related terms.
 */
export type LinkedInKeywordPostsConfigBodyDtoMatchMode = ClosedEnum<
  typeof LinkedInKeywordPostsConfigBodyDtoMatchMode
>;

export type LinkedInKeywordPostsConfigBodyDto = {
  limit?: number | undefined;
  sortBy?: LinkedInKeywordPostsConfigBodyDtoSortBy | undefined;
  dateFilter?: DateFilter | undefined;
  /**
   * Use exact to search the keyword as a quoted phrase, or broad to let LinkedIn match related terms.
   */
  matchMode?: LinkedInKeywordPostsConfigBodyDtoMatchMode | undefined;
};

/** @internal */
export const LinkedInKeywordPostsConfigBodyDtoSortBy$outboundSchema:
  z.ZodMiniEnum<typeof LinkedInKeywordPostsConfigBodyDtoSortBy> = z.enum(
    LinkedInKeywordPostsConfigBodyDtoSortBy,
  );

/** @internal */
export const DateFilter$outboundSchema: z.ZodMiniEnum<typeof DateFilter> = z
  .enum(DateFilter);

/** @internal */
export const LinkedInKeywordPostsConfigBodyDtoMatchMode$outboundSchema:
  z.ZodMiniEnum<typeof LinkedInKeywordPostsConfigBodyDtoMatchMode> = z.enum(
    LinkedInKeywordPostsConfigBodyDtoMatchMode,
  );

/** @internal */
export type LinkedInKeywordPostsConfigBodyDto$Outbound = {
  limit?: number | undefined;
  sortBy?: string | undefined;
  dateFilter?: string | undefined;
  matchMode: string;
};

/** @internal */
export const LinkedInKeywordPostsConfigBodyDto$outboundSchema: z.ZodMiniType<
  LinkedInKeywordPostsConfigBodyDto$Outbound,
  LinkedInKeywordPostsConfigBodyDto
> = z.object({
  limit: z.optional(z.number()),
  sortBy: z.optional(LinkedInKeywordPostsConfigBodyDtoSortBy$outboundSchema),
  dateFilter: z.optional(DateFilter$outboundSchema),
  matchMode: z._default(
    LinkedInKeywordPostsConfigBodyDtoMatchMode$outboundSchema,
    "exact",
  ),
});

export function linkedInKeywordPostsConfigBodyDtoToJSON(
  linkedInKeywordPostsConfigBodyDto: LinkedInKeywordPostsConfigBodyDto,
): string {
  return JSON.stringify(
    LinkedInKeywordPostsConfigBodyDto$outboundSchema.parse(
      linkedInKeywordPostsConfigBodyDto,
    ),
  );
}
