/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInAuthorResponseDto = {
  "name"?: string | null;
  "headline"?: string | null;
  "linkedinUrl"?: string | null;
  "avatar"?: string | null;
  "publicIdentifier"?: string | null;
};
export type LinkedInAuthorResponseDto$Outbound = LinkedInAuthorResponseDto;

export const LinkedInAuthorResponseDto$inboundSchema = (z.object({
  "name": z.optional(z.nullable(z.string())),
  "headline": z.optional(z.nullable(z.string())),
  "linkedinUrl": z.optional(z.nullable(z.string())),
  "avatar": z.optional(z.nullable(z.string())),
  "publicIdentifier": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInAuthorResponseDto>;
export const LinkedInAuthorResponseDto$outboundSchema = (z.object({
  "name": z.optional(z.nullable(z.string())),
  "headline": z.optional(z.nullable(z.string())),
  "linkedinUrl": z.optional(z.nullable(z.string())),
  "avatar": z.optional(z.nullable(z.string())),
  "publicIdentifier": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInAuthorResponseDto$Outbound>;

export function linkedInAuthorResponseDtoFromJSON(jsonString: string): LinkedInAuthorResponseDto {
  return LinkedInAuthorResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInAuthorResponseDto;
}

export function linkedInAuthorResponseDtoToJSON(value: LinkedInAuthorResponseDto): string {
  return JSON.stringify(LinkedInAuthorResponseDto$outboundSchema.parse(value));
}
