/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const LinkedInCommentActorResponseDtoType = {
  Profile: "profile",
  Company: "company",
} as const;
export type LinkedInCommentActorResponseDtoType = OpenEnum<
  typeof LinkedInCommentActorResponseDtoType
>;

export type LinkedInCommentActorResponseDto = {
  id: string | null;
  type: LinkedInCommentActorResponseDtoType;
  name: string;
  linkedinUrl: string;
  position: string;
  universalName?: string | null | undefined;
  pictureUrl?: string | null | undefined;
};

/** @internal */
export const LinkedInCommentActorResponseDtoType$inboundSchema: z.ZodMiniType<
  LinkedInCommentActorResponseDtoType,
  unknown
> = openEnums.inboundSchema(LinkedInCommentActorResponseDtoType);

/** @internal */
export const LinkedInCommentActorResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInCommentActorResponseDto,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  type: LinkedInCommentActorResponseDtoType$inboundSchema,
  name: types.string(),
  linkedinUrl: types.string(),
  position: types.string(),
  universalName: z.optional(z.nullable(types.string())),
  pictureUrl: z.optional(z.nullable(types.string())),
});

export function linkedInCommentActorResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInCommentActorResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInCommentActorResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInCommentActorResponseDto' from JSON`,
  );
}
