/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInCommentEngagementResponseDto = {
  "likes": number;
  "comments": number;
  "shares": number;
};
export type LinkedInCommentEngagementResponseDto$Outbound = LinkedInCommentEngagementResponseDto;

export const LinkedInCommentEngagementResponseDto$inboundSchema = (z.object({
  "likes": z.number(),
  "comments": z.number(),
  "shares": z.number(),
})) as z.ZodType<LinkedInCommentEngagementResponseDto>;
export const LinkedInCommentEngagementResponseDto$outboundSchema = (z.object({
  "likes": z.number(),
  "comments": z.number(),
  "shares": z.number(),
})) as z.ZodType<LinkedInCommentEngagementResponseDto$Outbound>;

export function linkedInCommentEngagementResponseDtoFromJSON(jsonString: string): LinkedInCommentEngagementResponseDto {
  return LinkedInCommentEngagementResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInCommentEngagementResponseDto;
}

export function linkedInCommentEngagementResponseDtoToJSON(value: LinkedInCommentEngagementResponseDto): string {
  return JSON.stringify(LinkedInCommentEngagementResponseDto$outboundSchema.parse(value));
}
