/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type RepostedBy = {
  name: string;
  publicIdentifier: string;
};

export type LinkedInPostResponseDto = {
  activityId: string;
  postUrl?: string | null | undefined;
  text: string;
  postedAt?: string | null | undefined;
  authorName?: string | null | undefined;
  authorHeadline?: string | null | undefined;
  authorProfileUrl?: string | null | undefined;
  authorProfileUsername?: string | null | undefined;
  totalReactions?: number | null | undefined;
  commentsCount?: number | null | undefined;
  repostsCount?: number | null | undefined;
  isReshare?: boolean | null | undefined;
  repostedBy?: RepostedBy | null | undefined;
  contentType?: string | null | undefined;
  contentData?: { [k: string]: any } | undefined;
  hashtags?: Array<string> | null | undefined;
};

/** @internal */
export const RepostedBy$inboundSchema: z.ZodMiniType<RepostedBy, unknown> = z
  .object({
    name: types.string(),
    publicIdentifier: types.string(),
  });

export function repostedByFromJSON(
  jsonString: string,
): SafeParseResult<RepostedBy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RepostedBy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RepostedBy' from JSON`,
  );
}

/** @internal */
export const LinkedInPostResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInPostResponseDto,
  unknown
> = z.object({
  activityId: types.string(),
  postUrl: z.optional(z.nullable(types.string())),
  text: types.string(),
  postedAt: z.optional(z.nullable(types.string())),
  authorName: z.optional(z.nullable(types.string())),
  authorHeadline: z.optional(z.nullable(types.string())),
  authorProfileUrl: z.optional(z.nullable(types.string())),
  authorProfileUsername: z.optional(z.nullable(types.string())),
  totalReactions: z.optional(z.nullable(types.number())),
  commentsCount: z.optional(z.nullable(types.number())),
  repostsCount: z.optional(z.nullable(types.number())),
  isReshare: z.optional(z.nullable(types.boolean())),
  repostedBy: z.optional(z.nullable(z.lazy(() => RepostedBy$inboundSchema))),
  contentType: z.optional(z.nullable(types.string())),
  contentData: types.optional(z.record(z.string(), z.any())),
  hashtags: z.optional(z.nullable(z.array(types.string()))),
});

export function linkedInPostResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInPostResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInPostResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInPostResponseDto' from JSON`,
  );
}
