/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInCommentActorResponseDto = {
  "id": string | null;
  "type": "profile" | "company";
  "name": string;
  "linkedinUrl": string;
  "position": string;
  "universalName"?: string | null;
  "pictureUrl"?: string | null;
};
export type LinkedInCommentActorResponseDto$Outbound = LinkedInCommentActorResponseDto;

export const LinkedInCommentActorResponseDto$inboundSchema = (z.object({
  "id": z.nullable(z.string()),
  "type": z.enum(["profile","company"]),
  "name": z.string(),
  "linkedinUrl": z.string(),
  "position": z.string(),
  "universalName": z.optional(z.nullable(z.string())),
  "pictureUrl": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInCommentActorResponseDto>;
export const LinkedInCommentActorResponseDto$outboundSchema = (z.object({
  "id": z.nullable(z.string()),
  "type": z.enum(["profile","company"]),
  "name": z.string(),
  "linkedinUrl": z.string(),
  "position": z.string(),
  "universalName": z.optional(z.nullable(z.string())),
  "pictureUrl": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInCommentActorResponseDto$Outbound>;

export function linkedInCommentActorResponseDtoFromJSON(jsonString: string): LinkedInCommentActorResponseDto {
  return LinkedInCommentActorResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInCommentActorResponseDto;
}

export function linkedInCommentActorResponseDtoToJSON(value: LinkedInCommentActorResponseDto): string {
  return JSON.stringify(LinkedInCommentActorResponseDto$outboundSchema.parse(value));
}
