/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInPostResponseDto } from "./linked-in-post-response-dto.js";
import { LinkedInPostResponseDto$inboundSchema, LinkedInPostResponseDto$outboundSchema } from "./linked-in-post-response-dto.js";

export type LinkedInCompanyPostsResponseDto = {
  "companySlug": string;
  "posts": LinkedInPostResponseDto[];
  "description"?: string | null;
};
export type LinkedInCompanyPostsResponseDto$Outbound = LinkedInCompanyPostsResponseDto;

export const LinkedInCompanyPostsResponseDto$inboundSchema = (z.object({
  "companySlug": z.string(),
  "posts": z.array(z.lazy(() => LinkedInPostResponseDto$inboundSchema)),
  "description": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInCompanyPostsResponseDto>;
export const LinkedInCompanyPostsResponseDto$outboundSchema = (z.object({
  "companySlug": z.string(),
  "posts": z.array(z.lazy(() => LinkedInPostResponseDto$outboundSchema)),
  "description": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInCompanyPostsResponseDto$Outbound>;

export function linkedInCompanyPostsResponseDtoFromJSON(jsonString: string): LinkedInCompanyPostsResponseDto {
  return LinkedInCompanyPostsResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInCompanyPostsResponseDto;
}

export function linkedInCompanyPostsResponseDtoToJSON(value: LinkedInCompanyPostsResponseDto): string {
  return JSON.stringify(LinkedInCompanyPostsResponseDto$outboundSchema.parse(value));
}
