/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInCompanyResponseDto = {
  "identifier": string;
  "name"?: string | null;
  "description"?: string | null;
  "website"?: string | null;
  "industry"?: string | null;
  "company_size"?: string | null;
  "headquarters"?: string | null;
  "founded"?: number | null;
  "specialties"?: string[] | null;
  "logo_url"?: string | null;
  "follower_count"?: number | null;
  "employee_count"?: number | null;
  "linkedin_url"?: string | null;
};
export type LinkedInCompanyResponseDto$Outbound = LinkedInCompanyResponseDto;

export const LinkedInCompanyResponseDto$inboundSchema = (z.object({
  "identifier": z.string(),
  "name": z.optional(z.nullable(z.string())),
  "description": z.optional(z.nullable(z.string())),
  "website": z.optional(z.nullable(z.string())),
  "industry": z.optional(z.nullable(z.string())),
  "company_size": z.optional(z.nullable(z.string())),
  "headquarters": z.optional(z.nullable(z.string())),
  "founded": z.optional(z.nullable(z.number())),
  "specialties": z.optional(z.nullable(z.array(z.string()))),
  "logo_url": z.optional(z.nullable(z.string())),
  "follower_count": z.optional(z.nullable(z.number())),
  "employee_count": z.optional(z.nullable(z.number())),
  "linkedin_url": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInCompanyResponseDto>;
export const LinkedInCompanyResponseDto$outboundSchema = (z.object({
  "identifier": z.string(),
  "name": z.optional(z.nullable(z.string())),
  "description": z.optional(z.nullable(z.string())),
  "website": z.optional(z.nullable(z.string())),
  "industry": z.optional(z.nullable(z.string())),
  "company_size": z.optional(z.nullable(z.string())),
  "headquarters": z.optional(z.nullable(z.string())),
  "founded": z.optional(z.nullable(z.number())),
  "specialties": z.optional(z.nullable(z.array(z.string()))),
  "logo_url": z.optional(z.nullable(z.string())),
  "follower_count": z.optional(z.nullable(z.number())),
  "employee_count": z.optional(z.nullable(z.number())),
  "linkedin_url": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInCompanyResponseDto$Outbound>;

export function linkedInCompanyResponseDtoFromJSON(jsonString: string): LinkedInCompanyResponseDto {
  return LinkedInCompanyResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInCompanyResponseDto;
}

export function linkedInCompanyResponseDtoToJSON(value: LinkedInCompanyResponseDto): string {
  return JSON.stringify(LinkedInCompanyResponseDto$outboundSchema.parse(value));
}
