/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInCommentActorResponseDto } from "./linked-in-comment-actor-response-dto.js";
import { LinkedInCommentActorResponseDto$inboundSchema, LinkedInCommentActorResponseDto$outboundSchema } from "./linked-in-comment-actor-response-dto.js";
import type { LinkedInCommentEngagementResponseDto } from "./linked-in-comment-engagement-response-dto.js";
import { LinkedInCommentEngagementResponseDto$inboundSchema, LinkedInCommentEngagementResponseDto$outboundSchema } from "./linked-in-comment-engagement-response-dto.js";

export type LinkedInPostCommentResponseDto = {
  "id": string;
  "commentary": string;
  "linkedinUrl": string;
  "createdAt": string;
  "createdAtTimestamp": number;
  "engagement": LinkedInCommentEngagementResponseDto;
  "postId": string;
  "pinned": boolean;
  "edited": boolean;
  "actor": LinkedInCommentActorResponseDto;
  "replies"?: LinkedInPostCommentResponseDto[] | null;
};
export type LinkedInPostCommentResponseDto$Outbound = LinkedInPostCommentResponseDto;

export const LinkedInPostCommentResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "commentary": z.string(),
  "linkedinUrl": z.string(),
  "createdAt": z.string(),
  "createdAtTimestamp": z.number(),
  "engagement": z.lazy(() => LinkedInCommentEngagementResponseDto$inboundSchema),
  "postId": z.string(),
  "pinned": z.boolean(),
  "edited": z.boolean(),
  "actor": z.lazy(() => LinkedInCommentActorResponseDto$inboundSchema),
  "replies": z.optional(z.nullable(z.array(z.lazy(() => LinkedInPostCommentResponseDto$inboundSchema)))),
})) as z.ZodType<LinkedInPostCommentResponseDto>;
export const LinkedInPostCommentResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "commentary": z.string(),
  "linkedinUrl": z.string(),
  "createdAt": z.string(),
  "createdAtTimestamp": z.number(),
  "engagement": z.lazy(() => LinkedInCommentEngagementResponseDto$outboundSchema),
  "postId": z.string(),
  "pinned": z.boolean(),
  "edited": z.boolean(),
  "actor": z.lazy(() => LinkedInCommentActorResponseDto$outboundSchema),
  "replies": z.optional(z.nullable(z.array(z.lazy(() => LinkedInPostCommentResponseDto$outboundSchema)))),
})) as z.ZodType<LinkedInPostCommentResponseDto$Outbound>;

export function linkedInPostCommentResponseDtoFromJSON(jsonString: string): LinkedInPostCommentResponseDto {
  return LinkedInPostCommentResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInPostCommentResponseDto;
}

export function linkedInPostCommentResponseDtoToJSON(value: LinkedInPostCommentResponseDto): string {
  return JSON.stringify(LinkedInPostCommentResponseDto$outboundSchema.parse(value));
}
