/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInAuthorResponseDto } from "./linked-in-author-response-dto.js";
import { LinkedInAuthorResponseDto$inboundSchema, LinkedInAuthorResponseDto$outboundSchema } from "./linked-in-author-response-dto.js";
import type { LinkedInPostResponseDto } from "./linked-in-post-response-dto.js";
import { LinkedInPostResponseDto$inboundSchema, LinkedInPostResponseDto$outboundSchema } from "./linked-in-post-response-dto.js";

export type LinkedInProfilePostsResponseDto = {
  "username": string;
  "posts": LinkedInPostResponseDto[];
  "bio"?: string | null;
  "author"?: (LinkedInAuthorResponseDto);
};
export type LinkedInProfilePostsResponseDto$Outbound = LinkedInProfilePostsResponseDto;

export const LinkedInProfilePostsResponseDto$inboundSchema = (z.object({
  "username": z.string(),
  "posts": z.array(z.lazy(() => LinkedInPostResponseDto$inboundSchema)),
  "bio": z.optional(z.nullable(z.string())),
  "author": z.optional(z.lazy(() => LinkedInAuthorResponseDto$inboundSchema)),
})) as z.ZodType<LinkedInProfilePostsResponseDto>;
export const LinkedInProfilePostsResponseDto$outboundSchema = (z.object({
  "username": z.string(),
  "posts": z.array(z.lazy(() => LinkedInPostResponseDto$outboundSchema)),
  "bio": z.optional(z.nullable(z.string())),
  "author": z.optional(z.lazy(() => LinkedInAuthorResponseDto$outboundSchema)),
})) as z.ZodType<LinkedInProfilePostsResponseDto$Outbound>;

export function linkedInProfilePostsResponseDtoFromJSON(jsonString: string): LinkedInProfilePostsResponseDto {
  return LinkedInProfilePostsResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInProfilePostsResponseDto;
}

export function linkedInProfilePostsResponseDtoToJSON(value: LinkedInProfilePostsResponseDto): string {
  return JSON.stringify(LinkedInProfilePostsResponseDto$outboundSchema.parse(value));
}
