/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInProfileActivityActorResponseDto = {
  "id"?: string | null;
  "type"?: "profile" | "company" | null;
  "name"?: string | null;
  "linkedinUrl"?: string | null;
  "position"?: string | null;
  "universalName"?: string | null;
  "pictureUrl"?: string | null;
};
export type LinkedInProfileActivityActorResponseDto$Outbound = LinkedInProfileActivityActorResponseDto;

export const LinkedInProfileActivityActorResponseDto$inboundSchema = (z.object({
  "id": z.optional(z.nullable(z.string())),
  "type": z.optional(z.nullable(z.enum(["profile","company"]))),
  "name": z.optional(z.nullable(z.string())),
  "linkedinUrl": z.optional(z.nullable(z.string())),
  "position": z.optional(z.nullable(z.string())),
  "universalName": z.optional(z.nullable(z.string())),
  "pictureUrl": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInProfileActivityActorResponseDto>;
export const LinkedInProfileActivityActorResponseDto$outboundSchema = (z.object({
  "id": z.optional(z.nullable(z.string())),
  "type": z.optional(z.nullable(z.enum(["profile","company"]))),
  "name": z.optional(z.nullable(z.string())),
  "linkedinUrl": z.optional(z.nullable(z.string())),
  "position": z.optional(z.nullable(z.string())),
  "universalName": z.optional(z.nullable(z.string())),
  "pictureUrl": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInProfileActivityActorResponseDto$Outbound>;

export function linkedInProfileActivityActorResponseDtoFromJSON(jsonString: string): LinkedInProfileActivityActorResponseDto {
  return LinkedInProfileActivityActorResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInProfileActivityActorResponseDto;
}

export function linkedInProfileActivityActorResponseDtoToJSON(value: LinkedInProfileActivityActorResponseDto): string {
  return JSON.stringify(LinkedInProfileActivityActorResponseDto$outboundSchema.parse(value));
}
