/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  LinkedInCommentActorResponseDto,
  LinkedInCommentActorResponseDto$inboundSchema,
} from "./linked-in-comment-actor-response-dto.js";
import {
  LinkedInCommentEngagementResponseDto,
  LinkedInCommentEngagementResponseDto$inboundSchema,
} from "./linked-in-comment-engagement-response-dto.js";

export type LinkedInPostCommentResponseDto = {
  id: string;
  commentary: string;
  linkedinUrl: string;
  createdAt: string;
  createdAtTimestamp: number;
  engagement: LinkedInCommentEngagementResponseDto;
  postId: string;
  pinned: boolean;
  edited: boolean;
  actor: LinkedInCommentActorResponseDto;
  replies?: Array<LinkedInPostCommentResponseDto> | null | undefined;
};

/** @internal */
export const LinkedInPostCommentResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInPostCommentResponseDto,
  unknown
> = z.object({
  id: types.string(),
  commentary: types.string(),
  linkedinUrl: types.string(),
  createdAt: types.string(),
  createdAtTimestamp: types.number(),
  engagement: LinkedInCommentEngagementResponseDto$inboundSchema,
  postId: types.string(),
  pinned: types.boolean(),
  edited: types.boolean(),
  actor: LinkedInCommentActorResponseDto$inboundSchema,
  replies: z.optional(
    z.nullable(z.array(z.lazy(() =>
      LinkedInPostCommentResponseDto$inboundSchema
    ))),
  ),
});

export function linkedInPostCommentResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInPostCommentResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInPostCommentResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInPostCommentResponseDto' from JSON`,
  );
}
