/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInReactionActorResponseDto = {
  "id": string;
  "name": string;
  "linkedinUrl": string;
  "position": string;
  "pictureUrl"?: string | null;
};
export type LinkedInReactionActorResponseDto$Outbound = LinkedInReactionActorResponseDto;

export const LinkedInReactionActorResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "name": z.string(),
  "linkedinUrl": z.string(),
  "position": z.string(),
  "pictureUrl": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInReactionActorResponseDto>;
export const LinkedInReactionActorResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "name": z.string(),
  "linkedinUrl": z.string(),
  "position": z.string(),
  "pictureUrl": z.optional(z.nullable(z.string())),
})) as z.ZodType<LinkedInReactionActorResponseDto$Outbound>;

export function linkedInReactionActorResponseDtoFromJSON(jsonString: string): LinkedInReactionActorResponseDto {
  return LinkedInReactionActorResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInReactionActorResponseDto;
}

export function linkedInReactionActorResponseDtoToJSON(value: LinkedInReactionActorResponseDto): string {
  return JSON.stringify(LinkedInReactionActorResponseDto$outboundSchema.parse(value));
}
