/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type LinkedInKeywordPostsConfigBodyDto = {
  "limit"?: number;
  "sortBy"?: "relevance" | "recent";
  "dateFilter"?: "past-24h" | "past-week" | "past-month";
  "matchMode"?: "exact" | "broad";
};
export type LinkedInKeywordPostsConfigBodyDto$Outbound = LinkedInKeywordPostsConfigBodyDto;

export const LinkedInKeywordPostsConfigBodyDto$inboundSchema = (z.object({
  "limit": z.optional(z.number()),
  "sortBy": z.optional(z.enum(["relevance","recent"])),
  "dateFilter": z.optional(z.enum(["past-24h","past-week","past-month"])),
  "matchMode": z.optional(z.enum(["exact","broad"])),
})) as z.ZodType<LinkedInKeywordPostsConfigBodyDto>;
export const LinkedInKeywordPostsConfigBodyDto$outboundSchema = (z.object({
  "limit": z.optional(z.number()),
  "sortBy": z.optional(z.enum(["relevance","recent"])),
  "dateFilter": z.optional(z.enum(["past-24h","past-week","past-month"])),
  "matchMode": z.optional(z.enum(["exact","broad"])),
})) as z.ZodType<LinkedInKeywordPostsConfigBodyDto$Outbound>;

export function linkedInKeywordPostsConfigBodyDtoFromJSON(jsonString: string): LinkedInKeywordPostsConfigBodyDto {
  return LinkedInKeywordPostsConfigBodyDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInKeywordPostsConfigBodyDto;
}

export function linkedInKeywordPostsConfigBodyDtoToJSON(value: LinkedInKeywordPostsConfigBodyDto): string {
  return JSON.stringify(LinkedInKeywordPostsConfigBodyDto$outboundSchema.parse(value));
}
