/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  LinkedInProfileActivityPostResponseDto,
  LinkedInProfileActivityPostResponseDto$inboundSchema,
} from "./linked-in-profile-activity-post-response-dto.js";

export const LinkedInProfileCommentResponseDtoType = {
  Profile: "profile",
  Company: "company",
} as const;
export type LinkedInProfileCommentResponseDtoType = OpenEnum<
  typeof LinkedInProfileCommentResponseDtoType
>;

export type LinkedInProfileCommentResponseDtoActor = {
  id?: string | null | undefined;
  type?: LinkedInProfileCommentResponseDtoType | null | undefined;
  name?: string | null | undefined;
  linkedinUrl?: string | null | undefined;
  position?: string | null | undefined;
  universalName?: string | null | undefined;
  pictureUrl?: string | null | undefined;
};

export type LinkedInProfileCommentResponseDto = {
  id?: string | null | undefined;
  profileUrl: string;
  profileUsername: string;
  commentText: string;
  commentedAt?: string | null | undefined;
  sourceUrl?: string | null | undefined;
  post: LinkedInProfileActivityPostResponseDto;
  actor?: LinkedInProfileCommentResponseDtoActor | null | undefined;
};

/** @internal */
export const LinkedInProfileCommentResponseDtoType$inboundSchema: z.ZodMiniType<
  LinkedInProfileCommentResponseDtoType,
  unknown
> = openEnums.inboundSchema(LinkedInProfileCommentResponseDtoType);

/** @internal */
export const LinkedInProfileCommentResponseDtoActor$inboundSchema:
  z.ZodMiniType<LinkedInProfileCommentResponseDtoActor, unknown> = z.object({
    id: z.optional(z.nullable(types.string())),
    type: z.optional(
      z.nullable(LinkedInProfileCommentResponseDtoType$inboundSchema),
    ),
    name: z.optional(z.nullable(types.string())),
    linkedinUrl: z.optional(z.nullable(types.string())),
    position: z.optional(z.nullable(types.string())),
    universalName: z.optional(z.nullable(types.string())),
    pictureUrl: z.optional(z.nullable(types.string())),
  });

export function linkedInProfileCommentResponseDtoActorFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInProfileCommentResponseDtoActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LinkedInProfileCommentResponseDtoActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInProfileCommentResponseDtoActor' from JSON`,
  );
}

/** @internal */
export const LinkedInProfileCommentResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInProfileCommentResponseDto,
  unknown
> = z.object({
  id: z.optional(z.nullable(types.string())),
  profileUrl: types.string(),
  profileUsername: types.string(),
  commentText: types.string(),
  commentedAt: z.optional(z.nullable(types.string())),
  sourceUrl: z.optional(z.nullable(types.string())),
  post: LinkedInProfileActivityPostResponseDto$inboundSchema,
  actor: z.optional(
    z.nullable(
      z.lazy(() => LinkedInProfileCommentResponseDtoActor$inboundSchema),
    ),
  ),
});

export function linkedInProfileCommentResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInProfileCommentResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInProfileCommentResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInProfileCommentResponseDto' from JSON`,
  );
}
