/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type LinkedInCommentEngagementResponseDto = {
  likes: number;
  comments: number;
  shares: number;
};

/** @internal */
export const LinkedInCommentEngagementResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInCommentEngagementResponseDto,
  unknown
> = z.object({
  likes: types.number(),
  comments: types.number(),
  shares: types.number(),
});

export function linkedInCommentEngagementResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInCommentEngagementResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LinkedInCommentEngagementResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInCommentEngagementResponseDto' from JSON`,
  );
}
