/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type LinkedInProfileActivityPostResponseDto = {
  postId?: string | null | undefined;
  postUrl?: string | null | undefined;
  text?: string | null | undefined;
  authorName?: string | null | undefined;
  authorProfileUrl?: string | null | undefined;
  authorCompanyUrl?: string | null | undefined;
  postedAt?: string | null | undefined;
  reactionCount?: number | null | undefined;
  commentCount?: number | null | undefined;
  repostCount?: number | null | undefined;
};

/** @internal */
export const LinkedInProfileActivityPostResponseDto$inboundSchema:
  z.ZodMiniType<LinkedInProfileActivityPostResponseDto, unknown> = z.object({
    postId: z.optional(z.nullable(types.string())),
    postUrl: z.optional(z.nullable(types.string())),
    text: z.optional(z.nullable(types.string())),
    authorName: z.optional(z.nullable(types.string())),
    authorProfileUrl: z.optional(z.nullable(types.string())),
    authorCompanyUrl: z.optional(z.nullable(types.string())),
    postedAt: z.optional(z.nullable(types.string())),
    reactionCount: z.optional(z.nullable(types.number())),
    commentCount: z.optional(z.nullable(types.number())),
    repostCount: z.optional(z.nullable(types.number())),
  });

export function linkedInProfileActivityPostResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInProfileActivityPostResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LinkedInProfileActivityPostResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInProfileActivityPostResponseDto' from JSON`,
  );
}
