/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type LinkedInReactionActorResponseDto = {
  id: string;
  name: string;
  linkedinUrl: string;
  position: string;
  pictureUrl?: string | null | undefined;
};

/** @internal */
export const LinkedInReactionActorResponseDto$inboundSchema: z.ZodMiniType<
  LinkedInReactionActorResponseDto,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  linkedinUrl: types.string(),
  position: types.string(),
  pictureUrl: z.optional(z.nullable(types.string())),
});

export function linkedInReactionActorResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInReactionActorResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInReactionActorResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInReactionActorResponseDto' from JSON`,
  );
}
