/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInProfileActivityActorResponseDto } from "./linked-in-profile-activity-actor-response-dto.js";
import { LinkedInProfileActivityActorResponseDto$inboundSchema, LinkedInProfileActivityActorResponseDto$outboundSchema } from "./linked-in-profile-activity-actor-response-dto.js";
import type { LinkedInProfileActivityPostResponseDto } from "./linked-in-profile-activity-post-response-dto.js";
import { LinkedInProfileActivityPostResponseDto$inboundSchema, LinkedInProfileActivityPostResponseDto$outboundSchema } from "./linked-in-profile-activity-post-response-dto.js";

export type LinkedInProfileCommentResponseDto = {
  "id"?: string | null;
  "profileUrl": string;
  "profileUsername": string;
  "commentText": string;
  "commentedAt"?: string | null;
  "sourceUrl"?: string | null;
  "post": LinkedInProfileActivityPostResponseDto;
  "actor"?: (LinkedInProfileActivityActorResponseDto);
};
export type LinkedInProfileCommentResponseDto$Outbound = LinkedInProfileCommentResponseDto;

export const LinkedInProfileCommentResponseDto$inboundSchema = (z.object({
  "id": z.optional(z.nullable(z.string())),
  "profileUrl": z.string(),
  "profileUsername": z.string(),
  "commentText": z.string(),
  "commentedAt": z.optional(z.nullable(z.string())),
  "sourceUrl": z.optional(z.nullable(z.string())),
  "post": z.lazy(() => LinkedInProfileActivityPostResponseDto$inboundSchema),
  "actor": z.optional(z.lazy(() => LinkedInProfileActivityActorResponseDto$inboundSchema)),
})) as z.ZodType<LinkedInProfileCommentResponseDto>;
export const LinkedInProfileCommentResponseDto$outboundSchema = (z.object({
  "id": z.optional(z.nullable(z.string())),
  "profileUrl": z.string(),
  "profileUsername": z.string(),
  "commentText": z.string(),
  "commentedAt": z.optional(z.nullable(z.string())),
  "sourceUrl": z.optional(z.nullable(z.string())),
  "post": z.lazy(() => LinkedInProfileActivityPostResponseDto$outboundSchema),
  "actor": z.optional(z.lazy(() => LinkedInProfileActivityActorResponseDto$outboundSchema)),
})) as z.ZodType<LinkedInProfileCommentResponseDto$Outbound>;

export function linkedInProfileCommentResponseDtoFromJSON(jsonString: string): LinkedInProfileCommentResponseDto {
  return LinkedInProfileCommentResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as LinkedInProfileCommentResponseDto;
}

export function linkedInProfileCommentResponseDtoToJSON(value: LinkedInProfileCommentResponseDto): string {
  return JSON.stringify(LinkedInProfileCommentResponseDto$outboundSchema.parse(value));
}
