/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInCompanyPostsResponseDto } from "./linked-in-company-posts-response-dto.js";
import { LinkedInCompanyPostsResponseDto$inboundSchema, LinkedInCompanyPostsResponseDto$outboundSchema } from "./linked-in-company-posts-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListLinkedInCompanyPostsResponse = {
  "data": LinkedInCompanyPostsResponseDto;
  "meta": PublicResponseMetaDto;
};
export type ListLinkedInCompanyPostsResponse$Outbound = ListLinkedInCompanyPostsResponse;

export const ListLinkedInCompanyPostsResponse$inboundSchema = (z.object({
  "data": z.lazy(() => LinkedInCompanyPostsResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListLinkedInCompanyPostsResponse>;
export const ListLinkedInCompanyPostsResponse$outboundSchema = (z.object({
  "data": z.lazy(() => LinkedInCompanyPostsResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListLinkedInCompanyPostsResponse$Outbound>;

export function listLinkedInCompanyPostsResponseFromJSON(jsonString: string): ListLinkedInCompanyPostsResponse {
  return ListLinkedInCompanyPostsResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListLinkedInCompanyPostsResponse;
}

export function listLinkedInCompanyPostsResponseToJSON(value: ListLinkedInCompanyPostsResponse): string {
  return JSON.stringify(ListLinkedInCompanyPostsResponse$outboundSchema.parse(value));
}
