/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInProfileCommentResponseDto } from "./linked-in-profile-comment-response-dto.js";
import { LinkedInProfileCommentResponseDto$inboundSchema, LinkedInProfileCommentResponseDto$outboundSchema } from "./linked-in-profile-comment-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListLinkedInProfileCommentsResponse = {
  "data": LinkedInProfileCommentResponseDto[];
  "meta": PublicResponseMetaDto;
};
export type ListLinkedInProfileCommentsResponse$Outbound = ListLinkedInProfileCommentsResponse;

export const ListLinkedInProfileCommentsResponse$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInProfileCommentResponseDto$inboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListLinkedInProfileCommentsResponse>;
export const ListLinkedInProfileCommentsResponse$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInProfileCommentResponseDto$outboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListLinkedInProfileCommentsResponse$Outbound>;

export function listLinkedInProfileCommentsResponseFromJSON(jsonString: string): ListLinkedInProfileCommentsResponse {
  return ListLinkedInProfileCommentsResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListLinkedInProfileCommentsResponse;
}

export function listLinkedInProfileCommentsResponseToJSON(value: ListLinkedInProfileCommentsResponse): string {
  return JSON.stringify(ListLinkedInProfileCommentsResponse$outboundSchema.parse(value));
}
