/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { InstagramFollowScrapeResponseDto } from "./instagram-follow-scrape-response-dto.js";
import { InstagramFollowScrapeResponseDto$inboundSchema, InstagramFollowScrapeResponseDto$outboundSchema } from "./instagram-follow-scrape-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListInstagramFollowingResponse = {
  "data": InstagramFollowScrapeResponseDto;
  "meta": PublicResponseMetaDto;
};
export type ListInstagramFollowingResponse$Outbound = ListInstagramFollowingResponse;

export const ListInstagramFollowingResponse$inboundSchema = (z.object({
  "data": z.lazy(() => InstagramFollowScrapeResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListInstagramFollowingResponse>;
export const ListInstagramFollowingResponse$outboundSchema = (z.object({
  "data": z.lazy(() => InstagramFollowScrapeResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListInstagramFollowingResponse$Outbound>;

export function listInstagramFollowingResponseFromJSON(jsonString: string): ListInstagramFollowingResponse {
  return ListInstagramFollowingResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListInstagramFollowingResponse;
}

export function listInstagramFollowingResponseToJSON(value: ListInstagramFollowingResponse): string {
  return JSON.stringify(ListInstagramFollowingResponse$outboundSchema.parse(value));
}
