/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInProfilePostsResponseDto } from "./linked-in-profile-posts-response-dto.js";
import { LinkedInProfilePostsResponseDto$inboundSchema, LinkedInProfilePostsResponseDto$outboundSchema } from "./linked-in-profile-posts-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListLinkedInProfilePostsResponse = {
  "data": LinkedInProfilePostsResponseDto;
  "meta": PublicResponseMetaDto;
};
export type ListLinkedInProfilePostsResponse$Outbound = ListLinkedInProfilePostsResponse;

export const ListLinkedInProfilePostsResponse$inboundSchema = (z.object({
  "data": z.lazy(() => LinkedInProfilePostsResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListLinkedInProfilePostsResponse>;
export const ListLinkedInProfilePostsResponse$outboundSchema = (z.object({
  "data": z.lazy(() => LinkedInProfilePostsResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListLinkedInProfilePostsResponse$Outbound>;

export function listLinkedInProfilePostsResponseFromJSON(jsonString: string): ListLinkedInProfilePostsResponse {
  return ListLinkedInProfilePostsResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListLinkedInProfilePostsResponse;
}

export function listLinkedInProfilePostsResponseToJSON(value: ListLinkedInProfilePostsResponse): string {
  return JSON.stringify(ListLinkedInProfilePostsResponse$outboundSchema.parse(value));
}
