/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInPostReactionResponseDto } from "./linked-in-post-reaction-response-dto.js";
import { LinkedInPostReactionResponseDto$inboundSchema, LinkedInPostReactionResponseDto$outboundSchema } from "./linked-in-post-reaction-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListLinkedInPostReactionsResponse = {
  "data": LinkedInPostReactionResponseDto[];
  "meta": PublicResponseMetaDto;
};
export type ListLinkedInPostReactionsResponse$Outbound = ListLinkedInPostReactionsResponse;

export const ListLinkedInPostReactionsResponse$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInPostReactionResponseDto$inboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListLinkedInPostReactionsResponse>;
export const ListLinkedInPostReactionsResponse$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInPostReactionResponseDto$outboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListLinkedInPostReactionsResponse$Outbound>;

export function listLinkedInPostReactionsResponseFromJSON(jsonString: string): ListLinkedInPostReactionsResponse {
  return ListLinkedInPostReactionsResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListLinkedInPostReactionsResponse;
}

export function listLinkedInPostReactionsResponseToJSON(value: ListLinkedInPostReactionsResponse): string {
  return JSON.stringify(ListLinkedInPostReactionsResponse$outboundSchema.parse(value));
}
