/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { InstagramPostResponseDto } from "./instagram-post-response-dto.js";
import { InstagramPostResponseDto$inboundSchema, InstagramPostResponseDto$outboundSchema } from "./instagram-post-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListInstagramPostsResponse = {
  "data": InstagramPostResponseDto[];
  "meta": PublicResponseMetaDto;
};
export type ListInstagramPostsResponse$Outbound = ListInstagramPostsResponse;

export const ListInstagramPostsResponse$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => InstagramPostResponseDto$inboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListInstagramPostsResponse>;
export const ListInstagramPostsResponse$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => InstagramPostResponseDto$outboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListInstagramPostsResponse$Outbound>;

export function listInstagramPostsResponseFromJSON(jsonString: string): ListInstagramPostsResponse {
  return ListInstagramPostsResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListInstagramPostsResponse;
}

export function listInstagramPostsResponseToJSON(value: ListInstagramPostsResponse): string {
  return JSON.stringify(ListInstagramPostsResponse$outboundSchema.parse(value));
}
