/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInPostCommentResponseDto } from "./linked-in-post-comment-response-dto.js";
import { LinkedInPostCommentResponseDto$inboundSchema, LinkedInPostCommentResponseDto$outboundSchema } from "./linked-in-post-comment-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListLinkedInPostCommentsResponse = {
  "data": LinkedInPostCommentResponseDto[];
  "meta": PublicResponseMetaDto;
};
export type ListLinkedInPostCommentsResponse$Outbound = ListLinkedInPostCommentsResponse;

export const ListLinkedInPostCommentsResponse$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInPostCommentResponseDto$inboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListLinkedInPostCommentsResponse>;
export const ListLinkedInPostCommentsResponse$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInPostCommentResponseDto$outboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListLinkedInPostCommentsResponse$Outbound>;

export function listLinkedInPostCommentsResponseFromJSON(jsonString: string): ListLinkedInPostCommentsResponse {
  return ListLinkedInPostCommentsResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListLinkedInPostCommentsResponse;
}

export function listLinkedInPostCommentsResponseToJSON(value: ListLinkedInPostCommentsResponse): string {
  return JSON.stringify(ListLinkedInPostCommentsResponse$outboundSchema.parse(value));
}
