/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { InstagramCommentResponseDto } from "./instagram-comment-response-dto.js";
import { InstagramCommentResponseDto$inboundSchema, InstagramCommentResponseDto$outboundSchema } from "./instagram-comment-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListInstagramPostCommentsResponse = {
  "data": InstagramCommentResponseDto[];
  "meta": PublicResponseMetaDto;
};
export type ListInstagramPostCommentsResponse$Outbound = ListInstagramPostCommentsResponse;

export const ListInstagramPostCommentsResponse$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => InstagramCommentResponseDto$inboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListInstagramPostCommentsResponse>;
export const ListInstagramPostCommentsResponse$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => InstagramCommentResponseDto$outboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListInstagramPostCommentsResponse$Outbound>;

export function listInstagramPostCommentsResponseFromJSON(jsonString: string): ListInstagramPostCommentsResponse {
  return ListInstagramPostCommentsResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListInstagramPostCommentsResponse;
}

export function listInstagramPostCommentsResponseToJSON(value: ListInstagramPostCommentsResponse): string {
  return JSON.stringify(ListInstagramPostCommentsResponse$outboundSchema.parse(value));
}
