/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { InstagramFollowScrapeResponseDto } from "./instagram-follow-scrape-response-dto.js";
import { InstagramFollowScrapeResponseDto$inboundSchema, InstagramFollowScrapeResponseDto$outboundSchema } from "./instagram-follow-scrape-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListInstagramFollowersResponse = {
  "data": InstagramFollowScrapeResponseDto;
  "meta": PublicResponseMetaDto;
};
export type ListInstagramFollowersResponse$Outbound = ListInstagramFollowersResponse;

export const ListInstagramFollowersResponse$inboundSchema = (z.object({
  "data": z.lazy(() => InstagramFollowScrapeResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListInstagramFollowersResponse>;
export const ListInstagramFollowersResponse$outboundSchema = (z.object({
  "data": z.lazy(() => InstagramFollowScrapeResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListInstagramFollowersResponse$Outbound>;

export function listInstagramFollowersResponseFromJSON(jsonString: string): ListInstagramFollowersResponse {
  return ListInstagramFollowersResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListInstagramFollowersResponse;
}

export function listInstagramFollowersResponseToJSON(value: ListInstagramFollowersResponse): string {
  return JSON.stringify(ListInstagramFollowersResponse$outboundSchema.parse(value));
}
