/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInProfileReactionResponseDto } from "./linked-in-profile-reaction-response-dto.js";
import { LinkedInProfileReactionResponseDto$inboundSchema, LinkedInProfileReactionResponseDto$outboundSchema } from "./linked-in-profile-reaction-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type ListLinkedInProfileReactionsResponse = {
  "data": LinkedInProfileReactionResponseDto[];
  "meta": PublicResponseMetaDto;
};
export type ListLinkedInProfileReactionsResponse$Outbound = ListLinkedInProfileReactionsResponse;

export const ListLinkedInProfileReactionsResponse$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInProfileReactionResponseDto$inboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ListLinkedInProfileReactionsResponse>;
export const ListLinkedInProfileReactionsResponse$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInProfileReactionResponseDto$outboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ListLinkedInProfileReactionsResponse$Outbound>;

export function listLinkedInProfileReactionsResponseFromJSON(jsonString: string): ListLinkedInProfileReactionsResponse {
  return ListLinkedInProfileReactionsResponse$inboundSchema.parse(JSON.parse(jsonString)) as ListLinkedInProfileReactionsResponse;
}

export function listLinkedInProfileReactionsResponseToJSON(value: ListLinkedInProfileReactionsResponse): string {
  return JSON.stringify(ListLinkedInProfileReactionsResponse$outboundSchema.parse(value));
}
