/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type MonitorEventDto = {
  "id": string;
  "monitor_id": string;
  "dedup_key": string;
  "event_type": string;
  "event_json": {
  [key: string]: unknown;
};
  "canonical_person_id": string | null;
  "canonical_company_id": string | null;
  "detected_at": string;
};
export type MonitorEventDto$Outbound = MonitorEventDto;

export const MonitorEventDto$inboundSchema = (z.object({
  "id": z.string(),
  "monitor_id": z.string(),
  "dedup_key": z.string(),
  "event_type": z.string(),
  "event_json": z.record(z.string(), z.unknown()),
  "canonical_person_id": z.nullable(z.string()),
  "canonical_company_id": z.nullable(z.string()),
  "detected_at": z.string(),
})) as z.ZodType<MonitorEventDto>;
export const MonitorEventDto$outboundSchema = (z.object({
  "id": z.string(),
  "monitor_id": z.string(),
  "dedup_key": z.string(),
  "event_type": z.string(),
  "event_json": z.record(z.string(), z.unknown()),
  "canonical_person_id": z.nullable(z.string()),
  "canonical_company_id": z.nullable(z.string()),
  "detected_at": z.string(),
})) as z.ZodType<MonitorEventDto$Outbound>;

export function monitorEventDtoFromJSON(jsonString: string): MonitorEventDto {
  return MonitorEventDto$inboundSchema.parse(JSON.parse(jsonString)) as MonitorEventDto;
}

export function monitorEventDtoToJSON(value: MonitorEventDto): string {
  return JSON.stringify(MonitorEventDto$outboundSchema.parse(value));
}
