/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const MonitorResponseDtoType = {
  LinkedinKeyword: "linkedin_keyword",
  LinkedinProfile: "linkedin_profile",
  LinkedinCompany: "linkedin_company",
  LinkedinPost: "linkedin_post",
  InstagramProfile: "instagram_profile",
  InstagramPost: "instagram_post",
  XProfile: "x_profile",
  XKeyword: "x_keyword",
  RedditKeyword: "reddit_keyword",
  RedditSubreddit: "reddit_subreddit",
  TiktokKeyword: "tiktok_keyword",
  TiktokHashtag: "tiktok_hashtag",
  WebSearch: "web_search",
  SiteSearch: "site_search",
} as const;
export type MonitorResponseDtoType = OpenEnum<typeof MonitorResponseDtoType>;

export const MonitorResponseDtoStatus = {
  Active: "active",
  Paused: "paused",
  Disabled: "disabled",
} as const;
export type MonitorResponseDtoStatus = OpenEnum<
  typeof MonitorResponseDtoStatus
>;

export type MonitorResponseDto = {
  id: string;
  name: string;
  type: MonitorResponseDtoType;
  status: MonitorResponseDtoStatus;
  config: { [k: string]: any };
  cadenceMinutes: number;
  lastRunAt: string | null;
  nextRunAt: string | null;
  consecutiveFailures: number;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const MonitorResponseDtoType$inboundSchema: z.ZodMiniType<
  MonitorResponseDtoType,
  unknown
> = openEnums.inboundSchema(MonitorResponseDtoType);

/** @internal */
export const MonitorResponseDtoStatus$inboundSchema: z.ZodMiniType<
  MonitorResponseDtoStatus,
  unknown
> = openEnums.inboundSchema(MonitorResponseDtoStatus);

/** @internal */
export const MonitorResponseDto$inboundSchema: z.ZodMiniType<
  MonitorResponseDto,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    type: MonitorResponseDtoType$inboundSchema,
    status: MonitorResponseDtoStatus$inboundSchema,
    config: z.record(z.string(), z.any()),
    cadence_minutes: types.number(),
    last_run_at: types.nullable(types.string()),
    next_run_at: types.nullable(types.string()),
    consecutive_failures: types.number(),
    created_at: types.string(),
    updated_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cadence_minutes": "cadenceMinutes",
      "last_run_at": "lastRunAt",
      "next_run_at": "nextRunAt",
      "consecutive_failures": "consecutiveFailures",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function monitorResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MonitorResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MonitorResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MonitorResponseDto' from JSON`,
  );
}
