/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MonitorEventDto,
  MonitorEventDto$inboundSchema,
} from "./monitor-event-dto.js";

export type MonitorEventListResponseDto = {
  data: Array<MonitorEventDto>;
  nextCursor: string | null;
};

/** @internal */
export const MonitorEventListResponseDto$inboundSchema: z.ZodMiniType<
  MonitorEventListResponseDto,
  unknown
> = z.pipe(
  z.object({
    data: z.array(MonitorEventDto$inboundSchema),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function monitorEventListResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MonitorEventListResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MonitorEventListResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MonitorEventListResponseDto' from JSON`,
  );
}
