/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { MonitorResponseDto } from "./monitor-response-dto.js";
import { MonitorResponseDto$inboundSchema, MonitorResponseDto$outboundSchema } from "./monitor-response-dto.js";

export type MonitorListResponseDto = {
  "data": MonitorResponseDto[];
  "next_cursor": string | null;
};
export type MonitorListResponseDto$Outbound = MonitorListResponseDto;

export const MonitorListResponseDto$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => MonitorResponseDto$inboundSchema)),
  "next_cursor": z.nullable(z.string()),
})) as z.ZodType<MonitorListResponseDto>;
export const MonitorListResponseDto$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => MonitorResponseDto$outboundSchema)),
  "next_cursor": z.nullable(z.string()),
})) as z.ZodType<MonitorListResponseDto$Outbound>;

export function monitorListResponseDtoFromJSON(jsonString: string): MonitorListResponseDto {
  return MonitorListResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as MonitorListResponseDto;
}

export function monitorListResponseDtoToJSON(value: MonitorListResponseDto): string {
  return JSON.stringify(MonitorListResponseDto$outboundSchema.parse(value));
}
