/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MonitorResponseDto,
  MonitorResponseDto$inboundSchema,
} from "./monitor-response-dto.js";

export type MonitorListResponseDto = {
  data: Array<MonitorResponseDto>;
  nextCursor: string | null;
};

/** @internal */
export const MonitorListResponseDto$inboundSchema: z.ZodMiniType<
  MonitorListResponseDto,
  unknown
> = z.pipe(
  z.object({
    data: z.array(MonitorResponseDto$inboundSchema),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function monitorListResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MonitorListResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MonitorListResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MonitorListResponseDto' from JSON`,
  );
}
