/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type MonitorEventDto = {
  id: string;
  monitorId: string;
  dedupKey: string;
  eventType: string;
  eventJson: { [k: string]: any };
  canonicalPersonId: string | null;
  canonicalCompanyId: string | null;
  detectedAt: string;
};

/** @internal */
export const MonitorEventDto$inboundSchema: z.ZodMiniType<
  MonitorEventDto,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    monitor_id: types.string(),
    dedup_key: types.string(),
    event_type: types.string(),
    event_json: z.record(z.string(), z.any()),
    canonical_person_id: types.nullable(types.string()),
    canonical_company_id: types.nullable(types.string()),
    detected_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "monitor_id": "monitorId",
      "dedup_key": "dedupKey",
      "event_type": "eventType",
      "event_json": "eventJson",
      "canonical_person_id": "canonicalPersonId",
      "canonical_company_id": "canonicalCompanyId",
      "detected_at": "detectedAt",
    });
  }),
);

export function monitorEventDtoFromJSON(
  jsonString: string,
): SafeParseResult<MonitorEventDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MonitorEventDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MonitorEventDto' from JSON`,
  );
}
