/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type MonitorResponseDto = {
  "id": string;
  "name": string;
  "type": "linkedin_keyword" | "linkedin_profile" | "linkedin_company" | "linkedin_post" | "instagram_profile" | "instagram_post" | "x_profile" | "x_keyword" | "reddit_keyword" | "reddit_subreddit" | "tiktok_keyword" | "tiktok_hashtag" | "web_search" | "site_search";
  "status": "active" | "paused" | "disabled";
  "config": {
  [key: string]: unknown;
};
  "cadence_minutes": number;
  "last_run_at": string | null;
  "next_run_at": string | null;
  "consecutive_failures": number;
  "created_at": string;
  "updated_at": string;
};
export type MonitorResponseDto$Outbound = MonitorResponseDto;

export const MonitorResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "name": z.string(),
  "type": z.enum(["linkedin_keyword","linkedin_profile","linkedin_company","linkedin_post","instagram_profile","instagram_post","x_profile","x_keyword","reddit_keyword","reddit_subreddit","tiktok_keyword","tiktok_hashtag","web_search","site_search"]),
  "status": z.enum(["active","paused","disabled"]),
  "config": z.record(z.string(), z.unknown()),
  "cadence_minutes": z.number(),
  "last_run_at": z.nullable(z.string()),
  "next_run_at": z.nullable(z.string()),
  "consecutive_failures": z.number(),
  "created_at": z.string(),
  "updated_at": z.string(),
})) as z.ZodType<MonitorResponseDto>;
export const MonitorResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "name": z.string(),
  "type": z.enum(["linkedin_keyword","linkedin_profile","linkedin_company","linkedin_post","instagram_profile","instagram_post","x_profile","x_keyword","reddit_keyword","reddit_subreddit","tiktok_keyword","tiktok_hashtag","web_search","site_search"]),
  "status": z.enum(["active","paused","disabled"]),
  "config": z.record(z.string(), z.unknown()),
  "cadence_minutes": z.number(),
  "last_run_at": z.nullable(z.string()),
  "next_run_at": z.nullable(z.string()),
  "consecutive_failures": z.number(),
  "created_at": z.string(),
  "updated_at": z.string(),
})) as z.ZodType<MonitorResponseDto$Outbound>;

export function monitorResponseDtoFromJSON(jsonString: string): MonitorResponseDto {
  return MonitorResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as MonitorResponseDto;
}

export function monitorResponseDtoToJSON(value: MonitorResponseDto): string {
  return JSON.stringify(MonitorResponseDto$outboundSchema.parse(value));
}
