/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const OperationResponseDtoStatus = {
  Queued: "queued",
  Processing: "processing",
  Succeeded: "succeeded",
  Failed: "failed",
  PartialSuccess: "partial_success",
  Cancelled: "cancelled",
} as const;
export type OperationResponseDtoStatus = OpenEnum<
  typeof OperationResponseDtoStatus
>;

export type OperationResponseDto = {
  id: string;
  status: OperationResponseDtoStatus;
  progress?: number | null | undefined;
  result?: { [k: string]: any } | null | undefined;
  error?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const OperationResponseDtoStatus$inboundSchema: z.ZodMiniType<
  OperationResponseDtoStatus,
  unknown
> = openEnums.inboundSchema(OperationResponseDtoStatus);

/** @internal */
export const OperationResponseDto$inboundSchema: z.ZodMiniType<
  OperationResponseDto,
  unknown
> = z.object({
  id: types.string(),
  status: OperationResponseDtoStatus$inboundSchema,
  progress: z.optional(z.nullable(types.number())),
  result: z.optional(z.nullable(z.record(z.string(), z.any()))),
  error: z.optional(z.nullable(z.record(z.string(), z.any()))),
});

export function operationResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<OperationResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OperationResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OperationResponseDto' from JSON`,
  );
}
