/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type OperationResponseDto = {
  "id": string;
  "status": "queued" | "processing" | "succeeded" | "failed" | "partial_success" | "cancelled";
  "progress"?: number | null;
  "result"?: {
  [key: string]: unknown;
} | null;
  "error"?: {
  [key: string]: unknown;
} | null;
};
export type OperationResponseDto$Outbound = OperationResponseDto;

export const OperationResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "status": z.enum(["queued","processing","succeeded","failed","partial_success","cancelled"]),
  "progress": z.optional(z.nullable(z.number())),
  "result": z.optional(z.nullable(z.record(z.string(), z.unknown()))),
  "error": z.optional(z.nullable(z.record(z.string(), z.unknown()))),
})) as z.ZodType<OperationResponseDto>;
export const OperationResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "status": z.enum(["queued","processing","succeeded","failed","partial_success","cancelled"]),
  "progress": z.optional(z.nullable(z.number())),
  "result": z.optional(z.nullable(z.record(z.string(), z.unknown()))),
  "error": z.optional(z.nullable(z.record(z.string(), z.unknown()))),
})) as z.ZodType<OperationResponseDto$Outbound>;

export function operationResponseDtoFromJSON(jsonString: string): OperationResponseDto {
  return OperationResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as OperationResponseDto;
}

export function operationResponseDtoToJSON(value: OperationResponseDto): string {
  return JSON.stringify(OperationResponseDto$outboundSchema.parse(value));
}
