/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PersonIdentifierRecordDto = {
  "linkedin_url"?: string;
  "email"?: string;
  "x_handle"?: string;
  "github_username"?: string;
};
export type PersonIdentifierRecordDto$Outbound = PersonIdentifierRecordDto;

export const PersonIdentifierRecordDto$inboundSchema = (z.object({
  "linkedin_url": z.optional(z.string()),
  "email": z.optional(z.string()),
  "x_handle": z.optional(z.string()),
  "github_username": z.optional(z.string()),
})) as z.ZodType<PersonIdentifierRecordDto>;
export const PersonIdentifierRecordDto$outboundSchema = (z.object({
  "linkedin_url": z.optional(z.string()),
  "email": z.optional(z.string()),
  "x_handle": z.optional(z.string()),
  "github_username": z.optional(z.string()),
})) as z.ZodType<PersonIdentifierRecordDto$Outbound>;

export function personIdentifierRecordDtoFromJSON(jsonString: string): PersonIdentifierRecordDto {
  return PersonIdentifierRecordDto$inboundSchema.parse(JSON.parse(jsonString)) as PersonIdentifierRecordDto;
}

export function personIdentifierRecordDtoToJSON(value: PersonIdentifierRecordDto): string {
  return JSON.stringify(PersonIdentifierRecordDto$outboundSchema.parse(value));
}
