/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PersonIdentifierRecordDto = {
  linkedinUrl?: string | undefined;
  email?: string | undefined;
  xHandle?: string | undefined;
  githubUsername?: string | undefined;
};

/** @internal */
export type PersonIdentifierRecordDto$Outbound = {
  linkedin_url?: string | undefined;
  email?: string | undefined;
  x_handle?: string | undefined;
  github_username?: string | undefined;
};

/** @internal */
export const PersonIdentifierRecordDto$outboundSchema: z.ZodMiniType<
  PersonIdentifierRecordDto$Outbound,
  PersonIdentifierRecordDto
> = z.pipe(
  z.object({
    linkedinUrl: z.optional(z.string()),
    email: z.optional(z.string()),
    xHandle: z.optional(z.string()),
    githubUsername: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      linkedinUrl: "linkedin_url",
      xHandle: "x_handle",
      githubUsername: "github_username",
    });
  }),
);

export function personIdentifierRecordDtoToJSON(
  personIdentifierRecordDto: PersonIdentifierRecordDto,
): string {
  return JSON.stringify(
    PersonIdentifierRecordDto$outboundSchema.parse(personIdentifierRecordDto),
  );
}
