/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformLinkedInFinderDto = {
  /**
   * Website domains or URLs to look up.
   */
  domains: Array<string>;
};

/** @internal */
export type PlatformLinkedInFinderDto$Outbound = {
  domains: Array<string>;
};

/** @internal */
export const PlatformLinkedInFinderDto$outboundSchema: z.ZodMiniType<
  PlatformLinkedInFinderDto$Outbound,
  PlatformLinkedInFinderDto
> = z.object({
  domains: z.array(z.string()),
});

export function platformLinkedInFinderDtoToJSON(
  platformLinkedInFinderDto: PlatformLinkedInFinderDto,
): string {
  return JSON.stringify(
    PlatformLinkedInFinderDto$outboundSchema.parse(platformLinkedInFinderDto),
  );
}
