/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformInstagramUsernameDto = {
  username: string;
  maxPosts?: number | undefined;
};

/** @internal */
export type PlatformInstagramUsernameDto$Outbound = {
  username: string;
  maxPosts?: number | undefined;
};

/** @internal */
export const PlatformInstagramUsernameDto$outboundSchema: z.ZodMiniType<
  PlatformInstagramUsernameDto$Outbound,
  PlatformInstagramUsernameDto
> = z.object({
  username: z.string(),
  maxPosts: z.optional(z.number()),
});

export function platformInstagramUsernameDtoToJSON(
  platformInstagramUsernameDto: PlatformInstagramUsernameDto,
): string {
  return JSON.stringify(
    PlatformInstagramUsernameDto$outboundSchema.parse(
      platformInstagramUsernameDto,
    ),
  );
}
