/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformLinkedInProfileDto = {
  username: string;
};

/** @internal */
export type PlatformLinkedInProfileDto$Outbound = {
  username: string;
};

/** @internal */
export const PlatformLinkedInProfileDto$outboundSchema: z.ZodMiniType<
  PlatformLinkedInProfileDto$Outbound,
  PlatformLinkedInProfileDto
> = z.object({
  username: z.string(),
});

export function platformLinkedInProfileDtoToJSON(
  platformLinkedInProfileDto: PlatformLinkedInProfileDto,
): string {
  return JSON.stringify(
    PlatformLinkedInProfileDto$outboundSchema.parse(platformLinkedInProfileDto),
  );
}
