/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformWebScrapeBatchItemDto = {
  "url": string;
  "renderJs"?: boolean;
  "maxAgeMs"?: number;
  "maxAgeDays"?: number;
};
export type PlatformWebScrapeBatchItemDto$Outbound = PlatformWebScrapeBatchItemDto;

export const PlatformWebScrapeBatchItemDto$inboundSchema = (z.object({
  "url": z.string(),
  "renderJs": z.optional(z.boolean()),
  "maxAgeMs": z.optional(z.number()),
  "maxAgeDays": z.optional(z.number()),
})) as z.ZodType<PlatformWebScrapeBatchItemDto>;
export const PlatformWebScrapeBatchItemDto$outboundSchema = (z.object({
  "url": z.string(),
  "renderJs": z.optional(z.boolean()),
  "maxAgeMs": z.optional(z.number()),
  "maxAgeDays": z.optional(z.number()),
})) as z.ZodType<PlatformWebScrapeBatchItemDto$Outbound>;

export function platformWebScrapeBatchItemDtoFromJSON(jsonString: string): PlatformWebScrapeBatchItemDto {
  return PlatformWebScrapeBatchItemDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformWebScrapeBatchItemDto;
}

export function platformWebScrapeBatchItemDtoToJSON(value: PlatformWebScrapeBatchItemDto): string {
  return JSON.stringify(PlatformWebScrapeBatchItemDto$outboundSchema.parse(value));
}
