/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformInstagramFollowersDto = {
  "username": string;
  "maxFollowers"?: number;
};
export type PlatformInstagramFollowersDto$Outbound = PlatformInstagramFollowersDto;

export const PlatformInstagramFollowersDto$inboundSchema = (z.object({
  "username": z.string(),
  "maxFollowers": z.optional(z.number()),
})) as z.ZodType<PlatformInstagramFollowersDto>;
export const PlatformInstagramFollowersDto$outboundSchema = (z.object({
  "username": z.string(),
  "maxFollowers": z.optional(z.number()),
})) as z.ZodType<PlatformInstagramFollowersDto$Outbound>;

export function platformInstagramFollowersDtoFromJSON(jsonString: string): PlatformInstagramFollowersDto {
  return PlatformInstagramFollowersDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformInstagramFollowersDto;
}

export function platformInstagramFollowersDtoToJSON(value: PlatformInstagramFollowersDto): string {
  return JSON.stringify(PlatformInstagramFollowersDto$outboundSchema.parse(value));
}
