/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Fetch posts no older than this time window.
 */
export const PostedLimit = {
  Any: "any",
  TwentyFourh: "24h",
  Week: "week",
  Month: "month",
  Threemonths: "3months",
  Sixmonths: "6months",
  Year: "year",
} as const;
/**
 * Fetch posts no older than this time window.
 */
export type PostedLimit = ClosedEnum<typeof PostedLimit>;

export type PlatformLinkedInProfileActivityDto = {
  /**
   * LinkedIn profile URLs or public profile usernames.
   */
  profiles: Array<string>;
  maxItems?: number | undefined;
  /**
   * Fetch posts no older than this time window.
   */
  postedLimit?: PostedLimit | undefined;
};

/** @internal */
export const PostedLimit$outboundSchema: z.ZodMiniEnum<typeof PostedLimit> = z
  .enum(PostedLimit);

/** @internal */
export type PlatformLinkedInProfileActivityDto$Outbound = {
  profiles: Array<string>;
  maxItems: number;
  postedLimit: string;
};

/** @internal */
export const PlatformLinkedInProfileActivityDto$outboundSchema: z.ZodMiniType<
  PlatformLinkedInProfileActivityDto$Outbound,
  PlatformLinkedInProfileActivityDto
> = z.object({
  profiles: z.array(z.string()),
  maxItems: z._default(z.number(), 10),
  postedLimit: z._default(PostedLimit$outboundSchema, "any"),
});

export function platformLinkedInProfileActivityDtoToJSON(
  platformLinkedInProfileActivityDto: PlatformLinkedInProfileActivityDto,
): string {
  return JSON.stringify(
    PlatformLinkedInProfileActivityDto$outboundSchema.parse(
      platformLinkedInProfileActivityDto,
    ),
  );
}
