/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformInstagramFollowingDto = {
  username: string;
  /**
   * Requested following limit. The upstream source may return more than requested. Unlimited is not exposed on v1.
   */
  maxFollowing?: number | undefined;
};

/** @internal */
export type PlatformInstagramFollowingDto$Outbound = {
  username: string;
  maxFollowing?: number | undefined;
};

/** @internal */
export const PlatformInstagramFollowingDto$outboundSchema: z.ZodMiniType<
  PlatformInstagramFollowingDto$Outbound,
  PlatformInstagramFollowingDto
> = z.object({
  username: z.string(),
  maxFollowing: z.optional(z.number()),
});

export function platformInstagramFollowingDtoToJSON(
  platformInstagramFollowingDto: PlatformInstagramFollowingDto,
): string {
  return JSON.stringify(
    PlatformInstagramFollowingDto$outboundSchema.parse(
      platformInstagramFollowingDto,
    ),
  );
}
