/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformLinkedInCompanyDto = {
  identifier: string;
};

/** @internal */
export type PlatformLinkedInCompanyDto$Outbound = {
  identifier: string;
};

/** @internal */
export const PlatformLinkedInCompanyDto$outboundSchema: z.ZodMiniType<
  PlatformLinkedInCompanyDto$Outbound,
  PlatformLinkedInCompanyDto
> = z.object({
  identifier: z.string(),
});

export function platformLinkedInCompanyDtoToJSON(
  platformLinkedInCompanyDto: PlatformLinkedInCompanyDto,
): string {
  return JSON.stringify(
    PlatformLinkedInCompanyDto$outboundSchema.parse(platformLinkedInCompanyDto),
  );
}
