/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformInstagramFollowingDto = {
  "username": string;
  "maxFollowing"?: number;
};
export type PlatformInstagramFollowingDto$Outbound = PlatformInstagramFollowingDto;

export const PlatformInstagramFollowingDto$inboundSchema = (z.object({
  "username": z.string(),
  "maxFollowing": z.optional(z.number()),
})) as z.ZodType<PlatformInstagramFollowingDto>;
export const PlatformInstagramFollowingDto$outboundSchema = (z.object({
  "username": z.string(),
  "maxFollowing": z.optional(z.number()),
})) as z.ZodType<PlatformInstagramFollowingDto$Outbound>;

export function platformInstagramFollowingDtoFromJSON(jsonString: string): PlatformInstagramFollowingDto {
  return PlatformInstagramFollowingDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformInstagramFollowingDto;
}

export function platformInstagramFollowingDtoToJSON(value: PlatformInstagramFollowingDto): string {
  return JSON.stringify(PlatformInstagramFollowingDto$outboundSchema.parse(value));
}
