/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformLinkedInProfilePostsDto = {
  username: string;
  maxPosts?: number | undefined;
};

/** @internal */
export type PlatformLinkedInProfilePostsDto$Outbound = {
  username: string;
  maxPosts: number;
};

/** @internal */
export const PlatformLinkedInProfilePostsDto$outboundSchema: z.ZodMiniType<
  PlatformLinkedInProfilePostsDto$Outbound,
  PlatformLinkedInProfilePostsDto
> = z.object({
  username: z.string(),
  maxPosts: z._default(z.number(), 20),
});

export function platformLinkedInProfilePostsDtoToJSON(
  platformLinkedInProfilePostsDto: PlatformLinkedInProfilePostsDto,
): string {
  return JSON.stringify(
    PlatformLinkedInProfilePostsDto$outboundSchema.parse(
      platformLinkedInProfilePostsDto,
    ),
  );
}
