/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformLinkedInCompanyPostsDto = {
  "companySlug": string;
  "limit"?: number;
};
export type PlatformLinkedInCompanyPostsDto$Outbound = PlatformLinkedInCompanyPostsDto;

export const PlatformLinkedInCompanyPostsDto$inboundSchema = (z.object({
  "companySlug": z.string(),
  "limit": z.optional(z.number()),
})) as z.ZodType<PlatformLinkedInCompanyPostsDto>;
export const PlatformLinkedInCompanyPostsDto$outboundSchema = (z.object({
  "companySlug": z.string(),
  "limit": z.optional(z.number()),
})) as z.ZodType<PlatformLinkedInCompanyPostsDto$Outbound>;

export function platformLinkedInCompanyPostsDtoFromJSON(jsonString: string): PlatformLinkedInCompanyPostsDto {
  return PlatformLinkedInCompanyPostsDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformLinkedInCompanyPostsDto;
}

export function platformLinkedInCompanyPostsDtoToJSON(value: PlatformLinkedInCompanyPostsDto): string {
  return JSON.stringify(PlatformLinkedInCompanyPostsDto$outboundSchema.parse(value));
}
