/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformWebScrapeDto = {
  /**
   * URL to scrape
   */
  url: string;
  /**
   * Render JavaScript before scraping
   */
  renderJs?: boolean | undefined;
  /**
   * Maximum accepted cache age in milliseconds. Use 0 or omit to force a fresh scrape.
   */
  maxAgeMs?: number | undefined;
  /**
   * Maximum accepted cache age in days. Use 0 or omit to force a fresh scrape. Ignored when maxAgeMs is provided.
   */
  maxAgeDays?: number | undefined;
};

/** @internal */
export type PlatformWebScrapeDto$Outbound = {
  url: string;
  renderJs: boolean;
  maxAgeMs: number;
  maxAgeDays: number;
};

/** @internal */
export const PlatformWebScrapeDto$outboundSchema: z.ZodMiniType<
  PlatformWebScrapeDto$Outbound,
  PlatformWebScrapeDto
> = z.object({
  url: z.string(),
  renderJs: z._default(z.boolean(), false),
  maxAgeMs: z._default(z.number(), 0),
  maxAgeDays: z._default(z.number(), 0),
});

export function platformWebScrapeDtoToJSON(
  platformWebScrapeDto: PlatformWebScrapeDto,
): string {
  return JSON.stringify(
    PlatformWebScrapeDto$outboundSchema.parse(platformWebScrapeDto),
  );
}
