/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformTikTokUsernameDto = {
  "username": string;
  "maxVideos"?: number;
};
export type PlatformTikTokUsernameDto$Outbound = PlatformTikTokUsernameDto;

export const PlatformTikTokUsernameDto$inboundSchema = (z.object({
  "username": z.string(),
  "maxVideos": z.optional(z.number()),
})) as z.ZodType<PlatformTikTokUsernameDto>;
export const PlatformTikTokUsernameDto$outboundSchema = (z.object({
  "username": z.string(),
  "maxVideos": z.optional(z.number()),
})) as z.ZodType<PlatformTikTokUsernameDto$Outbound>;

export function platformTikTokUsernameDtoFromJSON(jsonString: string): PlatformTikTokUsernameDto {
  return PlatformTikTokUsernameDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformTikTokUsernameDto;
}

export function platformTikTokUsernameDtoToJSON(value: PlatformTikTokUsernameDto): string {
  return JSON.stringify(PlatformTikTokUsernameDto$outboundSchema.parse(value));
}
