/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PlatformWebScrapeBatchItemDto } from "./platform-web-scrape-batch-item-dto.js";
import { PlatformWebScrapeBatchItemDto$inboundSchema, PlatformWebScrapeBatchItemDto$outboundSchema } from "./platform-web-scrape-batch-item-dto.js";

export type PlatformWebScrapeBatchDto = {
  "urls"?: string[];
  "items"?: PlatformWebScrapeBatchItemDto[];
  "renderJs"?: boolean;
  "maxAgeMs"?: number;
  "maxAgeDays"?: number;
  "maxConcurrency"?: number;
};
export type PlatformWebScrapeBatchDto$Outbound = PlatformWebScrapeBatchDto;

export const PlatformWebScrapeBatchDto$inboundSchema = (z.object({
  "urls": z.optional(z.array(z.string())),
  "items": z.optional(z.array(z.lazy(() => PlatformWebScrapeBatchItemDto$inboundSchema))),
  "renderJs": z.optional(z.boolean()),
  "maxAgeMs": z.optional(z.number()),
  "maxAgeDays": z.optional(z.number()),
  "maxConcurrency": z.optional(z.number()),
})) as z.ZodType<PlatformWebScrapeBatchDto>;
export const PlatformWebScrapeBatchDto$outboundSchema = (z.object({
  "urls": z.optional(z.array(z.string())),
  "items": z.optional(z.array(z.lazy(() => PlatformWebScrapeBatchItemDto$outboundSchema))),
  "renderJs": z.optional(z.boolean()),
  "maxAgeMs": z.optional(z.number()),
  "maxAgeDays": z.optional(z.number()),
  "maxConcurrency": z.optional(z.number()),
})) as z.ZodType<PlatformWebScrapeBatchDto$Outbound>;

export function platformWebScrapeBatchDtoFromJSON(jsonString: string): PlatformWebScrapeBatchDto {
  return PlatformWebScrapeBatchDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformWebScrapeBatchDto;
}

export function platformWebScrapeBatchDtoToJSON(value: PlatformWebScrapeBatchDto): string {
  return JSON.stringify(PlatformWebScrapeBatchDto$outboundSchema.parse(value));
}
