/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformLinkedInCompanyDto = {
  "identifier": string;
};
export type PlatformLinkedInCompanyDto$Outbound = PlatformLinkedInCompanyDto;

export const PlatformLinkedInCompanyDto$inboundSchema = (z.object({
  "identifier": z.string(),
})) as z.ZodType<PlatformLinkedInCompanyDto>;
export const PlatformLinkedInCompanyDto$outboundSchema = (z.object({
  "identifier": z.string(),
})) as z.ZodType<PlatformLinkedInCompanyDto$Outbound>;

export function platformLinkedInCompanyDtoFromJSON(jsonString: string): PlatformLinkedInCompanyDto {
  return PlatformLinkedInCompanyDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformLinkedInCompanyDto;
}

export function platformLinkedInCompanyDtoToJSON(value: PlatformLinkedInCompanyDto): string {
  return JSON.stringify(PlatformLinkedInCompanyDto$outboundSchema.parse(value));
}
