/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  LinkedInKeywordPostsConfigBodyDto,
  LinkedInKeywordPostsConfigBodyDto$Outbound,
  LinkedInKeywordPostsConfigBodyDto$outboundSchema,
} from "./linked-in-keyword-posts-config-body-dto.js";

export type PlatformLinkedInKeywordPostsDto = {
  keyword: string;
  config?: LinkedInKeywordPostsConfigBodyDto | undefined;
};

/** @internal */
export type PlatformLinkedInKeywordPostsDto$Outbound = {
  keyword: string;
  config?: LinkedInKeywordPostsConfigBodyDto$Outbound | undefined;
};

/** @internal */
export const PlatformLinkedInKeywordPostsDto$outboundSchema: z.ZodMiniType<
  PlatformLinkedInKeywordPostsDto$Outbound,
  PlatformLinkedInKeywordPostsDto
> = z.object({
  keyword: z.string(),
  config: z.optional(LinkedInKeywordPostsConfigBodyDto$outboundSchema),
});

export function platformLinkedInKeywordPostsDtoToJSON(
  platformLinkedInKeywordPostsDto: PlatformLinkedInKeywordPostsDto,
): string {
  return JSON.stringify(
    PlatformLinkedInKeywordPostsDto$outboundSchema.parse(
      platformLinkedInKeywordPostsDto,
    ),
  );
}
