/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformWebCrawlDto = {
  "url": string;
  "limit"?: number;
  "maxPages"?: number;
  "maxDepth"?: number;
  "sameDomainOnly"?: boolean;
  "instructions"?: string;
};
export type PlatformWebCrawlDto$Outbound = PlatformWebCrawlDto;

export const PlatformWebCrawlDto$inboundSchema = (z.object({
  "url": z.string(),
  "limit": z.optional(z.number()),
  "maxPages": z.optional(z.number()),
  "maxDepth": z.optional(z.number()),
  "sameDomainOnly": z.optional(z.boolean()),
  "instructions": z.optional(z.string()),
})) as z.ZodType<PlatformWebCrawlDto>;
export const PlatformWebCrawlDto$outboundSchema = (z.object({
  "url": z.string(),
  "limit": z.optional(z.number()),
  "maxPages": z.optional(z.number()),
  "maxDepth": z.optional(z.number()),
  "sameDomainOnly": z.optional(z.boolean()),
  "instructions": z.optional(z.string()),
})) as z.ZodType<PlatformWebCrawlDto$Outbound>;

export function platformWebCrawlDtoFromJSON(jsonString: string): PlatformWebCrawlDto {
  return PlatformWebCrawlDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformWebCrawlDto;
}

export function platformWebCrawlDtoToJSON(value: PlatformWebCrawlDto): string {
  return JSON.stringify(PlatformWebCrawlDto$outboundSchema.parse(value));
}
