/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformInstagramPostCommentsDto = {
  postUrl: string;
  maxComments?: number | undefined;
  /**
   * When true, requests nested reply threads from the comment actor (more items / cost).
   */
  includeNested?: boolean | undefined;
};

/** @internal */
export type PlatformInstagramPostCommentsDto$Outbound = {
  postUrl: string;
  maxComments?: number | undefined;
  includeNested?: boolean | undefined;
};

/** @internal */
export const PlatformInstagramPostCommentsDto$outboundSchema: z.ZodMiniType<
  PlatformInstagramPostCommentsDto$Outbound,
  PlatformInstagramPostCommentsDto
> = z.object({
  postUrl: z.string(),
  maxComments: z.optional(z.number()),
  includeNested: z.optional(z.boolean()),
});

export function platformInstagramPostCommentsDtoToJSON(
  platformInstagramPostCommentsDto: PlatformInstagramPostCommentsDto,
): string {
  return JSON.stringify(
    PlatformInstagramPostCommentsDto$outboundSchema.parse(
      platformInstagramPostCommentsDto,
    ),
  );
}
