/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformLinkedInProfileActivityDto = {
  "profiles": string[];
  "maxItems"?: number;
  "postedLimit"?: "any" | "24h" | "week" | "month" | "3months" | "6months" | "year";
};
export type PlatformLinkedInProfileActivityDto$Outbound = PlatformLinkedInProfileActivityDto;

export const PlatformLinkedInProfileActivityDto$inboundSchema = (z.object({
  "profiles": z.array(z.string()),
  "maxItems": z.optional(z.number()),
  "postedLimit": z.optional(z.enum(["any","24h","week","month","3months","6months","year"])),
})) as z.ZodType<PlatformLinkedInProfileActivityDto>;
export const PlatformLinkedInProfileActivityDto$outboundSchema = (z.object({
  "profiles": z.array(z.string()),
  "maxItems": z.optional(z.number()),
  "postedLimit": z.optional(z.enum(["any","24h","week","month","3months","6months","year"])),
})) as z.ZodType<PlatformLinkedInProfileActivityDto$Outbound>;

export function platformLinkedInProfileActivityDtoFromJSON(jsonString: string): PlatformLinkedInProfileActivityDto {
  return PlatformLinkedInProfileActivityDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformLinkedInProfileActivityDto;
}

export function platformLinkedInProfileActivityDtoToJSON(value: PlatformLinkedInProfileActivityDto): string {
  return JSON.stringify(PlatformLinkedInProfileActivityDto$outboundSchema.parse(value));
}
