/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformInstagramPostDetailsDto = {
  postUrl: string;
};

/** @internal */
export type PlatformInstagramPostDetailsDto$Outbound = {
  postUrl: string;
};

/** @internal */
export const PlatformInstagramPostDetailsDto$outboundSchema: z.ZodMiniType<
  PlatformInstagramPostDetailsDto$Outbound,
  PlatformInstagramPostDetailsDto
> = z.object({
  postUrl: z.string(),
});

export function platformInstagramPostDetailsDtoToJSON(
  platformInstagramPostDetailsDto: PlatformInstagramPostDetailsDto,
): string {
  return JSON.stringify(
    PlatformInstagramPostDetailsDto$outboundSchema.parse(
      platformInstagramPostDetailsDto,
    ),
  );
}
