/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const SearchDepth = {
  Basic: "basic",
  Advanced: "advanced",
} as const;
export type SearchDepth = ClosedEnum<typeof SearchDepth>;

export const Topic = {
  General: "general",
  News: "news",
} as const;
export type Topic = ClosedEnum<typeof Topic>;

export type PlatformWebSearchDto = {
  /**
   * Search query
   */
  query: string;
  maxResults?: number | undefined;
  searchDepth?: SearchDepth | undefined;
  topic?: Topic | undefined;
  /**
   * Limit results to last N days (news only)
   */
  days?: number | undefined;
  /**
   * Only include results from these domains
   */
  includeDomains?: Array<string> | undefined;
  /**
   * Exclude results from these domains
   */
  excludeDomains?: Array<string> | undefined;
};

/** @internal */
export const SearchDepth$outboundSchema: z.ZodMiniEnum<typeof SearchDepth> = z
  .enum(SearchDepth);

/** @internal */
export const Topic$outboundSchema: z.ZodMiniEnum<typeof Topic> = z.enum(Topic);

/** @internal */
export type PlatformWebSearchDto$Outbound = {
  query: string;
  maxResults: number;
  searchDepth: string;
  topic: string;
  days?: number | undefined;
  includeDomains?: Array<string> | undefined;
  excludeDomains?: Array<string> | undefined;
};

/** @internal */
export const PlatformWebSearchDto$outboundSchema: z.ZodMiniType<
  PlatformWebSearchDto$Outbound,
  PlatformWebSearchDto
> = z.object({
  query: z.string(),
  maxResults: z._default(z.number(), 10),
  searchDepth: z._default(SearchDepth$outboundSchema, "basic"),
  topic: z._default(Topic$outboundSchema, "general"),
  days: z.optional(z.number()),
  includeDomains: z.optional(z.array(z.string())),
  excludeDomains: z.optional(z.array(z.string())),
});

export function platformWebSearchDtoToJSON(
  platformWebSearchDto: PlatformWebSearchDto,
): string {
  return JSON.stringify(
    PlatformWebSearchDto$outboundSchema.parse(platformWebSearchDto),
  );
}
