/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformLinkedInPostUrlsDto = {
  postUrls: Array<string>;
  maxItems?: number | undefined;
};

/** @internal */
export type PlatformLinkedInPostUrlsDto$Outbound = {
  postUrls: Array<string>;
  maxItems: number;
};

/** @internal */
export const PlatformLinkedInPostUrlsDto$outboundSchema: z.ZodMiniType<
  PlatformLinkedInPostUrlsDto$Outbound,
  PlatformLinkedInPostUrlsDto
> = z.object({
  postUrls: z.array(z.string()),
  maxItems: z._default(z.number(), 10),
});

export function platformLinkedInPostUrlsDtoToJSON(
  platformLinkedInPostUrlsDto: PlatformLinkedInPostUrlsDto,
): string {
  return JSON.stringify(
    PlatformLinkedInPostUrlsDto$outboundSchema.parse(
      platformLinkedInPostUrlsDto,
    ),
  );
}
