/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformInstagramPostCommentsDto = {
  "postUrl": string;
  "maxComments"?: number;
  "includeNested"?: boolean;
};
export type PlatformInstagramPostCommentsDto$Outbound = PlatformInstagramPostCommentsDto;

export const PlatformInstagramPostCommentsDto$inboundSchema = (z.object({
  "postUrl": z.string(),
  "maxComments": z.optional(z.number()),
  "includeNested": z.optional(z.boolean()),
})) as z.ZodType<PlatformInstagramPostCommentsDto>;
export const PlatformInstagramPostCommentsDto$outboundSchema = (z.object({
  "postUrl": z.string(),
  "maxComments": z.optional(z.number()),
  "includeNested": z.optional(z.boolean()),
})) as z.ZodType<PlatformInstagramPostCommentsDto$Outbound>;

export function platformInstagramPostCommentsDtoFromJSON(jsonString: string): PlatformInstagramPostCommentsDto {
  return PlatformInstagramPostCommentsDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformInstagramPostCommentsDto;
}

export function platformInstagramPostCommentsDtoToJSON(value: PlatformInstagramPostCommentsDto): string {
  return JSON.stringify(PlatformInstagramPostCommentsDto$outboundSchema.parse(value));
}
