/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformTikTokUsernameDto = {
  username: string;
  maxVideos?: number | undefined;
};

/** @internal */
export type PlatformTikTokUsernameDto$Outbound = {
  username: string;
  maxVideos?: number | undefined;
};

/** @internal */
export const PlatformTikTokUsernameDto$outboundSchema: z.ZodMiniType<
  PlatformTikTokUsernameDto$Outbound,
  PlatformTikTokUsernameDto
> = z.object({
  username: z.string(),
  maxVideos: z.optional(z.number()),
});

export function platformTikTokUsernameDtoToJSON(
  platformTikTokUsernameDto: PlatformTikTokUsernameDto,
): string {
  return JSON.stringify(
    PlatformTikTokUsernameDto$outboundSchema.parse(platformTikTokUsernameDto),
  );
}
