/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformWebSearchDto = {
  "query": string;
  "maxResults"?: number;
  "searchDepth"?: "basic" | "advanced";
  "topic"?: "general" | "news";
  "days"?: number;
  "includeDomains"?: string[];
  "excludeDomains"?: string[];
};
export type PlatformWebSearchDto$Outbound = PlatformWebSearchDto;

export const PlatformWebSearchDto$inboundSchema = (z.object({
  "query": z.string(),
  "maxResults": z.optional(z.number()),
  "searchDepth": z.optional(z.enum(["basic","advanced"])),
  "topic": z.optional(z.enum(["general","news"])),
  "days": z.optional(z.number()),
  "includeDomains": z.optional(z.array(z.string())),
  "excludeDomains": z.optional(z.array(z.string())),
})) as z.ZodType<PlatformWebSearchDto>;
export const PlatformWebSearchDto$outboundSchema = (z.object({
  "query": z.string(),
  "maxResults": z.optional(z.number()),
  "searchDepth": z.optional(z.enum(["basic","advanced"])),
  "topic": z.optional(z.enum(["general","news"])),
  "days": z.optional(z.number()),
  "includeDomains": z.optional(z.array(z.string())),
  "excludeDomains": z.optional(z.array(z.string())),
})) as z.ZodType<PlatformWebSearchDto$Outbound>;

export function platformWebSearchDtoFromJSON(jsonString: string): PlatformWebSearchDto {
  return PlatformWebSearchDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformWebSearchDto;
}

export function platformWebSearchDtoToJSON(value: PlatformWebSearchDto): string {
  return JSON.stringify(PlatformWebSearchDto$outboundSchema.parse(value));
}
