/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformInstagramPostDetailsDto = {
  "postUrl": string;
};
export type PlatformInstagramPostDetailsDto$Outbound = PlatformInstagramPostDetailsDto;

export const PlatformInstagramPostDetailsDto$inboundSchema = (z.object({
  "postUrl": z.string(),
})) as z.ZodType<PlatformInstagramPostDetailsDto>;
export const PlatformInstagramPostDetailsDto$outboundSchema = (z.object({
  "postUrl": z.string(),
})) as z.ZodType<PlatformInstagramPostDetailsDto$Outbound>;

export function platformInstagramPostDetailsDtoFromJSON(jsonString: string): PlatformInstagramPostDetailsDto {
  return PlatformInstagramPostDetailsDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformInstagramPostDetailsDto;
}

export function platformInstagramPostDetailsDtoToJSON(value: PlatformInstagramPostDetailsDto): string {
  return JSON.stringify(PlatformInstagramPostDetailsDto$outboundSchema.parse(value));
}
