/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformLinkedInCompanyPostsDto = {
  companySlug: string;
  limit?: number | undefined;
};

/** @internal */
export type PlatformLinkedInCompanyPostsDto$Outbound = {
  companySlug: string;
  limit: number;
};

/** @internal */
export const PlatformLinkedInCompanyPostsDto$outboundSchema: z.ZodMiniType<
  PlatformLinkedInCompanyPostsDto$Outbound,
  PlatformLinkedInCompanyPostsDto
> = z.object({
  companySlug: z.string(),
  limit: z._default(z.number(), 20),
});

export function platformLinkedInCompanyPostsDtoToJSON(
  platformLinkedInCompanyPostsDto: PlatformLinkedInCompanyPostsDto,
): string {
  return JSON.stringify(
    PlatformLinkedInCompanyPostsDto$outboundSchema.parse(
      platformLinkedInCompanyPostsDto,
    ),
  );
}
