/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformInstagramUsernameDto = {
  "username": string;
  "maxPosts"?: number;
};
export type PlatformInstagramUsernameDto$Outbound = PlatformInstagramUsernameDto;

export const PlatformInstagramUsernameDto$inboundSchema = (z.object({
  "username": z.string(),
  "maxPosts": z.optional(z.number()),
})) as z.ZodType<PlatformInstagramUsernameDto>;
export const PlatformInstagramUsernameDto$outboundSchema = (z.object({
  "username": z.string(),
  "maxPosts": z.optional(z.number()),
})) as z.ZodType<PlatformInstagramUsernameDto$Outbound>;

export function platformInstagramUsernameDtoFromJSON(jsonString: string): PlatformInstagramUsernameDto {
  return PlatformInstagramUsernameDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformInstagramUsernameDto;
}

export function platformInstagramUsernameDtoToJSON(value: PlatformInstagramUsernameDto): string {
  return JSON.stringify(PlatformInstagramUsernameDto$outboundSchema.parse(value));
}
