/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformLinkedInFinderDto = {
  "domains": string[];
};
export type PlatformLinkedInFinderDto$Outbound = PlatformLinkedInFinderDto;

export const PlatformLinkedInFinderDto$inboundSchema = (z.object({
  "domains": z.array(z.string()),
})) as z.ZodType<PlatformLinkedInFinderDto>;
export const PlatformLinkedInFinderDto$outboundSchema = (z.object({
  "domains": z.array(z.string()),
})) as z.ZodType<PlatformLinkedInFinderDto$Outbound>;

export function platformLinkedInFinderDtoFromJSON(jsonString: string): PlatformLinkedInFinderDto {
  return PlatformLinkedInFinderDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformLinkedInFinderDto;
}

export function platformLinkedInFinderDtoToJSON(value: PlatformLinkedInFinderDto): string {
  return JSON.stringify(PlatformLinkedInFinderDto$outboundSchema.parse(value));
}
