/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformWebScrapeDto = {
  "url": string;
  "renderJs"?: boolean;
  "maxAgeMs"?: number;
  "maxAgeDays"?: number;
};
export type PlatformWebScrapeDto$Outbound = PlatformWebScrapeDto;

export const PlatformWebScrapeDto$inboundSchema = (z.object({
  "url": z.string(),
  "renderJs": z.optional(z.boolean()),
  "maxAgeMs": z.optional(z.number()),
  "maxAgeDays": z.optional(z.number()),
})) as z.ZodType<PlatformWebScrapeDto>;
export const PlatformWebScrapeDto$outboundSchema = (z.object({
  "url": z.string(),
  "renderJs": z.optional(z.boolean()),
  "maxAgeMs": z.optional(z.number()),
  "maxAgeDays": z.optional(z.number()),
})) as z.ZodType<PlatformWebScrapeDto$Outbound>;

export function platformWebScrapeDtoFromJSON(jsonString: string): PlatformWebScrapeDto {
  return PlatformWebScrapeDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformWebScrapeDto;
}

export function platformWebScrapeDtoToJSON(value: PlatformWebScrapeDto): string {
  return JSON.stringify(PlatformWebScrapeDto$outboundSchema.parse(value));
}
