/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformLinkedInProfileDto = {
  "username": string;
};
export type PlatformLinkedInProfileDto$Outbound = PlatformLinkedInProfileDto;

export const PlatformLinkedInProfileDto$inboundSchema = (z.object({
  "username": z.string(),
})) as z.ZodType<PlatformLinkedInProfileDto>;
export const PlatformLinkedInProfileDto$outboundSchema = (z.object({
  "username": z.string(),
})) as z.ZodType<PlatformLinkedInProfileDto$Outbound>;

export function platformLinkedInProfileDtoFromJSON(jsonString: string): PlatformLinkedInProfileDto {
  return PlatformLinkedInProfileDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformLinkedInProfileDto;
}

export function platformLinkedInProfileDtoToJSON(value: PlatformLinkedInProfileDto): string {
  return JSON.stringify(PlatformLinkedInProfileDto$outboundSchema.parse(value));
}
