/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformInstagramFollowersDto = {
  username: string;
  /**
   * Maximum followers to request. Unlimited is not exposed on v1.
   */
  maxFollowers?: number | undefined;
};

/** @internal */
export type PlatformInstagramFollowersDto$Outbound = {
  username: string;
  maxFollowers?: number | undefined;
};

/** @internal */
export const PlatformInstagramFollowersDto$outboundSchema: z.ZodMiniType<
  PlatformInstagramFollowersDto$Outbound,
  PlatformInstagramFollowersDto
> = z.object({
  username: z.string(),
  maxFollowers: z.optional(z.number()),
});

export function platformInstagramFollowersDtoToJSON(
  platformInstagramFollowersDto: PlatformInstagramFollowersDto,
): string {
  return JSON.stringify(
    PlatformInstagramFollowersDto$outboundSchema.parse(
      platformInstagramFollowersDto,
    ),
  );
}
