/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformLinkedInProfilePostsDto = {
  "username": string;
  "maxPosts"?: number;
};
export type PlatformLinkedInProfilePostsDto$Outbound = PlatformLinkedInProfilePostsDto;

export const PlatformLinkedInProfilePostsDto$inboundSchema = (z.object({
  "username": z.string(),
  "maxPosts": z.optional(z.number()),
})) as z.ZodType<PlatformLinkedInProfilePostsDto>;
export const PlatformLinkedInProfilePostsDto$outboundSchema = (z.object({
  "username": z.string(),
  "maxPosts": z.optional(z.number()),
})) as z.ZodType<PlatformLinkedInProfilePostsDto$Outbound>;

export function platformLinkedInProfilePostsDtoFromJSON(jsonString: string): PlatformLinkedInProfilePostsDto {
  return PlatformLinkedInProfilePostsDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformLinkedInProfilePostsDto;
}

export function platformLinkedInProfilePostsDtoToJSON(value: PlatformLinkedInProfilePostsDto): string {
  return JSON.stringify(PlatformLinkedInProfilePostsDto$outboundSchema.parse(value));
}
