/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PlatformWebCrawlDto = {
  /**
   * Domain or URL to crawl
   */
  url: string;
  limit?: number | undefined;
  /**
   * Instructions for content extraction
   */
  instructions?: string | undefined;
};

/** @internal */
export type PlatformWebCrawlDto$Outbound = {
  url: string;
  limit: number;
  instructions?: string | undefined;
};

/** @internal */
export const PlatformWebCrawlDto$outboundSchema: z.ZodMiniType<
  PlatformWebCrawlDto$Outbound,
  PlatformWebCrawlDto
> = z.object({
  url: z.string(),
  limit: z._default(z.number(), 5),
  instructions: z.optional(z.string()),
});

export function platformWebCrawlDtoToJSON(
  platformWebCrawlDto: PlatformWebCrawlDto,
): string {
  return JSON.stringify(
    PlatformWebCrawlDto$outboundSchema.parse(platformWebCrawlDto),
  );
}
