/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PlatformLinkedInPostUrlsDto = {
  "postUrls": string[];
  "maxItems"?: number;
};
export type PlatformLinkedInPostUrlsDto$Outbound = PlatformLinkedInPostUrlsDto;

export const PlatformLinkedInPostUrlsDto$inboundSchema = (z.object({
  "postUrls": z.array(z.string()),
  "maxItems": z.optional(z.number()),
})) as z.ZodType<PlatformLinkedInPostUrlsDto>;
export const PlatformLinkedInPostUrlsDto$outboundSchema = (z.object({
  "postUrls": z.array(z.string()),
  "maxItems": z.optional(z.number()),
})) as z.ZodType<PlatformLinkedInPostUrlsDto$Outbound>;

export function platformLinkedInPostUrlsDtoFromJSON(jsonString: string): PlatformLinkedInPostUrlsDto {
  return PlatformLinkedInPostUrlsDto$inboundSchema.parse(JSON.parse(jsonString)) as PlatformLinkedInPostUrlsDto;
}

export function platformLinkedInPostUrlsDtoToJSON(value: PlatformLinkedInPostUrlsDto): string {
  return JSON.stringify(PlatformLinkedInPostUrlsDto$outboundSchema.parse(value));
}
