/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PostSearchDto = {
  "type": "web_search" | "site_search" | "linkedin_keyword" | "x_keyword" | "reddit_search" | "tiktok_keyword" | "tiktok_hashtag";
  "query"?: string;
  "match_any"?: string[];
  "match_all"?: string[];
  "exclude"?: string[];
  "max_results"?: number;
  "site"?: string;
  "include_domains"?: string[];
  "exclude_domains"?: string[];
  "sort_by"?: "relevance" | "recent";
  "match_mode"?: "exact" | "broad";
  "date_filter"?: string;
  "hashtag"?: string;
  "subreddit"?: string;
};
export type PostSearchDto$Outbound = PostSearchDto;

export const PostSearchDto$inboundSchema = (z.object({
  "type": z.enum(["web_search","site_search","linkedin_keyword","x_keyword","reddit_search","tiktok_keyword","tiktok_hashtag"]),
  "query": z.optional(z.string()),
  "match_any": z.optional(z.array(z.string())),
  "match_all": z.optional(z.array(z.string())),
  "exclude": z.optional(z.array(z.string())),
  "max_results": z.optional(z.number()),
  "site": z.optional(z.string()),
  "include_domains": z.optional(z.array(z.string())),
  "exclude_domains": z.optional(z.array(z.string())),
  "sort_by": z.optional(z.enum(["relevance","recent"])),
  "match_mode": z.optional(z.enum(["exact","broad"])),
  "date_filter": z.optional(z.string()),
  "hashtag": z.optional(z.string()),
  "subreddit": z.optional(z.string()),
})) as z.ZodType<PostSearchDto>;
export const PostSearchDto$outboundSchema = (z.object({
  "type": z.enum(["web_search","site_search","linkedin_keyword","x_keyword","reddit_search","tiktok_keyword","tiktok_hashtag"]),
  "query": z.optional(z.string()),
  "match_any": z.optional(z.array(z.string())),
  "match_all": z.optional(z.array(z.string())),
  "exclude": z.optional(z.array(z.string())),
  "max_results": z.optional(z.number()),
  "site": z.optional(z.string()),
  "include_domains": z.optional(z.array(z.string())),
  "exclude_domains": z.optional(z.array(z.string())),
  "sort_by": z.optional(z.enum(["relevance","recent"])),
  "match_mode": z.optional(z.enum(["exact","broad"])),
  "date_filter": z.optional(z.string()),
  "hashtag": z.optional(z.string()),
  "subreddit": z.optional(z.string()),
})) as z.ZodType<PostSearchDto$Outbound>;

export function postSearchDtoFromJSON(jsonString: string): PostSearchDto {
  return PostSearchDto$inboundSchema.parse(JSON.parse(jsonString)) as PostSearchDto;
}

export function postSearchDtoToJSON(value: PostSearchDto): string {
  return JSON.stringify(PostSearchDto$outboundSchema.parse(value));
}
