/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { EntitySearchFiltersDto } from "./entity-search-filters-dto.js";
import { EntitySearchFiltersDto$inboundSchema, EntitySearchFiltersDto$outboundSchema } from "./entity-search-filters-dto.js";

export type PostPeopleSearchDto = {
  "query": string;
  "limit"?: number;
  "includeSignals"?: boolean;
  "includeContacts"?: boolean;
  "filters"?: EntitySearchFiltersDto;
};
export type PostPeopleSearchDto$Outbound = PostPeopleSearchDto;

export const PostPeopleSearchDto$inboundSchema = (z.object({
  "query": z.string(),
  "limit": z.optional(z.number()),
  "includeSignals": z.optional(z.boolean()),
  "includeContacts": z.optional(z.boolean()),
  "filters": z.optional(z.lazy(() => EntitySearchFiltersDto$inboundSchema)),
})) as z.ZodType<PostPeopleSearchDto>;
export const PostPeopleSearchDto$outboundSchema = (z.object({
  "query": z.string(),
  "limit": z.optional(z.number()),
  "includeSignals": z.optional(z.boolean()),
  "includeContacts": z.optional(z.boolean()),
  "filters": z.optional(z.lazy(() => EntitySearchFiltersDto$outboundSchema)),
})) as z.ZodType<PostPeopleSearchDto$Outbound>;

export function postPeopleSearchDtoFromJSON(jsonString: string): PostPeopleSearchDto {
  return PostPeopleSearchDto$inboundSchema.parse(JSON.parse(jsonString)) as PostPeopleSearchDto;
}

export function postPeopleSearchDtoToJSON(value: PostPeopleSearchDto): string {
  return JSON.stringify(PostPeopleSearchDto$outboundSchema.parse(value));
}
