/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { EntitySearchFiltersDto } from "./entity-search-filters-dto.js";
import { EntitySearchFiltersDto$inboundSchema, EntitySearchFiltersDto$outboundSchema } from "./entity-search-filters-dto.js";

export type PostCompanySearchDto = {
  "query": string;
  "limit"?: number;
  "includeSignals"?: boolean;
  "filters"?: EntitySearchFiltersDto;
};
export type PostCompanySearchDto$Outbound = PostCompanySearchDto;

export const PostCompanySearchDto$inboundSchema = (z.object({
  "query": z.string(),
  "limit": z.optional(z.number()),
  "includeSignals": z.optional(z.boolean()),
  "filters": z.optional(z.lazy(() => EntitySearchFiltersDto$inboundSchema)),
})) as z.ZodType<PostCompanySearchDto>;
export const PostCompanySearchDto$outboundSchema = (z.object({
  "query": z.string(),
  "limit": z.optional(z.number()),
  "includeSignals": z.optional(z.boolean()),
  "filters": z.optional(z.lazy(() => EntitySearchFiltersDto$outboundSchema)),
})) as z.ZodType<PostCompanySearchDto$Outbound>;

export function postCompanySearchDtoFromJSON(jsonString: string): PostCompanySearchDto {
  return PostCompanySearchDto$inboundSchema.parse(JSON.parse(jsonString)) as PostCompanySearchDto;
}

export function postCompanySearchDtoToJSON(value: PostCompanySearchDto): string {
  return JSON.stringify(PostCompanySearchDto$outboundSchema.parse(value));
}
