/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of search to perform
 */
export const PostSearchDtoType = {
  WebSearch: "web_search",
  SiteSearch: "site_search",
  LinkedinKeyword: "linkedin_keyword",
  XKeyword: "x_keyword",
  RedditSearch: "reddit_search",
  TiktokKeyword: "tiktok_keyword",
  TiktokHashtag: "tiktok_hashtag",
} as const;
/**
 * Type of search to perform
 */
export type PostSearchDtoType = ClosedEnum<typeof PostSearchDtoType>;

/**
 * Sort by: relevance or recent (keyword searches only)
 */
export const SortBy = {
  Relevance: "relevance",
  Recent: "recent",
} as const;
/**
 * Sort by: relevance or recent (keyword searches only)
 */
export type SortBy = ClosedEnum<typeof SortBy>;

/**
 * Match mode for LinkedIn keyword searches. exact searches the query as a quoted phrase; broad sends the query without phrase quotes.
 */
export const MatchMode = {
  Exact: "exact",
  Broad: "broad",
} as const;
/**
 * Match mode for LinkedIn keyword searches. exact searches the query as a quoted phrase; broad sends the query without phrase quotes.
 */
export type MatchMode = ClosedEnum<typeof MatchMode>;

export type PostSearchDto = {
  /**
   * Type of search to perform
   */
  type: PostSearchDtoType;
  /**
   * Search query string. Required unless match_any/match_all are provided.
   */
  query?: string | undefined;
  /**
   * Keywords where ANY must match (OR logic). Used to build search query.
   */
  matchAny?: Array<string> | undefined;
  /**
   * Keywords where ALL must match (AND logic). Used to build search query.
   */
  matchAll?: Array<string> | undefined;
  /**
   * Keywords to exclude from results.
   */
  exclude?: Array<string> | undefined;
  /**
   * Maximum results to return (default 10, max 50)
   */
  maxResults?: number | undefined;
  /**
   * Domain to restrict search to (required for site_search)
   */
  site?: string | undefined;
  /**
   * Domains to include results from (web_search only)
   */
  includeDomains?: Array<string> | undefined;
  /**
   * Domains to exclude results from (web_search only)
   */
  excludeDomains?: Array<string> | undefined;
  /**
   * Sort by: relevance or recent (keyword searches only)
   */
  sortBy?: SortBy | undefined;
  /**
   * Match mode for LinkedIn keyword searches. exact searches the query as a quoted phrase; broad sends the query without phrase quotes.
   */
  matchMode?: MatchMode | undefined;
  /**
   * Date filter for LinkedIn search (e.g. past-24h, past-week)
   */
  dateFilter?: string | undefined;
  /**
   * Project ID for attribution
   */
  projectId?: string | undefined;
  /**
   * Hashtag to search for (required for tiktok_hashtag type, without # prefix)
   */
  hashtag?: string | undefined;
  /**
   * Subreddit to search within (reddit_search only)
   */
  subreddit?: string | undefined;
};

/** @internal */
export const PostSearchDtoType$outboundSchema: z.ZodMiniEnum<
  typeof PostSearchDtoType
> = z.enum(PostSearchDtoType);

/** @internal */
export const SortBy$outboundSchema: z.ZodMiniEnum<typeof SortBy> = z.enum(
  SortBy,
);

/** @internal */
export const MatchMode$outboundSchema: z.ZodMiniEnum<typeof MatchMode> = z.enum(
  MatchMode,
);

/** @internal */
export type PostSearchDto$Outbound = {
  type: string;
  query?: string | undefined;
  match_any?: Array<string> | undefined;
  match_all?: Array<string> | undefined;
  exclude?: Array<string> | undefined;
  max_results: number;
  site?: string | undefined;
  include_domains?: Array<string> | undefined;
  exclude_domains?: Array<string> | undefined;
  sort_by: string;
  match_mode: string;
  date_filter?: string | undefined;
  project_id?: string | undefined;
  hashtag?: string | undefined;
  subreddit?: string | undefined;
};

/** @internal */
export const PostSearchDto$outboundSchema: z.ZodMiniType<
  PostSearchDto$Outbound,
  PostSearchDto
> = z.pipe(
  z.object({
    type: PostSearchDtoType$outboundSchema,
    query: z.optional(z.string()),
    matchAny: z.optional(z.array(z.string())),
    matchAll: z.optional(z.array(z.string())),
    exclude: z.optional(z.array(z.string())),
    maxResults: z._default(z.number(), 10),
    site: z.optional(z.string()),
    includeDomains: z.optional(z.array(z.string())),
    excludeDomains: z.optional(z.array(z.string())),
    sortBy: z._default(SortBy$outboundSchema, "relevance"),
    matchMode: z._default(MatchMode$outboundSchema, "exact"),
    dateFilter: z.optional(z.string()),
    projectId: z.optional(z.string()),
    hashtag: z.optional(z.string()),
    subreddit: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      matchAny: "match_any",
      matchAll: "match_all",
      maxResults: "max_results",
      includeDomains: "include_domains",
      excludeDomains: "exclude_domains",
      sortBy: "sort_by",
      matchMode: "match_mode",
      dateFilter: "date_filter",
      projectId: "project_id",
    });
  }),
);

export function postSearchDtoToJSON(postSearchDto: PostSearchDto): string {
  return JSON.stringify(PostSearchDto$outboundSchema.parse(postSearchDto));
}
