/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  PersonIdentifierRecordDto,
  PersonIdentifierRecordDto$Outbound,
  PersonIdentifierRecordDto$outboundSchema,
} from "./person-identifier-record-dto.js";
import {
  SignalsConfigDto,
  SignalsConfigDto$Outbound,
  SignalsConfigDto$outboundSchema,
} from "./signals-config-dto.js";

export type PostEnrichmentDto = {
  /**
   * Single person (mutually exclusive with identifiers)
   */
  identifier?: PersonIdentifierRecordDto | undefined;
  /**
   * Batch (max 100); mutually exclusive with identifier
   */
  identifiers?: Array<PersonIdentifierRecordDto> | undefined;
  fields: Array<string>;
  signalsConfig?: SignalsConfigDto | undefined;
};

/** @internal */
export type PostEnrichmentDto$Outbound = {
  identifier?: PersonIdentifierRecordDto$Outbound | undefined;
  identifiers?: Array<PersonIdentifierRecordDto$Outbound> | undefined;
  fields: Array<string>;
  signals_config?: SignalsConfigDto$Outbound | undefined;
};

/** @internal */
export const PostEnrichmentDto$outboundSchema: z.ZodMiniType<
  PostEnrichmentDto$Outbound,
  PostEnrichmentDto
> = z.pipe(
  z.object({
    identifier: z.optional(PersonIdentifierRecordDto$outboundSchema),
    identifiers: z.optional(z.array(PersonIdentifierRecordDto$outboundSchema)),
    fields: z.array(z.string()),
    signalsConfig: z.optional(SignalsConfigDto$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      signalsConfig: "signals_config",
    });
  }),
);

export function postEnrichmentDtoToJSON(
  postEnrichmentDto: PostEnrichmentDto,
): string {
  return JSON.stringify(
    PostEnrichmentDto$outboundSchema.parse(postEnrichmentDto),
  );
}
