/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  EntitySearchFiltersDto,
  EntitySearchFiltersDto$Outbound,
  EntitySearchFiltersDto$outboundSchema,
} from "./entity-search-filters-dto.js";

export type PostCompanySearchDto = {
  query: string;
  limit?: number | undefined;
  includeSignals?: boolean | undefined;
  filters?: EntitySearchFiltersDto | undefined;
  /**
   * Project context handle.
   */
  projectId?: string | undefined;
};

/** @internal */
export type PostCompanySearchDto$Outbound = {
  query: string;
  limit: number;
  includeSignals: boolean;
  filters?: EntitySearchFiltersDto$Outbound | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const PostCompanySearchDto$outboundSchema: z.ZodMiniType<
  PostCompanySearchDto$Outbound,
  PostCompanySearchDto
> = z.object({
  query: z.string(),
  limit: z._default(z.number(), 25),
  includeSignals: z._default(z.boolean(), false),
  filters: z.optional(EntitySearchFiltersDto$outboundSchema),
  projectId: z.optional(z.string()),
});

export function postCompanySearchDtoToJSON(
  postCompanySearchDto: PostCompanySearchDto,
): string {
  return JSON.stringify(
    PostCompanySearchDto$outboundSchema.parse(postCompanySearchDto),
  );
}
