/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PersonIdentifierRecordDto } from "./person-identifier-record-dto.js";
import { PersonIdentifierRecordDto$inboundSchema, PersonIdentifierRecordDto$outboundSchema } from "./person-identifier-record-dto.js";
import type { SignalsConfigDto } from "./signals-config-dto.js";
import { SignalsConfigDto$inboundSchema, SignalsConfigDto$outboundSchema } from "./signals-config-dto.js";

export type PostEnrichmentDto = {
  "identifier"?: (PersonIdentifierRecordDto);
  "identifiers"?: PersonIdentifierRecordDto[];
  "fields": string[];
  "signals_config"?: SignalsConfigDto;
};
export type PostEnrichmentDto$Outbound = PostEnrichmentDto;

export const PostEnrichmentDto$inboundSchema = (z.object({
  "identifier": z.optional(z.lazy(() => PersonIdentifierRecordDto$inboundSchema)),
  "identifiers": z.optional(z.array(z.lazy(() => PersonIdentifierRecordDto$inboundSchema))),
  "fields": z.array(z.string()),
  "signals_config": z.optional(z.lazy(() => SignalsConfigDto$inboundSchema)),
})) as z.ZodType<PostEnrichmentDto>;
export const PostEnrichmentDto$outboundSchema = (z.object({
  "identifier": z.optional(z.lazy(() => PersonIdentifierRecordDto$outboundSchema)),
  "identifiers": z.optional(z.array(z.lazy(() => PersonIdentifierRecordDto$outboundSchema))),
  "fields": z.array(z.string()),
  "signals_config": z.optional(z.lazy(() => SignalsConfigDto$outboundSchema)),
})) as z.ZodType<PostEnrichmentDto$Outbound>;

export function postEnrichmentDtoFromJSON(jsonString: string): PostEnrichmentDto {
  return PostEnrichmentDto$inboundSchema.parse(JSON.parse(jsonString)) as PostEnrichmentDto;
}

export function postEnrichmentDtoToJSON(value: PostEnrichmentDto): string {
  return JSON.stringify(PostEnrichmentDto$outboundSchema.parse(value));
}
