/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  EntitySearchFiltersDto,
  EntitySearchFiltersDto$Outbound,
  EntitySearchFiltersDto$outboundSchema,
} from "./entity-search-filters-dto.js";

export type PostPeopleSearchDto = {
  query: string;
  limit?: number | undefined;
  includeSignals?: boolean | undefined;
  includeContacts?: boolean | undefined;
  filters?: EntitySearchFiltersDto | undefined;
  /**
   * Project context handle.
   */
  projectId?: string | undefined;
};

/** @internal */
export type PostPeopleSearchDto$Outbound = {
  query: string;
  limit: number;
  includeSignals: boolean;
  includeContacts: boolean;
  filters?: EntitySearchFiltersDto$Outbound | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const PostPeopleSearchDto$outboundSchema: z.ZodMiniType<
  PostPeopleSearchDto$Outbound,
  PostPeopleSearchDto
> = z.object({
  query: z.string(),
  limit: z._default(z.number(), 25),
  includeSignals: z._default(z.boolean(), false),
  includeContacts: z._default(z.boolean(), false),
  filters: z.optional(EntitySearchFiltersDto$outboundSchema),
  projectId: z.optional(z.string()),
});

export function postPeopleSearchDtoToJSON(
  postPeopleSearchDto: PostPeopleSearchDto,
): string {
  return JSON.stringify(
    PostPeopleSearchDto$outboundSchema.parse(postPeopleSearchDto),
  );
}
