/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PublicValidationErrorItemDto } from "./public-validation-error-item-dto.js";
import { PublicValidationErrorItemDto$inboundSchema, PublicValidationErrorItemDto$outboundSchema } from "./public-validation-error-item-dto.js";

export type PublicErrorResponseDto = {
  "statusCode": number;
  "error": string;
  "message": string;
  "path": string;
  "requestId"?: string;
  "timestamp": string;
  "errors"?: PublicValidationErrorItemDto[];
};
export type PublicErrorResponseDto$Outbound = PublicErrorResponseDto;

export const PublicErrorResponseDto$inboundSchema = (z.object({
  "statusCode": z.number(),
  "error": z.string(),
  "message": z.string(),
  "path": z.string(),
  "requestId": z.optional(z.string()),
  "timestamp": z.string(),
  "errors": z.optional(z.array(z.lazy(() => PublicValidationErrorItemDto$inboundSchema))),
})) as z.ZodType<PublicErrorResponseDto>;
export const PublicErrorResponseDto$outboundSchema = (z.object({
  "statusCode": z.number(),
  "error": z.string(),
  "message": z.string(),
  "path": z.string(),
  "requestId": z.optional(z.string()),
  "timestamp": z.string(),
  "errors": z.optional(z.array(z.lazy(() => PublicValidationErrorItemDto$outboundSchema))),
})) as z.ZodType<PublicErrorResponseDto$Outbound>;

export function publicErrorResponseDtoFromJSON(jsonString: string): PublicErrorResponseDto {
  return PublicErrorResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as PublicErrorResponseDto;
}

export function publicErrorResponseDtoToJSON(value: PublicErrorResponseDto): string {
  return JSON.stringify(PublicErrorResponseDto$outboundSchema.parse(value));
}
