/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PublicValidationErrorItemDto = {
  "property": string;
  "message": string;
  "constraints"?: {
  [key: string]: string;
};
};
export type PublicValidationErrorItemDto$Outbound = PublicValidationErrorItemDto;

export const PublicValidationErrorItemDto$inboundSchema = (z.object({
  "property": z.string(),
  "message": z.string(),
  "constraints": z.optional(z.record(z.string(), z.string())),
})) as z.ZodType<PublicValidationErrorItemDto>;
export const PublicValidationErrorItemDto$outboundSchema = (z.object({
  "property": z.string(),
  "message": z.string(),
  "constraints": z.optional(z.record(z.string(), z.string())),
})) as z.ZodType<PublicValidationErrorItemDto$Outbound>;

export function publicValidationErrorItemDtoFromJSON(jsonString: string): PublicValidationErrorItemDto {
  return PublicValidationErrorItemDto$inboundSchema.parse(JSON.parse(jsonString)) as PublicValidationErrorItemDto;
}

export function publicValidationErrorItemDtoToJSON(value: PublicValidationErrorItemDto): string {
  return JSON.stringify(PublicValidationErrorItemDto$outboundSchema.parse(value));
}
