/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublicResponseMetaDto = {
  requestId: string;
};

/** @internal */
export const PublicResponseMetaDto$inboundSchema: z.ZodMiniType<
  PublicResponseMetaDto,
  unknown
> = z.object({
  requestId: types.string(),
});

export function publicResponseMetaDtoFromJSON(
  jsonString: string,
): SafeParseResult<PublicResponseMetaDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicResponseMetaDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicResponseMetaDto' from JSON`,
  );
}
