/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type PublicResponseMetaDto = {
  "requestId": string;
};
export type PublicResponseMetaDto$Outbound = PublicResponseMetaDto;

export const PublicResponseMetaDto$inboundSchema = (z.object({
  "requestId": z.string(),
})) as z.ZodType<PublicResponseMetaDto>;
export const PublicResponseMetaDto$outboundSchema = (z.object({
  "requestId": z.string(),
})) as z.ZodType<PublicResponseMetaDto$Outbound>;

export function publicResponseMetaDtoFromJSON(jsonString: string): PublicResponseMetaDto {
  return PublicResponseMetaDto$inboundSchema.parse(JSON.parse(jsonString)) as PublicResponseMetaDto;
}

export function publicResponseMetaDtoToJSON(value: PublicResponseMetaDto): string {
  return JSON.stringify(PublicResponseMetaDto$outboundSchema.parse(value));
}
