/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublicValidationErrorItemDto = {
  property: string;
  message: string;
  constraints?: { [k: string]: string } | undefined;
};

/** @internal */
export const PublicValidationErrorItemDto$inboundSchema: z.ZodMiniType<
  PublicValidationErrorItemDto,
  unknown
> = z.object({
  property: types.string(),
  message: types.string(),
  constraints: types.optional(z.record(z.string(), types.string())),
});

export function publicValidationErrorItemDtoFromJSON(
  jsonString: string,
): SafeParseResult<PublicValidationErrorItemDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicValidationErrorItemDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicValidationErrorItemDto' from JSON`,
  );
}
