/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type RunNowBodyDto = {
  "force_fresh"?: boolean;
};
export type RunNowBodyDto$Outbound = RunNowBodyDto;

export const RunNowBodyDto$inboundSchema = (z.object({
  "force_fresh": z.optional(z.boolean()),
})) as z.ZodType<RunNowBodyDto>;
export const RunNowBodyDto$outboundSchema = (z.object({
  "force_fresh": z.optional(z.boolean()),
})) as z.ZodType<RunNowBodyDto$Outbound>;

export function runNowBodyDtoFromJSON(jsonString: string): RunNowBodyDto {
  return RunNowBodyDto$inboundSchema.parse(JSON.parse(jsonString)) as RunNowBodyDto;
}

export function runNowBodyDtoToJSON(value: RunNowBodyDto): string {
  return JSON.stringify(RunNowBodyDto$outboundSchema.parse(value));
}
