/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type RunNowBodyDto = {
  /**
   * Force a fresh scrape for this run, bypassing cache
   */
  forceFresh?: boolean | undefined;
};

/** @internal */
export type RunNowBodyDto$Outbound = {
  force_fresh?: boolean | undefined;
};

/** @internal */
export const RunNowBodyDto$outboundSchema: z.ZodMiniType<
  RunNowBodyDto$Outbound,
  RunNowBodyDto
> = z.pipe(
  z.object({
    forceFresh: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      forceFresh: "force_fresh",
    });
  }),
);

export function runNowBodyDtoToJSON(runNowBodyDto: RunNowBodyDto): string {
  return JSON.stringify(RunNowBodyDto$outboundSchema.parse(runNowBodyDto));
}
