/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";
import type { WebScrapeResponseDto } from "./web-scrape-response-dto.js";
import { WebScrapeResponseDto$inboundSchema, WebScrapeResponseDto$outboundSchema } from "./web-scrape-response-dto.js";

export type ScrapeWebPageResponse = {
  "data": WebScrapeResponseDto;
  "meta": PublicResponseMetaDto;
};
export type ScrapeWebPageResponse$Outbound = ScrapeWebPageResponse;

export const ScrapeWebPageResponse$inboundSchema = (z.object({
  "data": z.lazy(() => WebScrapeResponseDto$inboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<ScrapeWebPageResponse>;
export const ScrapeWebPageResponse$outboundSchema = (z.object({
  "data": z.lazy(() => WebScrapeResponseDto$outboundSchema),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<ScrapeWebPageResponse$Outbound>;

export function scrapeWebPageResponseFromJSON(jsonString: string): ScrapeWebPageResponse {
  return ScrapeWebPageResponse$inboundSchema.parse(JSON.parse(jsonString)) as ScrapeWebPageResponse;
}

export function scrapeWebPageResponseToJSON(value: ScrapeWebPageResponse): string {
  return JSON.stringify(ScrapeWebPageResponse$outboundSchema.parse(value));
}
