/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SearchAcceptedMetaDto,
  SearchAcceptedMetaDto$inboundSchema,
} from "./search-accepted-meta-dto.js";

export const SearchAcceptedDtoStatus = {
  Queued: "queued",
} as const;
export type SearchAcceptedDtoStatus = ClosedEnum<
  typeof SearchAcceptedDtoStatus
>;

export type SearchAcceptedDto = {
  /**
   * Search operation ID
   */
  id: string;
  status: SearchAcceptedDtoStatus;
  /**
   * URL to poll for result
   */
  pollUrl: string;
  meta: SearchAcceptedMetaDto;
};

/** @internal */
export const SearchAcceptedDtoStatus$inboundSchema: z.ZodMiniEnum<
  typeof SearchAcceptedDtoStatus
> = z.enum(SearchAcceptedDtoStatus);

/** @internal */
export const SearchAcceptedDto$inboundSchema: z.ZodMiniType<
  SearchAcceptedDto,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    status: SearchAcceptedDtoStatus$inboundSchema,
    poll_url: types.string(),
    meta: SearchAcceptedMetaDto$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "poll_url": "pollUrl",
    });
  }),
);

export function searchAcceptedDtoFromJSON(
  jsonString: string,
): SafeParseResult<SearchAcceptedDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchAcceptedDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchAcceptedDto' from JSON`,
  );
}
