/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { LinkedInPostResponseDto } from "./linked-in-post-response-dto.js";
import { LinkedInPostResponseDto$inboundSchema, LinkedInPostResponseDto$outboundSchema } from "./linked-in-post-response-dto.js";
import type { PublicResponseMetaDto } from "./public-response-meta-dto.js";
import { PublicResponseMetaDto$inboundSchema, PublicResponseMetaDto$outboundSchema } from "./public-response-meta-dto.js";

export type SearchLinkedInKeywordPostsResponse = {
  "data": LinkedInPostResponseDto[];
  "meta": PublicResponseMetaDto;
};
export type SearchLinkedInKeywordPostsResponse$Outbound = SearchLinkedInKeywordPostsResponse;

export const SearchLinkedInKeywordPostsResponse$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInPostResponseDto$inboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$inboundSchema),
})) as z.ZodType<SearchLinkedInKeywordPostsResponse>;
export const SearchLinkedInKeywordPostsResponse$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => LinkedInPostResponseDto$outboundSchema)),
  "meta": z.lazy(() => PublicResponseMetaDto$outboundSchema),
})) as z.ZodType<SearchLinkedInKeywordPostsResponse$Outbound>;

export function searchLinkedInKeywordPostsResponseFromJSON(jsonString: string): SearchLinkedInKeywordPostsResponse {
  return SearchLinkedInKeywordPostsResponse$inboundSchema.parse(JSON.parse(jsonString)) as SearchLinkedInKeywordPostsResponse;
}

export function searchLinkedInKeywordPostsResponseToJSON(value: SearchLinkedInKeywordPostsResponse): string {
  return JSON.stringify(SearchLinkedInKeywordPostsResponse$outboundSchema.parse(value));
}
