/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { SearchAcceptedMetaDto } from "./search-accepted-meta-dto.js";
import { SearchAcceptedMetaDto$inboundSchema, SearchAcceptedMetaDto$outboundSchema } from "./search-accepted-meta-dto.js";

export type SearchAcceptedDto = {
  "id": string;
  "status": "queued";
  "poll_url": string;
  "meta": SearchAcceptedMetaDto;
};
export type SearchAcceptedDto$Outbound = SearchAcceptedDto;

export const SearchAcceptedDto$inboundSchema = (z.object({
  "id": z.string(),
  "status": z.enum(["queued"]),
  "poll_url": z.string(),
  "meta": z.lazy(() => SearchAcceptedMetaDto$inboundSchema),
})) as z.ZodType<SearchAcceptedDto>;
export const SearchAcceptedDto$outboundSchema = (z.object({
  "id": z.string(),
  "status": z.enum(["queued"]),
  "poll_url": z.string(),
  "meta": z.lazy(() => SearchAcceptedMetaDto$outboundSchema),
})) as z.ZodType<SearchAcceptedDto$Outbound>;

export function searchAcceptedDtoFromJSON(jsonString: string): SearchAcceptedDto {
  return SearchAcceptedDto$inboundSchema.parse(JSON.parse(jsonString)) as SearchAcceptedDto;
}

export function searchAcceptedDtoToJSON(value: SearchAcceptedDto): string {
  return JSON.stringify(SearchAcceptedDto$outboundSchema.parse(value));
}
