/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SearchResultDto,
  SearchResultDto$inboundSchema,
} from "./search-result-dto.js";

export type SearchListResponseDto = {
  data: Array<SearchResultDto>;
  nextCursor?: string | null | undefined;
};

/** @internal */
export const SearchListResponseDto$inboundSchema: z.ZodMiniType<
  SearchListResponseDto,
  unknown
> = z.pipe(
  z.object({
    data: z.array(SearchResultDto$inboundSchema),
    next_cursor: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function searchListResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<SearchListResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchListResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchListResponseDto' from JSON`,
  );
}
