/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { SearchResultDto } from "./search-result-dto.js";
import { SearchResultDto$inboundSchema, SearchResultDto$outboundSchema } from "./search-result-dto.js";

export type SearchListResponseDto = {
  "data": SearchResultDto[];
  "next_cursor"?: string | null;
};
export type SearchListResponseDto$Outbound = SearchListResponseDto;

export const SearchListResponseDto$inboundSchema = (z.object({
  "data": z.array(z.lazy(() => SearchResultDto$inboundSchema)),
  "next_cursor": z.optional(z.nullable(z.string())),
})) as z.ZodType<SearchListResponseDto>;
export const SearchListResponseDto$outboundSchema = (z.object({
  "data": z.array(z.lazy(() => SearchResultDto$outboundSchema)),
  "next_cursor": z.optional(z.nullable(z.string())),
})) as z.ZodType<SearchListResponseDto$Outbound>;

export function searchListResponseDtoFromJSON(jsonString: string): SearchListResponseDto {
  return SearchListResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as SearchListResponseDto;
}

export function searchListResponseDtoToJSON(value: SearchListResponseDto): string {
  return JSON.stringify(SearchListResponseDto$outboundSchema.parse(value));
}
