/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type SearchErrorDto = {
  "message": string;
  "retryable": boolean;
};
export type SearchErrorDto$Outbound = SearchErrorDto;

export const SearchErrorDto$inboundSchema = (z.object({
  "message": z.string(),
  "retryable": z.boolean(),
})) as z.ZodType<SearchErrorDto>;
export const SearchErrorDto$outboundSchema = (z.object({
  "message": z.string(),
  "retryable": z.boolean(),
})) as z.ZodType<SearchErrorDto$Outbound>;

export function searchErrorDtoFromJSON(jsonString: string): SearchErrorDto {
  return SearchErrorDto$inboundSchema.parse(JSON.parse(jsonString)) as SearchErrorDto;
}

export function searchErrorDtoToJSON(value: SearchErrorDto): string {
  return JSON.stringify(SearchErrorDto$outboundSchema.parse(value));
}
