/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type SearchAcceptedMetaDto = {
  "request_id": string;
};
export type SearchAcceptedMetaDto$Outbound = SearchAcceptedMetaDto;

export const SearchAcceptedMetaDto$inboundSchema = (z.object({
  "request_id": z.string(),
})) as z.ZodType<SearchAcceptedMetaDto>;
export const SearchAcceptedMetaDto$outboundSchema = (z.object({
  "request_id": z.string(),
})) as z.ZodType<SearchAcceptedMetaDto$Outbound>;

export function searchAcceptedMetaDtoFromJSON(jsonString: string): SearchAcceptedMetaDto {
  return SearchAcceptedMetaDto$inboundSchema.parse(JSON.parse(jsonString)) as SearchAcceptedMetaDto;
}

export function searchAcceptedMetaDtoToJSON(value: SearchAcceptedMetaDto): string {
  return JSON.stringify(SearchAcceptedMetaDto$outboundSchema.parse(value));
}
