/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SearchAcceptedMetaDto = {
  /**
   * Request ID for support and tracing
   */
  requestId: string;
};

/** @internal */
export const SearchAcceptedMetaDto$inboundSchema: z.ZodMiniType<
  SearchAcceptedMetaDto,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function searchAcceptedMetaDtoFromJSON(
  jsonString: string,
): SafeParseResult<SearchAcceptedMetaDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchAcceptedMetaDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchAcceptedMetaDto' from JSON`,
  );
}
