/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type Security = {
  "accessKey"?: string;
  "secretKey"?: string;
};
export type Security$Outbound = Security;

export const Security$inboundSchema = (z.object({
  "accessKey": z.optional(z.string()),
  "secretKey": z.optional(z.string()),
})) as z.ZodType<Security>;
export const Security$outboundSchema = (z.object({
  "accessKey": z.optional(z.string()),
  "secretKey": z.optional(z.string()),
})) as z.ZodType<Security$Outbound>;

export function securityFromJSON(jsonString: string): Security {
  return Security$inboundSchema.parse(JSON.parse(jsonString)) as Security;
}

export function securityToJSON(value: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(value));
}
