/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type SignalsConfigDto = {
  "platforms"?: string[];
  "max_posts"?: Record<string, unknown>;
  "intent_signals"?: string[];
  "since_days"?: number;
  "handles"?: Record<string, unknown>;
};
export type SignalsConfigDto$Outbound = SignalsConfigDto;

export const SignalsConfigDto$inboundSchema = (z.object({
  "platforms": z.optional(z.array(z.string())),
  "max_posts": z.optional(z.object({

})),
  "intent_signals": z.optional(z.array(z.string())),
  "since_days": z.optional(z.number()),
  "handles": z.optional(z.object({

})),
})) as z.ZodType<SignalsConfigDto>;
export const SignalsConfigDto$outboundSchema = (z.object({
  "platforms": z.optional(z.array(z.string())),
  "max_posts": z.optional(z.object({

})),
  "intent_signals": z.optional(z.array(z.string())),
  "since_days": z.optional(z.number()),
  "handles": z.optional(z.object({

})),
})) as z.ZodType<SignalsConfigDto$Outbound>;

export function signalsConfigDtoFromJSON(jsonString: string): SignalsConfigDto {
  return SignalsConfigDto$inboundSchema.parse(JSON.parse(jsonString)) as SignalsConfigDto;
}

export function signalsConfigDtoToJSON(value: SignalsConfigDto): string {
  return JSON.stringify(SignalsConfigDto$outboundSchema.parse(value));
}
