/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type MaxPosts = {};

export type Handles = {};

export type SignalsConfigDto = {
  /**
   * Opt-in platforms; omit or empty = all
   */
  platforms?: Array<string> | undefined;
  maxPosts?: MaxPosts | undefined;
  intentSignals?: Array<string> | undefined;
  sinceDays?: number | undefined;
  handles?: Handles | undefined;
};

/** @internal */
export type MaxPosts$Outbound = {};

/** @internal */
export const MaxPosts$outboundSchema: z.ZodMiniType<
  MaxPosts$Outbound,
  MaxPosts
> = z.object({});

export function maxPostsToJSON(maxPosts: MaxPosts): string {
  return JSON.stringify(MaxPosts$outboundSchema.parse(maxPosts));
}

/** @internal */
export type Handles$Outbound = {};

/** @internal */
export const Handles$outboundSchema: z.ZodMiniType<Handles$Outbound, Handles> =
  z.object({});

export function handlesToJSON(handles: Handles): string {
  return JSON.stringify(Handles$outboundSchema.parse(handles));
}

/** @internal */
export type SignalsConfigDto$Outbound = {
  platforms?: Array<string> | undefined;
  max_posts?: MaxPosts$Outbound | undefined;
  intent_signals?: Array<string> | undefined;
  since_days?: number | undefined;
  handles?: Handles$Outbound | undefined;
};

/** @internal */
export const SignalsConfigDto$outboundSchema: z.ZodMiniType<
  SignalsConfigDto$Outbound,
  SignalsConfigDto
> = z.pipe(
  z.object({
    platforms: z.optional(z.array(z.string())),
    maxPosts: z.optional(z.lazy(() => MaxPosts$outboundSchema)),
    intentSignals: z.optional(z.array(z.string())),
    sinceDays: z.optional(z.number()),
    handles: z.optional(z.lazy(() => Handles$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      maxPosts: "max_posts",
      intentSignals: "intent_signals",
      sinceDays: "since_days",
    });
  }),
);

export function signalsConfigDtoToJSON(
  signalsConfigDto: SignalsConfigDto,
): string {
  return JSON.stringify(
    SignalsConfigDto$outboundSchema.parse(signalsConfigDto),
  );
}
