/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { TikTokProfileSeedResponseDto } from "./tik-tok-profile-seed-response-dto.js";
import { TikTokProfileSeedResponseDto$inboundSchema, TikTokProfileSeedResponseDto$outboundSchema } from "./tik-tok-profile-seed-response-dto.js";
import type { TikTokVideoResponseDto } from "./tik-tok-video-response-dto.js";
import { TikTokVideoResponseDto$inboundSchema, TikTokVideoResponseDto$outboundSchema } from "./tik-tok-video-response-dto.js";

export type TikTokRelatedVideoResponseDto = {
  "relationship": "collaboration";
  "matched_username": string;
  "video": TikTokVideoResponseDto;
  "collaborators": TikTokProfileSeedResponseDto[];
};
export type TikTokRelatedVideoResponseDto$Outbound = TikTokRelatedVideoResponseDto;

export const TikTokRelatedVideoResponseDto$inboundSchema = (z.object({
  "relationship": z.enum(["collaboration"]),
  "matched_username": z.string(),
  "video": z.lazy(() => TikTokVideoResponseDto$inboundSchema),
  "collaborators": z.array(z.lazy(() => TikTokProfileSeedResponseDto$inboundSchema)),
})) as z.ZodType<TikTokRelatedVideoResponseDto>;
export const TikTokRelatedVideoResponseDto$outboundSchema = (z.object({
  "relationship": z.enum(["collaboration"]),
  "matched_username": z.string(),
  "video": z.lazy(() => TikTokVideoResponseDto$outboundSchema),
  "collaborators": z.array(z.lazy(() => TikTokProfileSeedResponseDto$outboundSchema)),
})) as z.ZodType<TikTokRelatedVideoResponseDto$Outbound>;

export function tikTokRelatedVideoResponseDtoFromJSON(jsonString: string): TikTokRelatedVideoResponseDto {
  return TikTokRelatedVideoResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as TikTokRelatedVideoResponseDto;
}

export function tikTokRelatedVideoResponseDtoToJSON(value: TikTokRelatedVideoResponseDto): string {
  return JSON.stringify(TikTokRelatedVideoResponseDto$outboundSchema.parse(value));
}
