/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TikTokVideoResponseDto = {
  id: string;
  platformVideoId: string;
  tiktokProfileId?: string | null | undefined;
  caption?: string | null | undefined;
  postUrl?: string | null | undefined;
  authorUsername?: string | null | undefined;
  authorDisplayName?: string | null | undefined;
  authorProfileUrl?: string | null | undefined;
  playCount?: number | null | undefined;
  likeCount?: number | null | undefined;
  commentCount?: number | null | undefined;
  shareCount?: number | null | undefined;
  hashtags?: Array<string> | null | undefined;
  cdnUrl?: string | null | undefined;
  s3Key?: string | null | undefined;
  thumbnailS3Key?: string | null | undefined;
  durationSecs?: number | null | undefined;
  postedAt?: string | null | undefined;
  createdAt: string;
};

/** @internal */
export const TikTokVideoResponseDto$inboundSchema: z.ZodMiniType<
  TikTokVideoResponseDto,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    platform_video_id: types.string(),
    tiktok_profile_id: z.optional(z.nullable(types.string())),
    caption: z.optional(z.nullable(types.string())),
    post_url: z.optional(z.nullable(types.string())),
    author_username: z.optional(z.nullable(types.string())),
    author_display_name: z.optional(z.nullable(types.string())),
    author_profile_url: z.optional(z.nullable(types.string())),
    play_count: z.optional(z.nullable(types.number())),
    like_count: z.optional(z.nullable(types.number())),
    comment_count: z.optional(z.nullable(types.number())),
    share_count: z.optional(z.nullable(types.number())),
    hashtags: z.optional(z.nullable(z.array(types.string()))),
    cdn_url: z.optional(z.nullable(types.string())),
    s3_key: z.optional(z.nullable(types.string())),
    thumbnail_s3_key: z.optional(z.nullable(types.string())),
    duration_secs: z.optional(z.nullable(types.number())),
    posted_at: z.optional(z.nullable(types.string())),
    created_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "platform_video_id": "platformVideoId",
      "tiktok_profile_id": "tiktokProfileId",
      "post_url": "postUrl",
      "author_username": "authorUsername",
      "author_display_name": "authorDisplayName",
      "author_profile_url": "authorProfileUrl",
      "play_count": "playCount",
      "like_count": "likeCount",
      "comment_count": "commentCount",
      "share_count": "shareCount",
      "cdn_url": "cdnUrl",
      "s3_key": "s3Key",
      "thumbnail_s3_key": "thumbnailS3Key",
      "duration_secs": "durationSecs",
      "posted_at": "postedAt",
      "created_at": "createdAt",
    });
  }),
);

export function tikTokVideoResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<TikTokVideoResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TikTokVideoResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TikTokVideoResponseDto' from JSON`,
  );
}
