/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type TikTokProfileSeedResponseDto = {
  "username": string;
  "tiktok_user_id"?: string | null;
  "display_name"?: string | null;
  "bio"?: string | null;
  "follower_count"?: number | null;
  "following_count"?: number | null;
  "verified"?: boolean | null;
  "avatar_url"?: string | null;
};
export type TikTokProfileSeedResponseDto$Outbound = TikTokProfileSeedResponseDto;

export const TikTokProfileSeedResponseDto$inboundSchema = (z.object({
  "username": z.string(),
  "tiktok_user_id": z.optional(z.nullable(z.string())),
  "display_name": z.optional(z.nullable(z.string())),
  "bio": z.optional(z.nullable(z.string())),
  "follower_count": z.optional(z.nullable(z.number())),
  "following_count": z.optional(z.nullable(z.number())),
  "verified": z.optional(z.nullable(z.boolean())),
  "avatar_url": z.optional(z.nullable(z.string())),
})) as z.ZodType<TikTokProfileSeedResponseDto>;
export const TikTokProfileSeedResponseDto$outboundSchema = (z.object({
  "username": z.string(),
  "tiktok_user_id": z.optional(z.nullable(z.string())),
  "display_name": z.optional(z.nullable(z.string())),
  "bio": z.optional(z.nullable(z.string())),
  "follower_count": z.optional(z.nullable(z.number())),
  "following_count": z.optional(z.nullable(z.number())),
  "verified": z.optional(z.nullable(z.boolean())),
  "avatar_url": z.optional(z.nullable(z.string())),
})) as z.ZodType<TikTokProfileSeedResponseDto$Outbound>;

export function tikTokProfileSeedResponseDtoFromJSON(jsonString: string): TikTokProfileSeedResponseDto {
  return TikTokProfileSeedResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as TikTokProfileSeedResponseDto;
}

export function tikTokProfileSeedResponseDtoToJSON(value: TikTokProfileSeedResponseDto): string {
  return JSON.stringify(TikTokProfileSeedResponseDto$outboundSchema.parse(value));
}
