/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TikTokVideoResponseDto,
  TikTokVideoResponseDto$inboundSchema,
} from "./tik-tok-video-response-dto.js";

export type Profile = {
  username: string;
  tiktokUserId?: string | null | undefined;
  displayName?: string | null | undefined;
  bio?: string | null | undefined;
  followerCount?: number | null | undefined;
  followingCount?: number | null | undefined;
  verified?: boolean | null | undefined;
  avatarUrl?: string | null | undefined;
};

export type TikTokProfileScrapeResponseDto = {
  profile: Profile | null;
  videos: Array<TikTokVideoResponseDto>;
};

/** @internal */
export const Profile$inboundSchema: z.ZodMiniType<Profile, unknown> = z.pipe(
  z.object({
    username: types.string(),
    tiktok_user_id: z.optional(z.nullable(types.string())),
    display_name: z.optional(z.nullable(types.string())),
    bio: z.optional(z.nullable(types.string())),
    follower_count: z.optional(z.nullable(types.number())),
    following_count: z.optional(z.nullable(types.number())),
    verified: z.optional(z.nullable(types.boolean())),
    avatar_url: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tiktok_user_id": "tiktokUserId",
      "display_name": "displayName",
      "follower_count": "followerCount",
      "following_count": "followingCount",
      "avatar_url": "avatarUrl",
    });
  }),
);

export function profileFromJSON(
  jsonString: string,
): SafeParseResult<Profile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Profile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Profile' from JSON`,
  );
}

/** @internal */
export const TikTokProfileScrapeResponseDto$inboundSchema: z.ZodMiniType<
  TikTokProfileScrapeResponseDto,
  unknown
> = z.object({
  profile: types.nullable(z.lazy(() => Profile$inboundSchema)),
  videos: z.array(TikTokVideoResponseDto$inboundSchema),
});

export function tikTokProfileScrapeResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<TikTokProfileScrapeResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TikTokProfileScrapeResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TikTokProfileScrapeResponseDto' from JSON`,
  );
}
