/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type TikTokVideoResponseDto = {
  "id": string;
  "platform_video_id": string;
  "tiktok_profile_id"?: string | null;
  "caption"?: string | null;
  "post_url"?: string | null;
  "author_username"?: string | null;
  "author_display_name"?: string | null;
  "author_profile_url"?: string | null;
  "play_count"?: number | null;
  "like_count"?: number | null;
  "comment_count"?: number | null;
  "share_count"?: number | null;
  "hashtags"?: string[] | null;
  "cdn_url"?: string | null;
  "s3_key"?: string | null;
  "thumbnail_s3_key"?: string | null;
  "duration_secs"?: number | null;
  "posted_at"?: string | null;
  "created_at": string;
};
export type TikTokVideoResponseDto$Outbound = TikTokVideoResponseDto;

export const TikTokVideoResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "platform_video_id": z.string(),
  "tiktok_profile_id": z.optional(z.nullable(z.string())),
  "caption": z.optional(z.nullable(z.string())),
  "post_url": z.optional(z.nullable(z.string())),
  "author_username": z.optional(z.nullable(z.string())),
  "author_display_name": z.optional(z.nullable(z.string())),
  "author_profile_url": z.optional(z.nullable(z.string())),
  "play_count": z.optional(z.nullable(z.number())),
  "like_count": z.optional(z.nullable(z.number())),
  "comment_count": z.optional(z.nullable(z.number())),
  "share_count": z.optional(z.nullable(z.number())),
  "hashtags": z.optional(z.nullable(z.array(z.string()))),
  "cdn_url": z.optional(z.nullable(z.string())),
  "s3_key": z.optional(z.nullable(z.string())),
  "thumbnail_s3_key": z.optional(z.nullable(z.string())),
  "duration_secs": z.optional(z.nullable(z.number())),
  "posted_at": z.optional(z.nullable(z.string())),
  "created_at": z.string(),
})) as z.ZodType<TikTokVideoResponseDto>;
export const TikTokVideoResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "platform_video_id": z.string(),
  "tiktok_profile_id": z.optional(z.nullable(z.string())),
  "caption": z.optional(z.nullable(z.string())),
  "post_url": z.optional(z.nullable(z.string())),
  "author_username": z.optional(z.nullable(z.string())),
  "author_display_name": z.optional(z.nullable(z.string())),
  "author_profile_url": z.optional(z.nullable(z.string())),
  "play_count": z.optional(z.nullable(z.number())),
  "like_count": z.optional(z.nullable(z.number())),
  "comment_count": z.optional(z.nullable(z.number())),
  "share_count": z.optional(z.nullable(z.number())),
  "hashtags": z.optional(z.nullable(z.array(z.string()))),
  "cdn_url": z.optional(z.nullable(z.string())),
  "s3_key": z.optional(z.nullable(z.string())),
  "thumbnail_s3_key": z.optional(z.nullable(z.string())),
  "duration_secs": z.optional(z.nullable(z.number())),
  "posted_at": z.optional(z.nullable(z.string())),
  "created_at": z.string(),
})) as z.ZodType<TikTokVideoResponseDto$Outbound>;

export function tikTokVideoResponseDtoFromJSON(jsonString: string): TikTokVideoResponseDto {
  return TikTokVideoResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as TikTokVideoResponseDto;
}

export function tikTokVideoResponseDtoToJSON(value: TikTokVideoResponseDto): string {
  return JSON.stringify(TikTokVideoResponseDto$outboundSchema.parse(value));
}
