/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { TikTokProfileSeedResponseDto } from "./tik-tok-profile-seed-response-dto.js";
import { TikTokProfileSeedResponseDto$inboundSchema, TikTokProfileSeedResponseDto$outboundSchema } from "./tik-tok-profile-seed-response-dto.js";
import type { TikTokRelatedVideoResponseDto } from "./tik-tok-related-video-response-dto.js";
import { TikTokRelatedVideoResponseDto$inboundSchema, TikTokRelatedVideoResponseDto$outboundSchema } from "./tik-tok-related-video-response-dto.js";
import type { TikTokVideoResponseDto } from "./tik-tok-video-response-dto.js";
import { TikTokVideoResponseDto$inboundSchema, TikTokVideoResponseDto$outboundSchema } from "./tik-tok-video-response-dto.js";

export type TikTokProfileScrapeResponseDto = {
  "profile": (TikTokProfileSeedResponseDto);
  "videos": TikTokVideoResponseDto[];
  "relatedVideos": TikTokRelatedVideoResponseDto[];
};
export type TikTokProfileScrapeResponseDto$Outbound = TikTokProfileScrapeResponseDto;

export const TikTokProfileScrapeResponseDto$inboundSchema = (z.object({
  "profile": z.lazy(() => TikTokProfileSeedResponseDto$inboundSchema),
  "videos": z.array(z.lazy(() => TikTokVideoResponseDto$inboundSchema)),
  "relatedVideos": z.array(z.lazy(() => TikTokRelatedVideoResponseDto$inboundSchema)),
})) as z.ZodType<TikTokProfileScrapeResponseDto>;
export const TikTokProfileScrapeResponseDto$outboundSchema = (z.object({
  "profile": z.lazy(() => TikTokProfileSeedResponseDto$outboundSchema),
  "videos": z.array(z.lazy(() => TikTokVideoResponseDto$outboundSchema)),
  "relatedVideos": z.array(z.lazy(() => TikTokRelatedVideoResponseDto$outboundSchema)),
})) as z.ZodType<TikTokProfileScrapeResponseDto$Outbound>;

export function tikTokProfileScrapeResponseDtoFromJSON(jsonString: string): TikTokProfileScrapeResponseDto {
  return TikTokProfileScrapeResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as TikTokProfileScrapeResponseDto;
}

export function tikTokProfileScrapeResponseDtoToJSON(value: TikTokProfileScrapeResponseDto): string {
  return JSON.stringify(TikTokProfileScrapeResponseDto$outboundSchema.parse(value));
}
