/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type UpdateMonitorDto = {
  "name"?: string;
  "config"?: Record<string, unknown>;
  "cadence_minutes"?: number;
  "max_results"?: number;
  "force_fresh"?: boolean;
  "cache_ttl_days"?: number;
  "status"?: "active" | "paused";
};
export type UpdateMonitorDto$Outbound = UpdateMonitorDto;

export const UpdateMonitorDto$inboundSchema = (z.object({
  "name": z.optional(z.string()),
  "config": z.optional(z.object({

})),
  "cadence_minutes": z.optional(z.number()),
  "max_results": z.optional(z.number()),
  "force_fresh": z.optional(z.boolean()),
  "cache_ttl_days": z.optional(z.number()),
  "status": z.optional(z.enum(["active","paused"])),
})) as z.ZodType<UpdateMonitorDto>;
export const UpdateMonitorDto$outboundSchema = (z.object({
  "name": z.optional(z.string()),
  "config": z.optional(z.object({

})),
  "cadence_minutes": z.optional(z.number()),
  "max_results": z.optional(z.number()),
  "force_fresh": z.optional(z.boolean()),
  "cache_ttl_days": z.optional(z.number()),
  "status": z.optional(z.enum(["active","paused"])),
})) as z.ZodType<UpdateMonitorDto$Outbound>;

export function updateMonitorDtoFromJSON(jsonString: string): UpdateMonitorDto {
  return UpdateMonitorDto$inboundSchema.parse(JSON.parse(jsonString)) as UpdateMonitorDto;
}

export function updateMonitorDtoToJSON(value: UpdateMonitorDto): string {
  return JSON.stringify(UpdateMonitorDto$outboundSchema.parse(value));
}
