/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export type UpdateMonitorDtoConfig = {};

/**
 * Only active and paused are user-settable
 */
export const UpdateMonitorDtoStatus = {
  Active: "active",
  Paused: "paused",
} as const;
/**
 * Only active and paused are user-settable
 */
export type UpdateMonitorDtoStatus = ClosedEnum<typeof UpdateMonitorDtoStatus>;

export type UpdateMonitorDto = {
  name?: string | undefined;
  config?: UpdateMonitorDtoConfig | undefined;
  cadenceMinutes?: number | undefined;
  maxResults?: number | undefined;
  forceFresh?: boolean | undefined;
  cacheTtlDays?: number | undefined;
  /**
   * Only active and paused are user-settable
   */
  status?: UpdateMonitorDtoStatus | undefined;
};

/** @internal */
export type UpdateMonitorDtoConfig$Outbound = {};

/** @internal */
export const UpdateMonitorDtoConfig$outboundSchema: z.ZodMiniType<
  UpdateMonitorDtoConfig$Outbound,
  UpdateMonitorDtoConfig
> = z.object({});

export function updateMonitorDtoConfigToJSON(
  updateMonitorDtoConfig: UpdateMonitorDtoConfig,
): string {
  return JSON.stringify(
    UpdateMonitorDtoConfig$outboundSchema.parse(updateMonitorDtoConfig),
  );
}

/** @internal */
export const UpdateMonitorDtoStatus$outboundSchema: z.ZodMiniEnum<
  typeof UpdateMonitorDtoStatus
> = z.enum(UpdateMonitorDtoStatus);

/** @internal */
export type UpdateMonitorDto$Outbound = {
  name?: string | undefined;
  config?: UpdateMonitorDtoConfig$Outbound | undefined;
  cadence_minutes?: number | undefined;
  max_results?: number | undefined;
  force_fresh?: boolean | undefined;
  cache_ttl_days?: number | undefined;
  status?: string | undefined;
};

/** @internal */
export const UpdateMonitorDto$outboundSchema: z.ZodMiniType<
  UpdateMonitorDto$Outbound,
  UpdateMonitorDto
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    config: z.optional(z.lazy(() => UpdateMonitorDtoConfig$outboundSchema)),
    cadenceMinutes: z.optional(z.number()),
    maxResults: z.optional(z.number()),
    forceFresh: z.optional(z.boolean()),
    cacheTtlDays: z.optional(z.number()),
    status: z.optional(UpdateMonitorDtoStatus$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      cadenceMinutes: "cadence_minutes",
      maxResults: "max_results",
      forceFresh: "force_fresh",
      cacheTtlDays: "cache_ttl_days",
    });
  }),
);

export function updateMonitorDtoToJSON(
  updateMonitorDto: UpdateMonitorDto,
): string {
  return JSON.stringify(
    UpdateMonitorDto$outboundSchema.parse(updateMonitorDto),
  );
}
