/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WebCrawlPageResponseDto = {
  url: string;
  content: string;
  title?: string | null | undefined;
};

/** @internal */
export const WebCrawlPageResponseDto$inboundSchema: z.ZodMiniType<
  WebCrawlPageResponseDto,
  unknown
> = z.object({
  url: types.string(),
  content: types.string(),
  title: z.optional(z.nullable(types.string())),
});

export function webCrawlPageResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<WebCrawlPageResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebCrawlPageResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebCrawlPageResponseDto' from JSON`,
  );
}
