/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WebScrapeResponseDto = {
  url: string;
  text: string;
  statusCode?: number | null | undefined;
};

/** @internal */
export const WebScrapeResponseDto$inboundSchema: z.ZodMiniType<
  WebScrapeResponseDto,
  unknown
> = z.object({
  url: types.string(),
  text: types.string(),
  statusCode: z.optional(z.nullable(types.number())),
});

export function webScrapeResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<WebScrapeResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebScrapeResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebScrapeResponseDto' from JSON`,
  );
}
