/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";
import type { WebSearchResultItemResponseDto } from "./web-search-result-item-response-dto.js";
import { WebSearchResultItemResponseDto$inboundSchema, WebSearchResultItemResponseDto$outboundSchema } from "./web-search-result-item-response-dto.js";

export type WebSearchResponseDto = {
  "query": string;
  "results": WebSearchResultItemResponseDto[];
  "totalResults"?: number | null;
};
export type WebSearchResponseDto$Outbound = WebSearchResponseDto;

export const WebSearchResponseDto$inboundSchema = (z.object({
  "query": z.string(),
  "results": z.array(z.lazy(() => WebSearchResultItemResponseDto$inboundSchema)),
  "totalResults": z.optional(z.nullable(z.number())),
})) as z.ZodType<WebSearchResponseDto>;
export const WebSearchResponseDto$outboundSchema = (z.object({
  "query": z.string(),
  "results": z.array(z.lazy(() => WebSearchResultItemResponseDto$outboundSchema)),
  "totalResults": z.optional(z.nullable(z.number())),
})) as z.ZodType<WebSearchResponseDto$Outbound>;

export function webSearchResponseDtoFromJSON(jsonString: string): WebSearchResponseDto {
  return WebSearchResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as WebSearchResponseDto;
}

export function webSearchResponseDtoToJSON(value: WebSearchResponseDto): string {
  return JSON.stringify(WebSearchResponseDto$outboundSchema.parse(value));
}
