/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WebSearchResultItemResponseDto,
  WebSearchResultItemResponseDto$inboundSchema,
} from "./web-search-result-item-response-dto.js";

export type WebSearchResponseDto = {
  query: string;
  results: Array<WebSearchResultItemResponseDto>;
  totalResults?: number | null | undefined;
};

/** @internal */
export const WebSearchResponseDto$inboundSchema: z.ZodMiniType<
  WebSearchResponseDto,
  unknown
> = z.object({
  query: types.string(),
  results: z.array(WebSearchResultItemResponseDto$inboundSchema),
  totalResults: z.optional(z.nullable(types.number())),
});

export function webSearchResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<WebSearchResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebSearchResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebSearchResponseDto' from JSON`,
  );
}
