/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type WebScrapeBatchAcceptedResponseDto = {
  "id": string;
  "operationId": string;
  "status": "queued";
  "pollUrl": string;
};
export type WebScrapeBatchAcceptedResponseDto$Outbound = WebScrapeBatchAcceptedResponseDto;

export const WebScrapeBatchAcceptedResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
})) as z.ZodType<WebScrapeBatchAcceptedResponseDto>;
export const WebScrapeBatchAcceptedResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued"]),
  "pollUrl": z.string(),
})) as z.ZodType<WebScrapeBatchAcceptedResponseDto$Outbound>;

export function webScrapeBatchAcceptedResponseDtoFromJSON(jsonString: string): WebScrapeBatchAcceptedResponseDto {
  return WebScrapeBatchAcceptedResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as WebScrapeBatchAcceptedResponseDto;
}

export function webScrapeBatchAcceptedResponseDtoToJSON(value: WebScrapeBatchAcceptedResponseDto): string {
  return JSON.stringify(WebScrapeBatchAcceptedResponseDto$outboundSchema.parse(value));
}
