/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type WebScrapeResponseDto = {
  "url": string;
  "text": string;
  "statusCode"?: number | null;
};
export type WebScrapeResponseDto$Outbound = WebScrapeResponseDto;

export const WebScrapeResponseDto$inboundSchema = (z.object({
  "url": z.string(),
  "text": z.string(),
  "statusCode": z.optional(z.nullable(z.number())),
})) as z.ZodType<WebScrapeResponseDto>;
export const WebScrapeResponseDto$outboundSchema = (z.object({
  "url": z.string(),
  "text": z.string(),
  "statusCode": z.optional(z.nullable(z.number())),
})) as z.ZodType<WebScrapeResponseDto$Outbound>;

export function webScrapeResponseDtoFromJSON(jsonString: string): WebScrapeResponseDto {
  return WebScrapeResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as WebScrapeResponseDto;
}

export function webScrapeResponseDtoToJSON(value: WebScrapeResponseDto): string {
  return JSON.stringify(WebScrapeResponseDto$outboundSchema.parse(value));
}
