/*
 * Code generated by The Hog SDK generator. DO NOT EDIT.
 */

import * as z from "zod/v4";

export type WebCrawlAcceptedResponseDto = {
  "id": string;
  "operationId": string;
  "status": "queued" | "processing" | "succeeded" | "failed" | "partial_success" | "cancelled";
  "pollUrl": string;
};
export type WebCrawlAcceptedResponseDto$Outbound = WebCrawlAcceptedResponseDto;

export const WebCrawlAcceptedResponseDto$inboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued","processing","succeeded","failed","partial_success","cancelled"]),
  "pollUrl": z.string(),
})) as z.ZodType<WebCrawlAcceptedResponseDto>;
export const WebCrawlAcceptedResponseDto$outboundSchema = (z.object({
  "id": z.string(),
  "operationId": z.string(),
  "status": z.enum(["queued","processing","succeeded","failed","partial_success","cancelled"]),
  "pollUrl": z.string(),
})) as z.ZodType<WebCrawlAcceptedResponseDto$Outbound>;

export function webCrawlAcceptedResponseDtoFromJSON(jsonString: string): WebCrawlAcceptedResponseDto {
  return WebCrawlAcceptedResponseDto$inboundSchema.parse(JSON.parse(jsonString)) as WebCrawlAcceptedResponseDto;
}

export function webCrawlAcceptedResponseDtoToJSON(value: WebCrawlAcceptedResponseDto): string {
  return JSON.stringify(WebCrawlAcceptedResponseDto$outboundSchema.parse(value));
}
