/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WebCrawlPageResponseDto,
  WebCrawlPageResponseDto$inboundSchema,
} from "./web-crawl-page-response-dto.js";

export type WebCrawlResponseDto = {
  domain: string;
  pages: Array<WebCrawlPageResponseDto>;
  combinedContent: string;
};

/** @internal */
export const WebCrawlResponseDto$inboundSchema: z.ZodMiniType<
  WebCrawlResponseDto,
  unknown
> = z.object({
  domain: types.string(),
  pages: z.array(WebCrawlPageResponseDto$inboundSchema),
  combinedContent: types.string(),
});

export function webCrawlResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<WebCrawlResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebCrawlResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebCrawlResponseDto' from JSON`,
  );
}
